/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod'

/**
 * @summary Create a new claim
 */

export const createClaimBodyEstimatedValueInCentsMin = 0

export const CreateClaimBody = zod.object({
  policyId: zod.string().min(1),
  clientId: zod.string().min(1),
  insurerId: zod.union([zod.enum(['']), zod.string()]).optional(),
  assignedToId: zod.union([zod.enum(['']), zod.string()]).optional(),
  priority: zod.enum(['NORMAL', 'HIGH', 'URGENT']).optional(),
  description: zod.string().min(1),
  estimatedValueInCents: zod
    .number()
    .min(createClaimBodyEstimatedValueInCentsMin)
    .optional(),
  incidentDate: zod
    .union([zod.enum(['']), zod.string().datetime({})])
    .optional(),
  incidentLocation: zod.union([zod.enum(['']), zod.string()]).optional(),
})

/**
 * @summary List claims with pagination and filters
 */
export const listClaimsQueryLimitDefault = 20
export const listClaimsQueryLimitMax = 100

export const ListClaimsQueryParams = zod.object({
  cursor: zod.string().optional(),
  limit: zod
    .number()
    .min(1)
    .max(listClaimsQueryLimitMax)
    .default(listClaimsQueryLimitDefault),
  status: zod
    .enum([
      'REGISTERED',
      'IN_ANALYSIS',
      'AWAITING_DOCUMENT',
      'PENDING_INSPECTION',
      'APPROVED',
      'REJECTED',
      'PAID',
      'COMPLETED',
    ])
    .optional(),
  priority: zod.enum(['NORMAL', 'HIGH', 'URGENT']).optional(),
  policyId: zod.string().optional(),
  clientId: zod.string().optional(),
  search: zod.string().optional(),
})

export const ListClaimsResponse = zod.object({
  success: zod.literal(true),
  data: zod.array(
    zod.object({
      id: zod.string(),
      organizationId: zod.string(),
      claimNumber: zod.number(),
      policyId: zod.string(),
      clientId: zod.string(),
      insurerId: zod.string().nullable(),
      assignedToId: zod.string().nullable(),
      status: zod.enum([
        'REGISTERED',
        'IN_ANALYSIS',
        'AWAITING_DOCUMENT',
        'PENDING_INSPECTION',
        'APPROVED',
        'REJECTED',
        'PAID',
        'COMPLETED',
      ]),
      priority: zod.enum(['NORMAL', 'HIGH', 'URGENT']),
      description: zod.string(),
      estimatedValueInCents: zod.number().nullable(),
      incidentDate: zod.string().datetime({}).nullable(),
      incidentLocation: zod.string().nullable(),
      reportedAt: zod.string().datetime({}),
      resolvedAt: zod.string().datetime({}).nullable(),
      closedAt: zod.string().datetime({}).nullable(),
      createdAt: zod.string().datetime({}),
      updatedAt: zod.string().datetime({}),
      policyNumber: zod.string().optional(),
      clientName: zod.string().optional(),
      insurerName: zod.string().optional(),
      assignedToName: zod.string().optional(),
    })
  ),
  meta: zod.object({
    total: zod.number().optional(),
    nextCursor: zod.string().nullish(),
  }),
})

/**
 * @summary Get a claim by ID
 */

export const GetClaimParams = zod.object({
  id: zod.string().min(1),
})

export const GetClaimResponse = zod.object({
  success: zod.literal(true),
  data: zod.object({
    id: zod.string(),
    organizationId: zod.string(),
    claimNumber: zod.number(),
    policyId: zod.string(),
    clientId: zod.string(),
    insurerId: zod.string().nullable(),
    assignedToId: zod.string().nullable(),
    status: zod.enum([
      'REGISTERED',
      'IN_ANALYSIS',
      'AWAITING_DOCUMENT',
      'PENDING_INSPECTION',
      'APPROVED',
      'REJECTED',
      'PAID',
      'COMPLETED',
    ]),
    priority: zod.enum(['NORMAL', 'HIGH', 'URGENT']),
    description: zod.string(),
    estimatedValueInCents: zod.number().nullable(),
    incidentDate: zod.string().datetime({}).nullable(),
    incidentLocation: zod.string().nullable(),
    reportedAt: zod.string().datetime({}),
    resolvedAt: zod.string().datetime({}).nullable(),
    closedAt: zod.string().datetime({}).nullable(),
    createdAt: zod.string().datetime({}),
    updatedAt: zod.string().datetime({}),
    policyNumber: zod.string().optional(),
    clientName: zod.string().optional(),
    insurerName: zod.string().optional(),
    assignedToName: zod.string().optional(),
  }),
})

/**
 * @summary Soft-delete a claim
 */

export const DeleteClaimParams = zod.object({
  id: zod.string().min(1),
})

/**
 * @summary Update the status of a claim
 */

export const UpdateClaimStatusParams = zod.object({
  id: zod.string().min(1),
})

export const UpdateClaimStatusBody = zod.object({
  status: zod.enum([
    'REGISTERED',
    'IN_ANALYSIS',
    'AWAITING_DOCUMENT',
    'PENDING_INSPECTION',
    'APPROVED',
    'REJECTED',
    'PAID',
    'COMPLETED',
  ]),
})

export const UpdateClaimStatusResponse = zod.object({
  success: zod.literal(true),
  data: zod.object({
    id: zod.string(),
    organizationId: zod.string(),
    claimNumber: zod.number(),
    policyId: zod.string(),
    clientId: zod.string(),
    insurerId: zod.string().nullable(),
    assignedToId: zod.string().nullable(),
    status: zod.enum([
      'REGISTERED',
      'IN_ANALYSIS',
      'AWAITING_DOCUMENT',
      'PENDING_INSPECTION',
      'APPROVED',
      'REJECTED',
      'PAID',
      'COMPLETED',
    ]),
    priority: zod.enum(['NORMAL', 'HIGH', 'URGENT']),
    description: zod.string(),
    estimatedValueInCents: zod.number().nullable(),
    incidentDate: zod.string().datetime({}).nullable(),
    incidentLocation: zod.string().nullable(),
    reportedAt: zod.string().datetime({}),
    resolvedAt: zod.string().datetime({}).nullable(),
    closedAt: zod.string().datetime({}).nullable(),
    createdAt: zod.string().datetime({}),
    updatedAt: zod.string().datetime({}),
    policyNumber: zod.string().optional(),
    clientName: zod.string().optional(),
    insurerName: zod.string().optional(),
    assignedToName: zod.string().optional(),
  }),
})

/**
 * @summary Create an occurrence for a claim
 */

export const CreateClaimOccurrenceParams = zod.object({
  id: zod.string().min(1),
})

export const CreateClaimOccurrenceBody = zod.object({
  type: zod.string().min(1),
  description: zod.string().min(1),
  metadata: zod
    .record(
      zod.string(),
      zod.union([
        zod.union([
          zod.string(),
          zod.number(),
          zod.boolean(),
          zod.enum(['null']).nullable(),
        ]),
        zod.array(zod.unknown()),
        zod.record(zod.string(), zod.unknown()),
      ])
    )
    .optional(),
})

/**
 * @summary List occurrences for a claim
 */

export const ListClaimOccurrencesParams = zod.object({
  id: zod.string().min(1),
})

export const ListClaimOccurrencesResponse = zod.object({
  success: zod.literal(true),
  data: zod.array(
    zod.object({
      id: zod.string(),
      claimId: zod.string(),
      organizationId: zod.string(),
      type: zod.string(),
      description: zod.string(),
      metadata: zod
        .record(
          zod.string(),
          zod.union([
            zod.union([
              zod.string(),
              zod.number(),
              zod.boolean(),
              zod.enum(['null']).nullable(),
            ]),
            zod.array(zod.unknown()),
            zod.record(zod.string(), zod.unknown()),
          ])
        )
        .nullable(),
      createdBy: zod.string().nullable(),
      createdAt: zod.string().datetime({}),
      createdByName: zod.string().optional(),
    })
  ),
})
