/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { AcceptTerms409Error } from './acceptTerms409Error'

export type AcceptTerms409 = {
  success: boolean
  error: AcceptTerms409Error
}
