/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type AcceptInvitationBody =
  | {
      mode: 'register'
      /** @minLength 2 */
      name: string
      /** @minLength 8 */
      password: string
    }
  | {
      mode: 'login'
      /** @minLength 1 */
      password: string
    }
  | {
      mode: 'current-session'
    }
