/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { AcceptInvitation422Error } from './acceptInvitation422Error'

export type AcceptInvitation422 = {
  success: boolean
  error: AcceptInvitation422Error
}
