/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { AcceptTerms200Data } from './acceptTerms200Data'

export type AcceptTerms200 = {
  success: boolean
  data: AcceptTerms200Data
}
