/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { AcceptInvitation400Error } from './acceptInvitation400Error'

export type AcceptInvitation400 = {
  success: boolean
  error: AcceptInvitation400Error
}
