/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { AcceptInvitation401Error } from './acceptInvitation401Error'

export type AcceptInvitation401 = {
  success: boolean
  error: AcceptInvitation401Error
}
