/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminListAiUsage200DataItemUnitType } from './adminListAiUsage200DataItemUnitType'

export type AdminListAiUsage200DataItem = {
  organizationId: string
  periodKey: string
  /** @nullable */
  channelIdHash: string | null
  /** @nullable */
  conversationIdHash: string | null
  /** @nullable */
  messageIdHash: string | null
  /** @nullable */
  agentIdHash: string | null
  provider: string
  model: string
  inputQuantity: number
  outputQuantity: number
  unitType: AdminListAiUsage200DataItemUnitType
  inputCostMicrocents: number
  outputCostMicrocents: number
  /** @nullable */
  countedAsIncluded: boolean | null
  /** @nullable */
  overageCents: number | null
  createdAt: string
}
