/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type AdminListAiUsageParams = {
  /**
   * @minLength 1
   */
  organizationId: string
  /**
   * @pattern ^\d{4}-\d{2}$
   */
  periodKey?: string
  cursor?: string
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number
}
