/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type AdminListAiUsage200DataItemUnitType =
  (typeof AdminListAiUsage200DataItemUnitType)[keyof typeof AdminListAiUsage200DataItemUnitType]

export const AdminListAiUsage200DataItemUnitType = {
  TOKEN: 'TOKEN',
  CHARACTER: 'CHARACTER',
  IMAGE: 'IMAGE',
} as const
