/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type AdvanceProposal200DataBoardType =
  (typeof AdvanceProposal200DataBoardType)[keyof typeof AdvanceProposal200DataBoardType]

export const AdvanceProposal200DataBoardType = {
  NEW_INSURANCE: 'NEW_INSURANCE',
  RENEWAL: 'RENEWAL',
} as const
