/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { AdvanceProposal400Error } from './advanceProposal400Error'

export type AdvanceProposal400 = {
  success: boolean
  error: AdvanceProposal400Error
}
