/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { AdvanceProposal404Error } from './advanceProposal404Error'

export type AdvanceProposal404 = {
  success: boolean
  error: AdvanceProposal404Error
}
