/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { AdvanceProposal200Data } from './advanceProposal200Data'

export type AdvanceProposal200 = {
  success: boolean
  data: AdvanceProposal200Data
}
