/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { AdvanceProposal200DataBoardType } from './advanceProposal200DataBoardType'
import type { AdvanceProposal200DataBranch } from './advanceProposal200DataBranch'
import type { AdvanceProposal200DataDetails } from './advanceProposal200DataDetails'
import type { AdvanceProposal200DataSourcePolicySnapshot } from './advanceProposal200DataSourcePolicySnapshot'
import type { AdvanceProposal200DataStage } from './advanceProposal200DataStage'

export type AdvanceProposal200Data = {
  id: string
  organizationId: string
  contactId: string
  salespersonId: string
  stage: AdvanceProposal200DataStage
  boardType: AdvanceProposal200DataBoardType
  branch: AdvanceProposal200DataBranch
  premiumValueInCents: number
  commissionPercentageInCents: number
  details: AdvanceProposal200DataDetails
  /** @nullable */
  lostReason: string | null
  /** @nullable */
  renewalPolicyId: string | null
  /** @nullable */
  renewalPolicyNumber: string | null
  /** @nullable */
  sourcePolicyId: string | null
  /** @nullable */
  endorsementType: string | null
  /** @nullable */
  endorsementReason: string | null
  /** @nullable */
  sourcePolicySnapshot: AdvanceProposal200DataSourcePolicySnapshot
  /** @nullable */
  insurerId: string | null
  /** @nullable */
  deletedAt: string | null
  createdAt: string
  updatedAt: string
  /** @nullable */
  coverageStartDate: string | null
  /** @nullable */
  coverageEndDate: string | null
  /** @nullable */
  sentToClientAt: string | null
  /** @nullable */
  clientResponseAt: string | null
  /** @nullable */
  quoteValidUntil: string | null
  clientName?: string
  clientDocument?: string
  clientPersonType?: string
  salespersonName?: string
  insurerName?: string
}
