/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type ApproveCommissionCommercial200DataStatus =
  (typeof ApproveCommissionCommercial200DataStatus)[keyof typeof ApproveCommissionCommercial200DataStatus]

export const ApproveCommissionCommercial200DataStatus = {
  PENDING_COMMERCIAL: 'PENDING_COMMERCIAL',
  PENDING_ADMIN: 'PENDING_ADMIN',
  APPROVED: 'APPROVED',
  PAID: 'PAID',
  REJECTED: 'REJECTED',
  REVERSED: 'REVERSED',
} as const
