/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { CancelPolicy200DataBranch } from './cancelPolicy200DataBranch'
import type { CancelPolicy200DataCoverageDetails } from './cancelPolicy200DataCoverageDetails'
import type { CancelPolicy200DataStatus } from './cancelPolicy200DataStatus'

export type CancelPolicy200Data = {
  id: string
  organizationId: string
  proposalId: string
  clientId: string
  salespersonId: string
  policyNumber: string
  status: CancelPolicy200DataStatus
  branch: CancelPolicy200DataBranch
  premiumValueInCents: number
  /** @nullable */
  coverageDetails: CancelPolicy200DataCoverageDetails
  startDate: string
  endDate: string
  /** @nullable */
  cancelledAt: string | null
  /** @nullable */
  cancelReason: string | null
  createdAt: string
  updatedAt: string
  clientName?: string
  clientDocument?: string
  salespersonName?: string
  insurerName?: string
  proposalIdentifier?: string
}
