/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { CancelPolicy200Data } from './cancelPolicy200Data'

export type CancelPolicy200 = {
  success: boolean
  data: CancelPolicy200Data
}
