/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { CancelBillingSubscription400Error } from './cancelBillingSubscription400Error'

export type CancelBillingSubscription400 = {
  success: boolean
  error: CancelBillingSubscription400Error
}
