/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type CancelPolicy200DataBranch =
  (typeof CancelPolicy200DataBranch)[keyof typeof CancelPolicy200DataBranch]

export const CancelPolicy200DataBranch = {
  AUTO: 'AUTO',
  RESIDENTIAL: 'RESIDENTIAL',
  CONDOMINIUM: 'CONDOMINIUM',
  BUSINESS: 'BUSINESS',
  LIFE: 'LIFE',
  OTHER: 'OTHER',
} as const
