/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { CompleteOnboarding200DataRedirectTo } from './completeOnboarding200DataRedirectTo'

export type CompleteOnboarding200Data = {
  organizationId: string
  subscriptionId: string
  redirectTo: CompleteOnboarding200DataRedirectTo
}
