/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type CompleteOnboarding200DataRedirectTo =
  (typeof CompleteOnboarding200DataRedirectTo)[keyof typeof CompleteOnboarding200DataRedirectTo]

export const CompleteOnboarding200DataRedirectTo = {
  '/dashboard': '/dashboard',
} as const
