/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { CompleteOnboarding404Error } from './completeOnboarding404Error'

export type CompleteOnboarding404 = {
  success: boolean
  error: CompleteOnboarding404Error
}
