/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateClaimOccurrence201Data } from './createClaimOccurrence201Data'

export type CreateClaimOccurrence201 = {
  success: boolean
  data: CreateClaimOccurrence201Data
}
