/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateInternalClaim201DataClaimData } from './createInternalClaim201DataClaimData'

export type CreateInternalClaim201Data = {
  claimCreated: boolean
  /** @nullable */
  claimNumber: string | null
  dataSaved: boolean
  /** @nullable */
  claimData: CreateInternalClaim201DataClaimData
  message: string
}
