/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateProposal201DataBoardType } from './createProposal201DataBoardType'
import type { CreateProposal201DataBranch } from './createProposal201DataBranch'
import type { CreateProposal201DataDetails } from './createProposal201DataDetails'
import type { CreateProposal201DataSourcePolicySnapshot } from './createProposal201DataSourcePolicySnapshot'
import type { CreateProposal201DataStage } from './createProposal201DataStage'

export type CreateProposal201Data = {
  id: string
  organizationId: string
  contactId: string
  salespersonId: string
  stage: CreateProposal201DataStage
  boardType: CreateProposal201DataBoardType
  branch: CreateProposal201DataBranch
  premiumValueInCents: number
  commissionPercentageInCents: number
  details: CreateProposal201DataDetails
  /** @nullable */
  lostReason: string | null
  /** @nullable */
  renewalPolicyId: string | null
  /** @nullable */
  renewalPolicyNumber: string | null
  /** @nullable */
  sourcePolicyId: string | null
  /** @nullable */
  endorsementType: string | null
  /** @nullable */
  endorsementReason: string | null
  /** @nullable */
  sourcePolicySnapshot: CreateProposal201DataSourcePolicySnapshot
  /** @nullable */
  insurerId: string | null
  /** @nullable */
  deletedAt: string | null
  createdAt: string
  updatedAt: string
  /** @nullable */
  coverageStartDate: string | null
  /** @nullable */
  coverageEndDate: string | null
  /** @nullable */
  sentToClientAt: string | null
  /** @nullable */
  clientResponseAt: string | null
  /** @nullable */
  quoteValidUntil: string | null
  clientName?: string
  clientDocument?: string
  clientPersonType?: string
  salespersonName?: string
  insurerName?: string
}
