/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateProposalBodyBoardType } from './createProposalBodyBoardType'
import type { CreateProposalBodyBranch } from './createProposalBodyBranch'

export type CreateProposalBody = {
  /** @minLength 1 */
  clientId: string
  branch: CreateProposalBodyBranch
  boardType: CreateProposalBodyBoardType
  renewalPolicyId?: string
  insurerId?: string
}
