/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateClaim201Data } from './createClaim201Data'

export type CreateClaim201 = {
  success: boolean
  data: CreateClaim201Data
}
