/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type CreateContact201DataStage =
  (typeof CreateContact201DataStage)[keyof typeof CreateContact201DataStage]

export const CreateContact201DataStage = {
  LEAD: 'LEAD',
  CLIENT_NEW: 'CLIENT_NEW',
  CLIENT_ACTIVE: 'CLIENT_ACTIVE',
  CLIENT_INACTIVE: 'CLIENT_INACTIVE',
} as const
