/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateContact400Error } from './createContact400Error'

export type CreateContact400 = {
  success: boolean
  error: CreateContact400Error
}
