/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateClaim201DataPriority } from './createClaim201DataPriority'
import type { CreateClaim201DataStatus } from './createClaim201DataStatus'

export type CreateClaim201Data = {
  id: string
  organizationId: string
  claimNumber: number
  policyId: string
  clientId: string
  /** @nullable */
  insurerId: string | null
  /** @nullable */
  assignedToId: string | null
  status: CreateClaim201DataStatus
  priority: CreateClaim201DataPriority
  description: string
  /** @nullable */
  estimatedValueInCents: number | null
  /** @nullable */
  incidentDate: string | null
  /** @nullable */
  incidentLocation: string | null
  reportedAt: string
  /** @nullable */
  resolvedAt: string | null
  /** @nullable */
  closedAt: string | null
  createdAt: string
  updatedAt: string
  policyNumber?: string
  clientName?: string
  insurerName?: string
  assignedToName?: string
}
