/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type CreateProposalBody =
  | {
      /** @minLength 1 */
      clientId: string
      branch:
        | 'AUTO'
        | 'RESIDENTIAL'
        | 'CONDOMINIUM'
        | 'BUSINESS'
        | 'LIFE'
        | 'OTHER'
      boardType: 'NEW_INSURANCE' | 'RENEWAL'
      renewalPolicyId?: string
      insurerId?: string
    }
  | {
      boardType: 'ENDORSEMENT'
      /** @minLength 1 */
      sourcePolicyId: string
      /** @minLength 1 */
      endorsementType: string
      /** @minLength 1 */
      endorsementReason: string
    }
