/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type CreateClient201DataPersonType =
  (typeof CreateClient201DataPersonType)[keyof typeof CreateClient201DataPersonType]

export const CreateClient201DataPersonType = {
  INDIVIDUAL: 'INDIVIDUAL',
  COMPANY: 'COMPANY',
} as const
