/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type CreateProposalBodyBranch =
  (typeof CreateProposalBodyBranch)[keyof typeof CreateProposalBodyBranch]

export const CreateProposalBodyBranch = {
  AUTO: 'AUTO',
  RESIDENTIAL: 'RESIDENTIAL',
  CONDOMINIUM: 'CONDOMINIUM',
  BUSINESS: 'BUSINESS',
  LIFE: 'LIFE',
  OTHER: 'OTHER',
} as const
