/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateClient201DataAddress } from './createClient201DataAddress'
import type { CreateClient201DataMaritalStatus } from './createClient201DataMaritalStatus'
import type { CreateClient201DataPersonType } from './createClient201DataPersonType'
import type { CreateClient201DataSocialMedia } from './createClient201DataSocialMedia'
import type { CreateClient201DataType } from './createClient201DataType'

export type CreateClient201Data = {
  id: string
  name: string
  type: CreateClient201DataType
  personType: CreateClient201DataPersonType
  tags: string[]
  document: string
  /** @nullable */
  email?: string | null
  /** @nullable */
  phone?: string | null
  createdAt: string
  /** @nullable */
  socialMedia?: CreateClient201DataSocialMedia
  consentLgpd: boolean
  updatedAt: string
  /** @nullable */
  birthDate?: string | null
  /** @nullable */
  profession?: string | null
  /** @nullable */
  maritalStatus?: CreateClient201DataMaritalStatus
  /** @nullable */
  address?: CreateClient201DataAddress
}
