/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateClaimOccurrence201DataMetadata } from './createClaimOccurrence201DataMetadata'

export type CreateClaimOccurrence201Data = {
  id: string
  claimId: string
  organizationId: string
  type: string
  description: string
  /** @nullable */
  metadata: CreateClaimOccurrence201DataMetadata
  /** @nullable */
  createdBy: string | null
  createdAt: string
  createdByName?: string
}
