/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type CreateClient201DataMaritalStatus =
  | (typeof CreateClient201DataMaritalStatus)[keyof typeof CreateClient201DataMaritalStatus]
  | null

export const CreateClient201DataMaritalStatus = {
  SINGLE: 'SINGLE',
  MARRIED: 'MARRIED',
  DIVORCED: 'DIVORCED',
  WIDOWED: 'WIDOWED',
  OTHER: 'OTHER',
} as const
