/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type CreateAssistance201DataStatus =
  (typeof CreateAssistance201DataStatus)[keyof typeof CreateAssistance201DataStatus]

export const CreateAssistance201DataStatus = {
  REQUESTED: 'REQUESTED',
  AWAITING_DOCUMENT: 'AWAITING_DOCUMENT',
  PENDING_INSPECTION: 'PENDING_INSPECTION',
  DISPATCHED: 'DISPATCHED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
} as const
