/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type CreateClientBodyMaritalStatus =
  (typeof CreateClientBodyMaritalStatus)[keyof typeof CreateClientBodyMaritalStatus]

export const CreateClientBodyMaritalStatus = {
  SINGLE: 'SINGLE',
  MARRIED: 'MARRIED',
  DIVORCED: 'DIVORCED',
  WIDOWED: 'WIDOWED',
  OTHER: 'OTHER',
} as const
