/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateInvitation201Data } from './createInvitation201Data'

export type CreateInvitation201 = {
  success: boolean
  data: CreateInvitation201Data
}
