/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateAssistance201Data } from './createAssistance201Data'

export type CreateAssistance201 = {
  success: boolean
  data: CreateAssistance201Data
}
