/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type CreateAssistanceBody = {
  /** @minLength 1 */
  policyId: string
  /** @minLength 1 */
  clientId: string
  claimId?: '' | string
  /** @minLength 1 */
  type: string
  description?: '' | string
  address?: '' | string
  latitude?: number
  longitude?: number
  providerName?: '' | string
  providerPhone?: '' | string
  scheduledAt?: '' | string
}
