/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type CreateClientBodyType =
  (typeof CreateClientBodyType)[keyof typeof CreateClientBodyType]

export const CreateClientBodyType = {
  LEAD: 'LEAD',
  CLIENT: 'CLIENT',
  FORMER_CLIENT: 'FORMER_CLIENT',
} as const
