/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateClient201DataAddress } from './createClient201DataAddress'
import type { CreateClient201DataMaritalStatus } from './createClient201DataMaritalStatus'
import type { CreateClient201DataPersonType } from './createClient201DataPersonType'

export type CreateClient201Data = {
  id: string
  organizationId: string
  legalName: string
  document: string
  personType: CreateClient201DataPersonType
  /** @nullable */
  profession: string | null
  /** @nullable */
  maritalStatus: CreateClient201DataMaritalStatus
  /** @nullable */
  address: CreateClient201DataAddress
  /** @nullable */
  fiscalBirthDate: string | null
  createdAt: string
  updatedAt: string
  /** @nullable */
  deletedAt: string | null
  activePolicyCount: number
  totalPolicyCount: number
  contactCount: number
}
