/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type CreateProposal201DataSourcePolicySnapshot = {
  policyNumber: string
  clientName: string
  startDate: string
  endDate: string
  status: 'ACTIVE' | 'CANCELLED' | 'EXPIRED'
  /** @nullable */
  insurerId: string | null
  /** @nullable */
  insurerName: string | null
} | null
