/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateClient201Data } from './createClient201Data'

export type CreateClient201 = {
  success: boolean
  data: CreateClient201Data
}
