/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateInternalClaim400Error } from './createInternalClaim400Error'

export type CreateInternalClaim400 = {
  success: boolean
  error: CreateInternalClaim400Error
}
