/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type CreateInsurer201Data = {
  id: string
  organizationId: string
  name: string
  /** @nullable */
  code: string | null
  active: boolean
  createdAt: string
  updatedAt: string
}
