/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type CreateClaim201DataPriority =
  (typeof CreateClaim201DataPriority)[keyof typeof CreateClaim201DataPriority]

export const CreateClaim201DataPriority = {
  NORMAL: 'NORMAL',
  HIGH: 'HIGH',
  URGENT: 'URGENT',
} as const
