/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateProposal201Data } from './createProposal201Data'

export type CreateProposal201 = {
  success: boolean
  data: CreateProposal201Data
}
