/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateEndorsementBodyChanges } from './createEndorsementBodyChanges'
import type { CreateEndorsementBodyPreviousVersionSnapshot } from './createEndorsementBodyPreviousVersionSnapshot'

export type CreateEndorsementBody = {
  /** @minLength 1 */
  policyId: string
  /** @minLength 1 */
  type: string
  /** @minLength 1 */
  description: string
  effectiveDate: string
  previousVersionSnapshot: CreateEndorsementBodyPreviousVersionSnapshot
  changes: CreateEndorsementBodyChanges
}
