/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type CreateLeadBody = {
  /** @minLength 1 */
  clientName: string
  /** @minLength 1 */
  clientPhone: string
  insuranceType: string
  notes?: string
  source?: string
}
