/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateContact201DataSocialMedia } from './createContact201DataSocialMedia'
import type { CreateContact201DataSource } from './createContact201DataSource'
import type { CreateContact201DataStage } from './createContact201DataStage'

export type CreateContact201Data = {
  id: string
  organizationId: string
  name: string
  /** @nullable */
  phone: string | null
  /** @nullable */
  email: string | null
  source: CreateContact201DataSource
  salespersonId: string
  /** @nullable */
  clientId: string | null
  tags: string[]
  /** @nullable */
  socialMedia: CreateContact201DataSocialMedia
  /** @nullable */
  notes: string | null
  consentLgpd: boolean
  /** @nullable */
  birthDate: string | null
  createdAt: string
  updatedAt: string
  /** @nullable */
  deletedAt: string | null
  stage: CreateContact201DataStage
  activePolicyCount: number
}
