/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type CreateClaimBodyPriority =
  (typeof CreateClaimBodyPriority)[keyof typeof CreateClaimBodyPriority]

export const CreateClaimBodyPriority = {
  NORMAL: 'NORMAL',
  HIGH: 'HIGH',
  URGENT: 'URGENT',
} as const
