/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ExportClientsHasActivePolicy } from './exportClientsHasActivePolicy'
import type { ExportClientsSortBy } from './exportClientsSortBy'
import type { ExportClientsSortOrder } from './exportClientsSortOrder'

export type ExportClientsParams = {
  hasActivePolicy?: (typeof ExportClientsHasActivePolicy)[keyof typeof ExportClientsHasActivePolicy]
  personTypeIn?: string
  search?: string
  cursor?: string
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number
  sortBy?: ExportClientsSortBy
  sortOrder?: ExportClientsSortOrder
}
