/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type ExportPoliciesStatus =
  (typeof ExportPoliciesStatus)[keyof typeof ExportPoliciesStatus]

export const ExportPoliciesStatus = {
  ACTIVE: 'ACTIVE',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED',
} as const
