/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ExportDashboardPdfPreset } from './exportDashboardPdfPreset'

export type ExportDashboardPdfParams = {
  preset?: ExportDashboardPdfPreset
}
