/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type ExportClientsType =
  (typeof ExportClientsType)[keyof typeof ExportClientsType]

export const ExportClientsType = {
  LEAD: 'LEAD',
  CLIENT: 'CLIENT',
  FORMER_CLIENT: 'FORMER_CLIENT',
} as const
