/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ExportProposalsBoardType } from './exportProposalsBoardType'
import type { ExportProposalsSortBy } from './exportProposalsSortBy'
import type { ExportProposalsSortOrder } from './exportProposalsSortOrder'
import type { ExportProposalsStage } from './exportProposalsStage'

export type ExportProposalsParams = {
  cursor?: string
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number
  stage?: ExportProposalsStage
  stages?: string &
    (
      | 'CAPTURE'
      | 'QUOTE'
      | 'PROTOCOL'
      | 'INSPECTION'
      | 'PAYMENT'
      | 'POLICY_ISSUED'
      | 'LOST'
    )[]
  contactId?: string
  clientId?: string
  salespersonId?: string
  insurerId?: string
  sourcePolicyId?: string
  createdFrom?: string
  createdTo?: string
  updatedAtFrom?: string
  updatedAtTo?: string
  boardType?: ExportProposalsBoardType
  search?: string
  sortBy?: ExportProposalsSortBy
  sortOrder?: ExportProposalsSortOrder
}
