/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ExportPoliciesBoardType } from './exportPoliciesBoardType'
import type { ExportPoliciesBranch } from './exportPoliciesBranch'
import type { ExportPoliciesStatus } from './exportPoliciesStatus'

export type ExportPoliciesParams = {
  cursor?: string
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number
  status?: ExportPoliciesStatus
  statusIn?: string
  clientId?: string
  proposalId?: string
  branch?: ExportPoliciesBranch
  branchIn?: string
  boardType?: ExportPoliciesBoardType
  boardTypeIn?: string
  createdFrom?: string
  createdTo?: string
  endDateFrom?: string
  endDateTo?: string
  search?: string
}
