/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type ExportProposalsBoardType =
  (typeof ExportProposalsBoardType)[keyof typeof ExportProposalsBoardType]

export const ExportProposalsBoardType = {
  NEW_INSURANCE: 'NEW_INSURANCE',
  RENEWAL: 'RENEWAL',
  ENDORSEMENT: 'ENDORSEMENT',
} as const
