/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type ExportDashboardPdfPreset =
  (typeof ExportDashboardPdfPreset)[keyof typeof ExportDashboardPdfPreset]

export const ExportDashboardPdfPreset = {
  '7d': '7d',
  '30d': '30d',
  '90d': '90d',
  '6m': '6m',
} as const
