/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ExportDashboardPdf404Error } from './exportDashboardPdf404Error'

export type ExportDashboardPdf404 = {
  success: boolean
  error: ExportDashboardPdf404Error
}
