/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ExportCommissionsSortBy } from './exportCommissionsSortBy'
import type { ExportCommissionsSortOrder } from './exportCommissionsSortOrder'
import type { ExportCommissionsStatus } from './exportCommissionsStatus'

export type ExportCommissionsParams = {
  cursor?: string
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number
  dateFrom?: string
  dateTo?: string
  status?: ExportCommissionsStatus
  statusIn?: string
  salespersonId?: string
  policyId?: string
  search?: string
  sortBy?: ExportCommissionsSortBy
  sortOrder?: ExportCommissionsSortOrder
}
