/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ExportPoliciesBranch } from './exportPoliciesBranch'
import type { ExportPoliciesStatus } from './exportPoliciesStatus'

export type ExportPoliciesParams = {
  cursor?: string
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number
  status?: ExportPoliciesStatus
  clientId?: string
  proposalId?: string
  branch?: ExportPoliciesBranch
  search?: string
}
