/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ExportDashboardPdf200Data } from './exportDashboardPdf200Data'

export type ExportDashboardPdf200 = {
  success: boolean
  data: ExportDashboardPdf200Data
}
