/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type ExportProposalsStage =
  (typeof ExportProposalsStage)[keyof typeof ExportProposalsStage]

export const ExportProposalsStage = {
  CAPTURE: 'CAPTURE',
  QUOTE: 'QUOTE',
  PROTOCOL: 'PROTOCOL',
  INSPECTION: 'INSPECTION',
  PAYMENT: 'PAYMENT',
  POLICY_ISSUED: 'POLICY_ISSUED',
  LOST: 'LOST',
} as const
