/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { GeneratePolicyPdf404Error } from './generatePolicyPdf404Error'

export type GeneratePolicyPdf404 = {
  success: boolean
  error: GeneratePolicyPdf404Error
}
