/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type GetAssistance200DataStatus =
  (typeof GetAssistance200DataStatus)[keyof typeof GetAssistance200DataStatus]

export const GetAssistance200DataStatus = {
  REQUESTED: 'REQUESTED',
  AWAITING_DOCUMENT: 'AWAITING_DOCUMENT',
  PENDING_INSPECTION: 'PENDING_INSPECTION',
  DISPATCHED: 'DISPATCHED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
} as const
