/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { GetBillingAiUsage200Data } from './getBillingAiUsage200Data'

export type GetBillingAiUsage200 = {
  success: boolean
  data: GetBillingAiUsage200Data
}
