/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { GetBillingCurrent200Data } from './getBillingCurrent200Data'

export type GetBillingCurrent200 = {
  success: boolean
  data: GetBillingCurrent200Data
}
