/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type GetBillingCurrent200DataEntitlements = {
  /** @nullable */
  maxUsers: number | null
  /** @nullable */
  maxProposalsPerMonth: number | null
  /** @nullable */
  maxChannels: number | null
  /** @nullable */
  maxConversationsPerOrg: number | null
  /** @nullable */
  maxImportRows: number | null
  /** @nullable */
  maxLogoSizeBytes: number | null
  aiEnabled: boolean
  aiMessagesIncluded: number
  aiOverageCentsPerMessage: number
  customBranding: boolean
  apiAccess: boolean
  advancedReports: boolean
  prioritySupport: boolean
  isActive: boolean
  isTrialing: boolean
  /** @nullable */
  trialEndsAt: string | null
  billingManagedExternally: boolean
}
