/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { GetBillingAiUsage200DataSeriesItem } from './getBillingAiUsage200DataSeriesItem'
import type { GetBillingAiUsage200DataTotals } from './getBillingAiUsage200DataTotals'

export type GetBillingAiUsage200Data = {
  series: GetBillingAiUsage200DataSeriesItem[]
  totals: GetBillingAiUsage200DataTotals
}
