/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type GetBillingAiUsage200DataSeriesItem = {
  date: string
  inputTokens: number
  outputTokens: number
  totalCostMicrocents: number
  messageCount: number
}
