/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type GetClaim200DataStatus =
  (typeof GetClaim200DataStatus)[keyof typeof GetClaim200DataStatus]

export const GetClaim200DataStatus = {
  REGISTERED: 'REGISTERED',
  IN_ANALYSIS: 'IN_ANALYSIS',
  AWAITING_DOCUMENT: 'AWAITING_DOCUMENT',
  PENDING_INSPECTION: 'PENDING_INSPECTION',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  PAID: 'PAID',
  COMPLETED: 'COMPLETED',
} as const
