/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type GetCep200Data = {
  /**
   * @minLength 8
   * @maxLength 8
   */
  zipCode: string
  street: string
  neighborhood: string
  city: string
  /**
   * @minLength 2
   * @maxLength 2
   */
  state: string
  /** @nullable */
  complement: string | null
}
