/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type GetContact200DataStage =
  (typeof GetContact200DataStage)[keyof typeof GetContact200DataStage]

export const GetContact200DataStage = {
  LEAD: 'LEAD',
  CLIENT_NEW: 'CLIENT_NEW',
  CLIENT_ACTIVE: 'CLIENT_ACTIVE',
  CLIENT_INACTIVE: 'CLIENT_INACTIVE',
} as const
