/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { GetClient200DataAddress } from './getClient200DataAddress'
import type { GetClient200DataMaritalStatus } from './getClient200DataMaritalStatus'
import type { GetClient200DataPersonType } from './getClient200DataPersonType'

export type GetClient200Data = {
  id: string
  organizationId: string
  legalName: string
  document: string
  personType: GetClient200DataPersonType
  /** @nullable */
  profession: string | null
  /** @nullable */
  maritalStatus: GetClient200DataMaritalStatus
  /** @nullable */
  address: GetClient200DataAddress
  /** @nullable */
  fiscalBirthDate: string | null
  createdAt: string
  updatedAt: string
  /** @nullable */
  deletedAt: string | null
  activePolicyCount: number
  totalPolicyCount: number
  contactCount: number
}
