/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { GetContact404Error } from './getContact404Error'

export type GetContact404 = {
  success: boolean
  error: GetContact404Error
}
