/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type GetClient200DataType =
  (typeof GetClient200DataType)[keyof typeof GetClient200DataType]

export const GetClient200DataType = {
  LEAD: 'LEAD',
  CLIENT: 'CLIENT',
  FORMER_CLIENT: 'FORMER_CLIENT',
} as const
