/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { GetContact200Data } from './getContact200Data'

export type GetContact200 = {
  success: boolean
  data: GetContact200Data
}
