/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { GetCep200Data } from './getCep200Data'

export type GetCep200 = {
  success: boolean
  data: GetCep200Data
}
