/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { GetCep404Error } from './getCep404Error'

export type GetCep404 = {
  success: boolean
  error: GetCep404Error
}
