/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type GetClaim200DataPriority =
  (typeof GetClaim200DataPriority)[keyof typeof GetClaim200DataPriority]

export const GetClaim200DataPriority = {
  NORMAL: 'NORMAL',
  HIGH: 'HIGH',
  URGENT: 'URGENT',
} as const
