/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { GetCep400Error } from './getCep400Error'

export type GetCep400 = {
  success: boolean
  error: GetCep400Error
}
