/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type GetClient200DataPersonType =
  (typeof GetClient200DataPersonType)[keyof typeof GetClient200DataPersonType]

export const GetClient200DataPersonType = {
  INDIVIDUAL: 'INDIVIDUAL',
  COMPANY: 'COMPANY',
} as const
