/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { GetClaim200DataPriority } from './getClaim200DataPriority'
import type { GetClaim200DataStatus } from './getClaim200DataStatus'

export type GetClaim200Data = {
  id: string
  organizationId: string
  claimNumber: number
  policyId: string
  clientId: string
  /** @nullable */
  insurerId: string | null
  /** @nullable */
  assignedToId: string | null
  status: GetClaim200DataStatus
  priority: GetClaim200DataPriority
  description: string
  /** @nullable */
  estimatedValueInCents: number | null
  /** @nullable */
  incidentDate: string | null
  /** @nullable */
  incidentLocation: string | null
  reportedAt: string
  /** @nullable */
  resolvedAt: string | null
  /** @nullable */
  closedAt: string | null
  createdAt: string
  updatedAt: string
  policyNumber?: string
  clientName?: string
  insurerName?: string
  assignedToName?: string
}
