/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { GetDashboardStats200Data } from './getDashboardStats200Data'

export type GetDashboardStats200 = {
  success: boolean
  data: GetDashboardStats200Data
}
