/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { GetDashboardStats200DataAverageTicket } from './getDashboardStats200DataAverageTicket'
import type { GetDashboardStats200DataClaimsByPriorityItem } from './getDashboardStats200DataClaimsByPriorityItem'
import type { GetDashboardStats200DataCommissionsThisMonthItem } from './getDashboardStats200DataCommissionsThisMonthItem'
import type { GetDashboardStats200DataComparison } from './getDashboardStats200DataComparison'
import type { GetDashboardStats200DataConversionRate } from './getDashboardStats200DataConversionRate'
import type { GetDashboardStats200DataMonthlyTrendsItem } from './getDashboardStats200DataMonthlyTrendsItem'
import type { GetDashboardStats200DataNewInsurance } from './getDashboardStats200DataNewInsurance'
import type { GetDashboardStats200DataProposalsByStageItem } from './getDashboardStats200DataProposalsByStageItem'
import type { GetDashboardStats200DataProposalsPending } from './getDashboardStats200DataProposalsPending'
import type { GetDashboardStats200DataRankingItem } from './getDashboardStats200DataRankingItem'
import type { GetDashboardStats200DataTotalPremium } from './getDashboardStats200DataTotalPremium'
import type { GetDashboardStats200DataWarnings } from './getDashboardStats200DataWarnings'

export type GetDashboardStats200Data = {
  proposalsByStage: GetDashboardStats200DataProposalsByStageItem[]
  activePolicies: number
  expiringPolicies: number
  renewalsNext7Days: number
  claimsByPriority: GetDashboardStats200DataClaimsByPriorityItem[]
  commissionsThisMonth: GetDashboardStats200DataCommissionsThisMonthItem[]
  conversionRate: GetDashboardStats200DataConversionRate
  monthlyTrends: GetDashboardStats200DataMonthlyTrendsItem[]
  comparison: GetDashboardStats200DataComparison
  totalPremium: GetDashboardStats200DataTotalPremium
  averageTicket: GetDashboardStats200DataAverageTicket
  commissionsReceivable: number
  ranking: GetDashboardStats200DataRankingItem[]
  newInsurance: GetDashboardStats200DataNewInsurance
  renewal7dPremiumCents: number
  warnings: GetDashboardStats200DataWarnings
  proposalsPending: GetDashboardStats200DataProposalsPending
}
