/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { GetGoalsProgress200Data } from './getGoalsProgress200Data'

export type GetGoalsProgress200 = {
  success: boolean
  data: GetGoalsProgress200Data
}
