/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type GetGoalsProgress200DataEntriesItemBoardType =
  (typeof GetGoalsProgress200DataEntriesItemBoardType)[keyof typeof GetGoalsProgress200DataEntriesItemBoardType]

export const GetGoalsProgress200DataEntriesItemBoardType = {
  NEW_INSURANCE: 'NEW_INSURANCE',
  RENEWAL: 'RENEWAL',
} as const
