/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { GetGoalsProgress200DataEntriesItemBoardType } from './getGoalsProgress200DataEntriesItemBoardType'

export type GetGoalsProgress200DataEntriesItem = {
  /**
   * @minimum 1
   * @maximum 12
   */
  month: number
  boardType: GetGoalsProgress200DataEntriesItemBoardType
  /** @minimum 0 */
  targetPremiumCents: number
  /** @minimum 0 */
  realizedPremiumCents: number
}
