/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { GetInsurer200Data } from './getInsurer200Data'

export type GetInsurer200 = {
  success: boolean
  data: GetInsurer200Data
}
