/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { GetOrganization200Data } from './getOrganization200Data'

export type GetOrganization200 = {
  success: boolean
  data: GetOrganization200Data
}
