/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { GetProposalChecklist404Error } from './getProposalChecklist404Error'

export type GetProposalChecklist404 = {
  success: boolean
  error: GetProposalChecklist404Error
}
