/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { GetProposal200DataBoardType } from './getProposal200DataBoardType'
import type { GetProposal200DataBranch } from './getProposal200DataBranch'
import type { GetProposal200DataDetails } from './getProposal200DataDetails'
import type { GetProposal200DataStage } from './getProposal200DataStage'

export type GetProposal200Data = {
  id: string
  organizationId: string
  clientId: string
  salespersonId: string
  stage: GetProposal200DataStage
  boardType: GetProposal200DataBoardType
  branch: GetProposal200DataBranch
  premiumValueInCents: number
  commissionPercentageInCents: number
  details: GetProposal200DataDetails
  /** @nullable */
  lostReason: string | null
  /** @nullable */
  renewalPolicyId: string | null
  /** @nullable */
  insurerId: string | null
  /** @nullable */
  deletedAt: string | null
  createdAt: string
  updatedAt: string
  clientName?: string
  clientDocument?: string
  salespersonName?: string
  insurerName?: string
}
