/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type GetProposalChecklist200DataSummary = {
  total: number
  completed: number
  required: number
  requiredCompleted: number
  canAdvance: boolean
}
