/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { GetPublicInvitation200DataCurrentSession } from './getPublicInvitation200DataCurrentSession'

export type GetPublicInvitation200Data = {
  id: string
  email: string
  role: string
  status: string
  expiresAt: string
  organizationName: string
  inviterName: string
  hasAccount: boolean
  /** @nullable */
  currentSession: GetPublicInvitation200DataCurrentSession
}
