/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { GetPolicy200DataBranch } from './getPolicy200DataBranch'
import type { GetPolicy200DataClientAddress } from './getPolicy200DataClientAddress'
import type { GetPolicy200DataCoverageDetails } from './getPolicy200DataCoverageDetails'
import type { GetPolicy200DataStatus } from './getPolicy200DataStatus'

export type GetPolicy200Data = {
  id: string
  organizationId: string
  proposalId: string
  clientId: string
  salespersonId: string
  policyNumber: string
  status: GetPolicy200DataStatus
  branch: GetPolicy200DataBranch
  premiumValueInCents: number
  /** @nullable */
  coverageDetails: GetPolicy200DataCoverageDetails
  startDate: string
  endDate: string
  /** @nullable */
  cancelledAt: string | null
  /** @nullable */
  cancelReason: string | null
  createdAt: string
  updatedAt: string
  clientName?: string
  clientDocument?: string
  /** @nullable */
  clientEmail?: string | null
  /** @nullable */
  clientPhone?: string | null
  /** @nullable */
  clientAddress?: GetPolicy200DataClientAddress
  salespersonName?: string
  insurerName?: string
  proposalIdentifier?: string
}
