/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type GetPolicy200DataClientAddress = {
  /** @pattern ^\d{8}$ */
  cep: string
  /**
   * @minLength 1
   * @maxLength 200
   */
  street: string
  /**
   * @maxLength 20
   * @nullable
   */
  number: string | null
  /**
   * @maxLength 200
   * @nullable
   */
  complement: string | null
  /**
   * @minLength 1
   * @maxLength 100
   */
  neighborhood: string
  /**
   * @minLength 1
   * @maxLength 100
   */
  city: string
  /**
   * @minLength 2
   * @maxLength 2
   */
  state: string
} | null
