/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type GetPolicy200DataStatus =
  (typeof GetPolicy200DataStatus)[keyof typeof GetPolicy200DataStatus]

export const GetPolicy200DataStatus = {
  ACTIVE: 'ACTIVE',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED',
} as const
