/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { GetPolicy200Data } from './getPolicy200Data'

export type GetPolicy200 = {
  success: boolean
  data: GetPolicy200Data
}
