/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { GetPublicInvitation404Error } from './getPublicInvitation404Error'

export type GetPublicInvitation404 = {
  success: boolean
  error: GetPublicInvitation404Error
}
