/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type GetProposalChecklist200DataItemsItem = {
  id: string
  proposalId: string
  itemKey: string
  label: string
  isRequired: boolean
  isCompleted: boolean
  /** @nullable */
  completedAt: string | null
  /** @nullable */
  completedBy: string | null
  createdAt: string
}
