/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type GetTermsStatus200Data = {
  needsReAccept: boolean
  currentTermsVersion: string
  currentPrivacyVersion: string
  /** @nullable */
  userTermsVersion: string | null
  /** @nullable */
  userPrivacyVersion: string | null
}
