/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { GetTermsStatus200Data } from './getTermsStatus200Data'

export type GetTermsStatus200 = {
  success: boolean
  data: GetTermsStatus200Data
}
