/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { GetUnreadCount200Data } from './getUnreadCount200Data'

export type GetUnreadCount200 = {
  success: boolean
  data: GetUnreadCount200Data
}
