/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type GlobalSearchParams = {
  /**
   * @minLength 2
   * @maxLength 100
   */
  q: string
  /**
   * @minimum 1
   * @maximum 20
   */
  limit?: number
}
