/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { GlobalSearch200DataClaimsItem } from './globalSearch200DataClaimsItem'
import type { GlobalSearch200DataClientsItem } from './globalSearch200DataClientsItem'
import type { GlobalSearch200DataPoliciesItem } from './globalSearch200DataPoliciesItem'
import type { GlobalSearch200DataProposalsItem } from './globalSearch200DataProposalsItem'

export type GlobalSearch200Data = {
  clients: GlobalSearch200DataClientsItem[]
  proposals: GlobalSearch200DataProposalsItem[]
  policies: GlobalSearch200DataPoliciesItem[]
  claims: GlobalSearch200DataClaimsItem[]
}
