/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { GlobalSearch200Data } from './globalSearch200Data'
import type { GlobalSearch200Meta } from './globalSearch200Meta'

export type GlobalSearch200 = {
  success: boolean
  data: GlobalSearch200Data
  meta: GlobalSearch200Meta
}
