/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ImportStatusClients200DataProgress } from './importStatusClients200DataProgress'
import type { ImportStatusClients200DataStatus } from './importStatusClients200DataStatus'

export type ImportStatusClients200Data = {
  status: ImportStatusClients200DataStatus
  /** @nullable */
  progress: ImportStatusClients200DataProgress
}
