/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ImportUploadClients400Error } from './importUploadClients400Error'

export type ImportUploadClients400 = {
  success: boolean
  error: ImportUploadClients400Error
}
