/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ImportStatusPolicies200DataProgress } from './importStatusPolicies200DataProgress'
import type { ImportStatusPolicies200DataStatus } from './importStatusPolicies200DataStatus'

export type ImportStatusPolicies200Data = {
  status: ImportStatusPolicies200DataStatus
  /** @nullable */
  progress: ImportStatusPolicies200DataProgress
}
