/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ImportStatusPolicies404Error } from './importStatusPolicies404Error'

export type ImportStatusPolicies404 = {
  success: boolean
  error: ImportStatusPolicies404Error
}
