/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ImportStatusPolicies200Data } from './importStatusPolicies200Data'

export type ImportStatusPolicies200 = {
  success: boolean
  data: ImportStatusPolicies200Data
}
