/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ImportUploadClients422Error } from './importUploadClients422Error'

export type ImportUploadClients422 = {
  success: boolean
  error: ImportUploadClients422Error
}
