/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ImportStatusClients200Data } from './importStatusClients200Data'

export type ImportStatusClients200 = {
  success: boolean
  data: ImportStatusClients200Data
}
