/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ImportUploadClients413Error } from './importUploadClients413Error'

export type ImportUploadClients413 = {
  success: boolean
  error: ImportUploadClients413Error
}
