/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ImportConfirmPolicies404Error } from './importConfirmPolicies404Error'

export type ImportConfirmPolicies404 = {
  success: boolean
  error: ImportConfirmPolicies404Error
}
