/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ImportUploadPolicies413Error } from './importUploadPolicies413Error'

export type ImportUploadPolicies413 = {
  success: boolean
  error: ImportUploadPolicies413Error
}
