/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ImportConfirmClients404Error } from './importConfirmClients404Error'

export type ImportConfirmClients404 = {
  success: boolean
  error: ImportConfirmClients404Error
}
