/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ImportConfirmPolicies200Data } from './importConfirmPolicies200Data'

export type ImportConfirmPolicies200 = {
  success: boolean
  data: ImportConfirmPolicies200Data
}
