/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ImportUploadClients200Data } from './importUploadClients200Data'

export type ImportUploadClients200 = {
  success: boolean
  data: ImportUploadClients200Data
}
