/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { InternalPromoteContact400Error } from './internalPromoteContact400Error'

export type InternalPromoteContact400 = {
  success: boolean
  error: InternalPromoteContact400Error
}
