/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type InternalPromoteContactBodyPersonType =
  (typeof InternalPromoteContactBodyPersonType)[keyof typeof InternalPromoteContactBodyPersonType]

export const InternalPromoteContactBodyPersonType = {
  INDIVIDUAL: 'INDIVIDUAL',
  COMPANY: 'COMPANY',
} as const
