/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type IssuePolicy201DataStatus =
  (typeof IssuePolicy201DataStatus)[keyof typeof IssuePolicy201DataStatus]

export const IssuePolicy201DataStatus = {
  ACTIVE: 'ACTIVE',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED',
} as const
