/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { IssuePolicy201Data } from './issuePolicy201Data'

export type IssuePolicy201 = {
  success: boolean
  data: IssuePolicy201Data
}
