/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { IssuePolicyBodyCoverageDetails } from './issuePolicyBodyCoverageDetails'

export type IssuePolicyBody = {
  /** @minLength 1 */
  proposalId: string
  /** @minLength 1 */
  policyNumber: string
  startDate: string
  endDate: string
  coverageDetails?: IssuePolicyBodyCoverageDetails
}
