/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type IssuePolicy201DataCoverageDetails = {
  [key: string]: unknown
} | null
