/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ListClientsSortBy } from './listClientsSortBy'
import type { ListClientsSortOrder } from './listClientsSortOrder'

export type ListClientsParams = {
  hasActivePolicy?: boolean
  search?: string
  cursor?: string
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number
  sortBy?: ListClientsSortBy
  sortOrder?: ListClientsSortOrder
}
