/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ListContacts200DataItem } from './listContacts200DataItem'
import type { ListContacts200Meta } from './listContacts200Meta'

export type ListContacts200 = {
  success: boolean
  data: ListContacts200DataItem[]
  meta: ListContacts200Meta
}
