/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type ListInvitationsParams = {
  cursor?: string
  /**
   * @minimum 1
   * @maximum 50
   */
  limit?: number
}
