/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type ListBillingInvoices200DataItemStatus =
  (typeof ListBillingInvoices200DataItemStatus)[keyof typeof ListBillingInvoices200DataItemStatus]

export const ListBillingInvoices200DataItemStatus = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  OVERDUE: 'OVERDUE',
  CANCELED: 'CANCELED',
  REFUNDED: 'REFUNDED',
} as const
