/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ListInternalProposals200Data } from './listInternalProposals200Data'

export type ListInternalProposals200 = {
  success: boolean
  data: ListInternalProposals200Data
}
