/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type ListClaimsSortOrder =
  (typeof ListClaimsSortOrder)[keyof typeof ListClaimsSortOrder]

export const ListClaimsSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const
