/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type ListAssistances200DataItemStatus =
  (typeof ListAssistances200DataItemStatus)[keyof typeof ListAssistances200DataItemStatus]

export const ListAssistances200DataItemStatus = {
  REQUESTED: 'REQUESTED',
  AWAITING_DOCUMENT: 'AWAITING_DOCUMENT',
  PENDING_INSPECTION: 'PENDING_INSPECTION',
  DISPATCHED: 'DISPATCHED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
} as const
