/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type ListPolicies200DataItemStatus =
  (typeof ListPolicies200DataItemStatus)[keyof typeof ListPolicies200DataItemStatus]

export const ListPolicies200DataItemStatus = {
  ACTIVE: 'ACTIVE',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED',
} as const
