/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ListInternalPoliciesBranch } from './listInternalPoliciesBranch'

export type ListInternalPoliciesParams = {
  clientId?: string
  phone?: string
  branch?: ListInternalPoliciesBranch
}
