/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ListContacts400Error } from './listContacts400Error'

export type ListContacts400 = {
  success: boolean
  error: ListContacts400Error
}
