/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type ListAssistancesStatusGroup =
  (typeof ListAssistancesStatusGroup)[keyof typeof ListAssistancesStatusGroup]

export const ListAssistancesStatusGroup = {
  open: 'open',
  closed: 'closed',
} as const
