/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type ListTenants200DataItem = {
  id: string
  name: string
  slug: string
  /** @nullable */
  logo: string | null
  role: string
}
