/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type ListClaims200Meta = {
  total?: number
  /** @nullable */
  nextCursor?: string | null
}
