/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ListClaimOccurrences200DataItem } from './listClaimOccurrences200DataItem'

export type ListClaimOccurrences200 = {
  success: boolean
  data: ListClaimOccurrences200DataItem[]
}
