/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ListMembers200DataItem } from './listMembers200DataItem'
import type { ListMembers200Meta } from './listMembers200Meta'

export type ListMembers200 = {
  success: boolean
  data: ListMembers200DataItem[]
  meta: ListMembers200Meta
}
