/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ListPolicies200DataItem } from './listPolicies200DataItem'
import type { ListPolicies200Meta } from './listPolicies200Meta'

export type ListPolicies200 = {
  success: boolean
  data: ListPolicies200DataItem[]
  meta: ListPolicies200Meta
}
