/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ListInternalProposalsStatus } from './listInternalProposalsStatus'

export type ListInternalProposalsParams = {
  clientId?: string
  phone?: string
  status?: ListInternalProposalsStatus
}
