/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type ListNotifications200DataItem = {
  id: string
  organizationId: string
  userId: string
  type: string
  title: string
  body: string
  /** @nullable */
  entityType: string | null
  /** @nullable */
  entityId: string | null
  read: boolean
  /** @nullable */
  readAt: string | null
  emailSent: boolean
  createdAt: string
}
