/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type ListInvitations200DataItem = {
  id: string
  organizationId: string
  email: string
  role: string
  status: string
  expiresAt: string
  invitedBy: string
  createdAt: string
  updatedAt: string
}
