/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type ListPoliciesBoardType =
  (typeof ListPoliciesBoardType)[keyof typeof ListPoliciesBoardType]

export const ListPoliciesBoardType = {
  NEW_INSURANCE: 'NEW_INSURANCE',
  RENEWAL: 'RENEWAL',
  ENDORSEMENT: 'ENDORSEMENT',
} as const
