/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type ListClaimOccurrences200DataItemMetadata = {
  [key: string]:
    | string
    | number
    | boolean
    | 'null'
    | null
    | unknown[]
    | { [key: string]: unknown }
} | null
