/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type ListContactsSource =
  (typeof ListContactsSource)[keyof typeof ListContactsSource]

export const ListContactsSource = {
  MANUAL: 'MANUAL',
  CHAT_WHATSAPP: 'CHAT_WHATSAPP',
  CHAT_WIDGET: 'CHAT_WIDGET',
  FORM_WEB: 'FORM_WEB',
  IMPORT: 'IMPORT',
  REFERRAL: 'REFERRAL',
} as const
