/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ListPolicies200DataItemBranch } from './listPolicies200DataItemBranch'
import type { ListPolicies200DataItemClientAddress } from './listPolicies200DataItemClientAddress'
import type { ListPolicies200DataItemCoverageDetails } from './listPolicies200DataItemCoverageDetails'
import type { ListPolicies200DataItemStatus } from './listPolicies200DataItemStatus'

export type ListPolicies200DataItem = {
  id: string
  organizationId: string
  proposalId: string
  clientId: string
  salespersonId: string
  policyNumber: string
  status: ListPolicies200DataItemStatus
  branch: ListPolicies200DataItemBranch
  premiumValueInCents: number
  /** @nullable */
  coverageDetails: ListPolicies200DataItemCoverageDetails
  startDate: string
  endDate: string
  /** @nullable */
  cancelledAt: string | null
  /** @nullable */
  cancelReason: string | null
  createdAt: string
  updatedAt: string
  clientName?: string
  clientDocument?: string
  /** @nullable */
  clientEmail?: string | null
  /** @nullable */
  clientPhone?: string | null
  /** @nullable */
  clientAddress?: ListPolicies200DataItemClientAddress
  salespersonName?: string
  insurerName?: string
  proposalIdentifier?: string
}
