/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ListPoliciesBoardType } from './listPoliciesBoardType'
import type { ListPoliciesBranch } from './listPoliciesBranch'
import type { ListPoliciesStatus } from './listPoliciesStatus'

export type ListPoliciesParams = {
  cursor?: string
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number
  status?: ListPoliciesStatus
  statusIn?: string
  clientId?: string
  proposalId?: string
  branch?: ListPoliciesBranch
  branchIn?: string
  boardType?: ListPoliciesBoardType
  boardTypeIn?: string
  createdFrom?: string
  createdTo?: string
  endDateFrom?: string
  endDateTo?: string
  search?: string
}
