/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ListClaimsPriority } from './listClaimsPriority'
import type { ListClaimsStatus } from './listClaimsStatus'

export type ListClaimsParams = {
  cursor?: string
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number
  status?: ListClaimsStatus
  priority?: ListClaimsPriority
  policyId?: string
  clientId?: string
  search?: string
}
