/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type ListInternalProposalsStatus =
  (typeof ListInternalProposalsStatus)[keyof typeof ListInternalProposalsStatus]

export const ListInternalProposalsStatus = {
  ACTIVE: 'ACTIVE',
  LOST: 'LOST',
  ALL: 'ALL',
} as const
