/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ListProposals200DataItemBoardType } from './listProposals200DataItemBoardType'
import type { ListProposals200DataItemBranch } from './listProposals200DataItemBranch'
import type { ListProposals200DataItemDetails } from './listProposals200DataItemDetails'
import type { ListProposals200DataItemSourcePolicySnapshot } from './listProposals200DataItemSourcePolicySnapshot'
import type { ListProposals200DataItemStage } from './listProposals200DataItemStage'

export type ListProposals200DataItem = {
  id: string
  organizationId: string
  clientId: string
  salespersonId: string
  stage: ListProposals200DataItemStage
  boardType: ListProposals200DataItemBoardType
  branch: ListProposals200DataItemBranch
  premiumValueInCents: number
  commissionPercentageInCents: number
  details: ListProposals200DataItemDetails
  /** @nullable */
  lostReason: string | null
  /** @nullable */
  renewalPolicyId: string | null
  /** @nullable */
  sourcePolicyId: string | null
  /** @nullable */
  endorsementType: string | null
  /** @nullable */
  endorsementReason: string | null
  /** @nullable */
  sourcePolicySnapshot: ListProposals200DataItemSourcePolicySnapshot
  /** @nullable */
  insurerId: string | null
  /** @nullable */
  deletedAt: string | null
  createdAt: string
  updatedAt: string
  clientName?: string
  clientDocument?: string
  salespersonName?: string
  insurerName?: string
}
