/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type ListDocuments200DataItemEntityType =
  (typeof ListDocuments200DataItemEntityType)[keyof typeof ListDocuments200DataItemEntityType]

export const ListDocuments200DataItemEntityType = {
  CLIENT: 'CLIENT',
  PROPOSAL: 'PROPOSAL',
  POLICY: 'POLICY',
  CLAIM: 'CLAIM',
  ASSISTANCE: 'ASSISTANCE',
} as const
