/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ListClients200DataItem } from './listClients200DataItem'
import type { ListClients200Meta } from './listClients200Meta'

export type ListClients200 = {
  success: boolean
  data: ListClients200DataItem[]
  meta: ListClients200Meta
}
