/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type ListCommissions200DataItemStatus =
  (typeof ListCommissions200DataItemStatus)[keyof typeof ListCommissions200DataItemStatus]

export const ListCommissions200DataItemStatus = {
  PENDING_COMMERCIAL: 'PENDING_COMMERCIAL',
  PENDING_ADMIN: 'PENDING_ADMIN',
  APPROVED: 'APPROVED',
  PAID: 'PAID',
  REJECTED: 'REJECTED',
  REVERSED: 'REVERSED',
} as const
