/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type ListPoliciesStatus =
  (typeof ListPoliciesStatus)[keyof typeof ListPoliciesStatus]

export const ListPoliciesStatus = {
  ACTIVE: 'ACTIVE',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED',
} as const
