/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type ListAuditLogsParams = {
  entityType?: string
  entityTypeIn?: string
  action?: string
  actionIn?: string
  userId?: string
  dateFrom?: string
  dateTo?: string
  cursor?: string
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number
}
