/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type ListInternalProposals200DataProposalsItem = {
  id: string
  branch: string
  stage: string
  /** @nullable */
  premiumValueInCents: number | null
  /** @nullable */
  coverageStartDate: string | null
  createdAt: string
  clientName: string
}
