/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ListInternalProposals400Error } from './listInternalProposals400Error'

export type ListInternalProposals400 = {
  success: boolean
  error: ListInternalProposals400Error
}
