/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type ListInsurersSortOrder =
  (typeof ListInsurersSortOrder)[keyof typeof ListInsurersSortOrder]

export const ListInsurersSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const
