/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type ListDocumentsEntityType =
  (typeof ListDocumentsEntityType)[keyof typeof ListDocumentsEntityType]

export const ListDocumentsEntityType = {
  CLIENT: 'CLIENT',
  PROPOSAL: 'PROPOSAL',
  POLICY: 'POLICY',
  CLAIM: 'CLAIM',
  ASSISTANCE: 'ASSISTANCE',
} as const
