/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ListBillingInvoices200DataItem } from './listBillingInvoices200DataItem'
import type { ListBillingInvoices200Meta } from './listBillingInvoices200Meta'

export type ListBillingInvoices200 = {
  success: boolean
  data: ListBillingInvoices200DataItem[]
  meta: ListBillingInvoices200Meta
}
