/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type ListContactsSortBy =
  (typeof ListContactsSortBy)[keyof typeof ListContactsSortBy]

export const ListContactsSortBy = {
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  name: 'name',
} as const
