/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ListBillingInvoices200DataItemPaymentMethod } from './listBillingInvoices200DataItemPaymentMethod'
import type { ListBillingInvoices200DataItemStatus } from './listBillingInvoices200DataItemStatus'

export type ListBillingInvoices200DataItem = {
  id: string
  status: ListBillingInvoices200DataItemStatus
  amountCents: number
  baseAmountCents: number
  overageAmountCents: number
  dueDate: string
  /** @nullable */
  paidAt: string | null
  periodStart: string
  periodEnd: string
  /** @nullable */
  paymentMethod: ListBillingInvoices200DataItemPaymentMethod
  /** @nullable */
  invoiceUrl: string | null
  /** @nullable */
  receiptUrl: string | null
  createdAt: string
}
