/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type ListClientsSortBy =
  (typeof ListClientsSortBy)[keyof typeof ListClientsSortBy]

export const ListClientsSortBy = {
  name: 'name',
  document: 'document',
  type: 'type',
  createdAt: 'createdAt',
} as const
