/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ListAssistancesSortBy } from './listAssistancesSortBy'
import type { ListAssistancesSortOrder } from './listAssistancesSortOrder'
import type { ListAssistancesStatus } from './listAssistancesStatus'
import type { ListAssistancesStatusGroup } from './listAssistancesStatusGroup'

export type ListAssistancesParams = {
  status?: ListAssistancesStatus
  statusIn?: string
  statusGroup?: ListAssistancesStatusGroup
  policyId?: string
  clientId?: string
  type?: string
  typeIn?: string
  search?: string
  cursor?: string
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number
  sortBy?: ListAssistancesSortBy
  sortOrder?: ListAssistancesSortOrder
}
