/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type ListClients200DataItemPersonType =
  (typeof ListClients200DataItemPersonType)[keyof typeof ListClients200DataItemPersonType]

export const ListClients200DataItemPersonType = {
  INDIVIDUAL: 'INDIVIDUAL',
  COMPANY: 'COMPANY',
} as const
