/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type ListContacts200DataItemSource =
  (typeof ListContacts200DataItemSource)[keyof typeof ListContacts200DataItemSource]

export const ListContacts200DataItemSource = {
  MANUAL: 'MANUAL',
  CHAT_WHATSAPP: 'CHAT_WHATSAPP',
  CHAT_WIDGET: 'CHAT_WIDGET',
  FORM_WEB: 'FORM_WEB',
  IMPORT: 'IMPORT',
  REFERRAL: 'REFERRAL',
} as const
