/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ListInvitations200DataItem } from './listInvitations200DataItem'
import type { ListInvitations200Meta } from './listInvitations200Meta'

export type ListInvitations200 = {
  success: boolean
  data: ListInvitations200DataItem[]
  meta: ListInvitations200Meta
}
