/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type ListContactsStage =
  (typeof ListContactsStage)[keyof typeof ListContactsStage]

export const ListContactsStage = {
  LEAD: 'LEAD',
  CLIENT_ACTIVE: 'CLIENT_ACTIVE',
  CLIENT_INACTIVE: 'CLIENT_INACTIVE',
} as const
