/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ListDocuments200DataItem } from './listDocuments200DataItem'

export type ListDocuments200 = {
  success: boolean
  data: ListDocuments200DataItem[]
}
