/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ListCommissionsStatus } from './listCommissionsStatus'

export type ListCommissionsParams = {
  cursor?: string
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number
  dateFrom?: string
  dateTo?: string
  status?: ListCommissionsStatus
  salespersonId?: string
  policyId?: string
  search?: string
}
