/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type ListProposals200DataItemBoardType =
  (typeof ListProposals200DataItemBoardType)[keyof typeof ListProposals200DataItemBoardType]

export const ListProposals200DataItemBoardType = {
  NEW_INSURANCE: 'NEW_INSURANCE',
  RENEWAL: 'RENEWAL',
  ENDORSEMENT: 'ENDORSEMENT',
} as const
