/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ListInternalProposals200DataProposalsItem } from './listInternalProposals200DataProposalsItem'

export type ListInternalProposals200Data = {
  proposals: ListInternalProposals200DataProposalsItem[]
  total: number
}
