/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ListAssistancesStatus } from './listAssistancesStatus'

export type ListAssistancesParams = {
  status?: ListAssistancesStatus
  policyId?: string
  clientId?: string
  type?: string
  cursor?: string
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number
}
