/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type ListAssistancesSortBy =
  (typeof ListAssistancesSortBy)[keyof typeof ListAssistancesSortBy]

export const ListAssistancesSortBy = {
  type: 'type',
  status: 'status',
  requestedAt: 'requestedAt',
  createdAt: 'createdAt',
} as const
