/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ListNotificationsRead } from './listNotificationsRead'

export type ListNotificationsParams = {
  read?: ListNotificationsRead
  cursor?: string
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number
}
