/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ListBillingPlans200DataItemBillingPeriod } from './listBillingPlans200DataItemBillingPeriod'
import type { ListBillingPlans200DataItemFeatures } from './listBillingPlans200DataItemFeatures'

export type ListBillingPlans200DataItem = {
  id: string
  slug: string
  name: string
  /** @nullable */
  description: string | null
  priceCents: number
  currency: string
  billingPeriod: ListBillingPlans200DataItemBillingPeriod
  sortOrder: number
  /** @nullable */
  maxUsers: number | null
  /** @nullable */
  maxProposalsPerMonth: number | null
  /** @nullable */
  maxChannels: number | null
  /** @nullable */
  maxConversationsPerOrg: number | null
  /** @nullable */
  maxImportRows: number | null
  /** @nullable */
  maxLogoSizeBytes: number | null
  aiEnabled: boolean
  aiMessagesIncluded: number
  aiOverageCentsPerMessage: number
  features: ListBillingPlans200DataItemFeatures
}
