/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ListClaims200DataItem } from './listClaims200DataItem'
import type { ListClaims200Meta } from './listClaims200Meta'

export type ListClaims200 = {
  success: boolean
  data: ListClaims200DataItem[]
  meta: ListClaims200Meta
}
