/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type ListProposalsSortBy =
  (typeof ListProposalsSortBy)[keyof typeof ListProposalsSortBy]

export const ListProposalsSortBy = {
  clientName: 'clientName',
  branch: 'branch',
  stage: 'stage',
  boardType: 'boardType',
  premiumValueInCents: 'premiumValueInCents',
  createdAt: 'createdAt',
} as const
