/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type ListClientsType =
  (typeof ListClientsType)[keyof typeof ListClientsType]

export const ListClientsType = {
  LEAD: 'LEAD',
  CLIENT: 'CLIENT',
  FORMER_CLIENT: 'FORMER_CLIENT',
} as const
