/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type ListMembers200DataItem = {
  id: string
  userId: string
  /** @nullable */
  name: string | null
  email: string
  role: string
  active: boolean
  createdAt: string
}
