/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type ListProposalsSortOrder =
  (typeof ListProposalsSortOrder)[keyof typeof ListProposalsSortOrder]

export const ListProposalsSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const
