/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ListDocuments200DataItemEntityType } from './listDocuments200DataItemEntityType'
import type { ListDocuments200DataItemType } from './listDocuments200DataItemType'

export type ListDocuments200DataItem = {
  id: string
  organizationId: string
  entityType: ListDocuments200DataItemEntityType
  entityId: string
  /** @nullable */
  clientId: string | null
  type: ListDocuments200DataItemType
  fileName: string
  mimeType: string
  sizeBytes: number
  storageKey: string
  /** @nullable */
  url: string | null
  /** @nullable */
  createdBy: string | null
  createdAt: string
}
