/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ListProposals200DataItem } from './listProposals200DataItem'
import type { ListProposals200Meta } from './listProposals200Meta'

export type ListProposals200 = {
  success: boolean
  data: ListProposals200DataItem[]
  meta: ListProposals200Meta
}
