/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ListAssistances200DataItem } from './listAssistances200DataItem'
import type { ListAssistances200Meta } from './listAssistances200Meta'

export type ListAssistances200 = {
  success: boolean
  data: ListAssistances200DataItem[]
  meta: ListAssistances200Meta
}
