/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type LookupVehicle200MetaSource =
  (typeof LookupVehicle200MetaSource)[keyof typeof LookupVehicle200MetaSource]

export const LookupVehicle200MetaSource = {
  cache: 'cache',
  apibrasil: 'apibrasil',
} as const
