/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type LookupVehicleBody = {
  plate?: string
  /**
   * @minLength 17
   * @maxLength 17
   * @pattern ^[A-HJ-NPR-Z0-9]{17}$
   */
  chassi?: string
  /** @minLength 1 */
  proposalId?: string
}
