/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { LookupVehicle200Data } from './lookupVehicle200Data'
import type { LookupVehicle200Meta } from './lookupVehicle200Meta'

export type LookupVehicle200 = {
  success: boolean
  data: LookupVehicle200Data
  meta: LookupVehicle200Meta
}
