/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type MarkNotificationRead200Data =
  | (typeof MarkNotificationRead200Data)[keyof typeof MarkNotificationRead200Data]
  | null

export const MarkNotificationRead200Data = {
  null: 'null',
} as const
