/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { MarkProposalLost200DataBoardType } from './markProposalLost200DataBoardType'
import type { MarkProposalLost200DataBranch } from './markProposalLost200DataBranch'
import type { MarkProposalLost200DataDetails } from './markProposalLost200DataDetails'
import type { MarkProposalLost200DataSourcePolicySnapshot } from './markProposalLost200DataSourcePolicySnapshot'
import type { MarkProposalLost200DataStage } from './markProposalLost200DataStage'

export type MarkProposalLost200Data = {
  id: string
  organizationId: string
  clientId: string
  salespersonId: string
  stage: MarkProposalLost200DataStage
  boardType: MarkProposalLost200DataBoardType
  branch: MarkProposalLost200DataBranch
  premiumValueInCents: number
  commissionPercentageInCents: number
  details: MarkProposalLost200DataDetails
  /** @nullable */
  lostReason: string | null
  /** @nullable */
  renewalPolicyId: string | null
  /** @nullable */
  sourcePolicyId: string | null
  /** @nullable */
  endorsementType: string | null
  /** @nullable */
  endorsementReason: string | null
  /** @nullable */
  sourcePolicySnapshot: MarkProposalLost200DataSourcePolicySnapshot
  /** @nullable */
  insurerId: string | null
  /** @nullable */
  deletedAt: string | null
  createdAt: string
  updatedAt: string
  clientName?: string
  clientDocument?: string
  salespersonName?: string
  insurerName?: string
}
