/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { MarkProposalLost404Error } from './markProposalLost404Error'

export type MarkProposalLost404 = {
  success: boolean
  error: MarkProposalLost404Error
}
