/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { MarkAllNotificationsRead200Data } from './markAllNotificationsRead200Data'

export type MarkAllNotificationsRead200 = {
  success: boolean
  data: MarkAllNotificationsRead200Data
}
