/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { MarkProposalLost400Error } from './markProposalLost400Error'

export type MarkProposalLost400 = {
  success: boolean
  error: MarkProposalLost400Error
}
