/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { MarkNotificationRead200Data } from './markNotificationRead200Data'

export type MarkNotificationRead200 = {
  success: boolean
  data: MarkNotificationRead200Data
}
