/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type MarkProposalLost200DataBoardType =
  (typeof MarkProposalLost200DataBoardType)[keyof typeof MarkProposalLost200DataBoardType]

export const MarkProposalLost200DataBoardType = {
  NEW_INSURANCE: 'NEW_INSURANCE',
  RENEWAL: 'RENEWAL',
} as const
