/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { PayCommission200DataStatus } from './payCommission200DataStatus'

export type PayCommission200Data = {
  id: string
  organizationId: string
  policyId: string
  salespersonId: string
  status: PayCommission200DataStatus
  commissionValueInCents: number
  premiumValueInCents: number
  percentageInBasisPoints: number
  /** @nullable */
  splitPercentage: number | null
  /** @nullable */
  approvedBy: string | null
  /** @nullable */
  approvedAt: string | null
  /** @nullable */
  paidAt: string | null
  /** @nullable */
  rejectedBy: string | null
  /** @nullable */
  rejectedAt: string | null
  /** @nullable */
  rejectionReason: string | null
  isReversal: boolean
  /** @nullable */
  originalCommissionId: string | null
  /** @nullable */
  deletedAt: string | null
  createdAt: string
  updatedAt: string
  salespersonName?: string
  policyNumber?: string
  clientName?: string
}
