/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { PromoteContactBodyAddress } from './promoteContactBodyAddress'
import type { PromoteContactBodyMaritalStatus } from './promoteContactBodyMaritalStatus'
import type { PromoteContactBodyPersonType } from './promoteContactBodyPersonType'

export type PromoteContactBody = {
  /** @minLength 11 */
  document: string
  /** @minLength 1 */
  legalName?: string
  personType?: PromoteContactBodyPersonType
  profession?: string
  maritalStatus?: PromoteContactBodyMaritalStatus
  address?: PromoteContactBodyAddress
  fiscalBirthDate?: string
}
