/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type ReopenProposal200Data =
  | (typeof ReopenProposal200Data)[keyof typeof ReopenProposal200Data]
  | null

export const ReopenProposal200Data = {
  null: 'null',
} as const
