/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ReopenProposal404Error } from './reopenProposal404Error'

export type ReopenProposal404 = {
  success: boolean
  error: ReopenProposal404Error
}
