/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ReopenProposal400Error } from './reopenProposal400Error'

export type ReopenProposal400 = {
  success: boolean
  error: ReopenProposal400Error
}
