/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type ReverseCommission201DataOriginalStatus =
  (typeof ReverseCommission201DataOriginalStatus)[keyof typeof ReverseCommission201DataOriginalStatus]

export const ReverseCommission201DataOriginalStatus = {
  PENDING_COMMERCIAL: 'PENDING_COMMERCIAL',
  PENDING_ADMIN: 'PENDING_ADMIN',
  APPROVED: 'APPROVED',
  PAID: 'PAID',
  REJECTED: 'REJECTED',
  REVERSED: 'REVERSED',
} as const
