/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { RevokeInvitation200Data } from './revokeInvitation200Data'

export type RevokeInvitation200 = {
  success: boolean
  data: RevokeInvitation200Data
}
