/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { SearchClients200DataClient } from './searchClients200DataClient'

export type SearchClients200Data = {
  found: boolean
  /** @nullable */
  client: SearchClients200DataClient
}
