/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { SendQuote422Error } from './sendQuote422Error'

export type SendQuote422 = {
  success: boolean
  error: SendQuote422Error
}
