/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { SendQuote202Data } from './sendQuote202Data'

export type SendQuote202 = {
  success: boolean
  data: SendQuote202Data
}
