/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateMemberRole200Data } from './updateMemberRole200Data'

export type UpdateMemberRole200 = {
  success: boolean
  data: UpdateMemberRole200Data
}
