/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type UpdateClient200DataSocialMedia = {
  instagram?: '' | string
  facebook?: '' | string
  linkedin?: '' | string
  tiktok?: '' | string
} | null
