/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type UpdateProposalObservations200DataBoardType =
  (typeof UpdateProposalObservations200DataBoardType)[keyof typeof UpdateProposalObservations200DataBoardType]

export const UpdateProposalObservations200DataBoardType = {
  NEW_INSURANCE: 'NEW_INSURANCE',
  RENEWAL: 'RENEWAL',
  ENDORSEMENT: 'ENDORSEMENT',
} as const
