/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type UpdateMemberRole200Data = {
  id: string
  userId: string
  organizationId: string
  role: string
  active: boolean
}
