/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateContactBodySocialMedia } from './updateContactBodySocialMedia'

export type UpdateContactBody = {
  /** @minLength 1 */
  name?: string
  /** @minLength 1 */
  phone?: string
  /** @nullable */
  email?: string | null
  tags?: string[]
  /** @nullable */
  notes?: string | null
  /** @nullable */
  birthDate?: string | null
  /** @nullable */
  socialMedia?: UpdateContactBodySocialMedia
  /** @minLength 1 */
  salespersonId?: string
}
