/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type UpdateClientBodyPersonType =
  (typeof UpdateClientBodyPersonType)[keyof typeof UpdateClientBodyPersonType]

export const UpdateClientBodyPersonType = {
  INDIVIDUAL: 'INDIVIDUAL',
  COMPANY: 'COMPANY',
} as const
