/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateContact200Data } from './updateContact200Data'

export type UpdateContact200 = {
  success: boolean
  data: UpdateContact200Data
}
