/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateClientInternal400Error } from './updateClientInternal400Error'

export type UpdateClientInternal400 = {
  success: boolean
  error: UpdateClientInternal400Error
}
