/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type UpdateClaimStatus200DataPriority =
  (typeof UpdateClaimStatus200DataPriority)[keyof typeof UpdateClaimStatus200DataPriority]

export const UpdateClaimStatus200DataPriority = {
  NORMAL: 'NORMAL',
  HIGH: 'HIGH',
  URGENT: 'URGENT',
} as const
