/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateProposalDates200DataBoardType } from './updateProposalDates200DataBoardType'
import type { UpdateProposalDates200DataBranch } from './updateProposalDates200DataBranch'
import type { UpdateProposalDates200DataDetails } from './updateProposalDates200DataDetails'
import type { UpdateProposalDates200DataSourcePolicySnapshot } from './updateProposalDates200DataSourcePolicySnapshot'
import type { UpdateProposalDates200DataStage } from './updateProposalDates200DataStage'

export type UpdateProposalDates200Data = {
  id: string
  organizationId: string
  contactId: string
  salespersonId: string
  stage: UpdateProposalDates200DataStage
  boardType: UpdateProposalDates200DataBoardType
  branch: UpdateProposalDates200DataBranch
  premiumValueInCents: number
  commissionPercentageInCents: number
  details: UpdateProposalDates200DataDetails
  /** @nullable */
  lostReason: string | null
  /** @nullable */
  renewalPolicyId: string | null
  /** @nullable */
  renewalPolicyNumber: string | null
  /** @nullable */
  sourcePolicyId: string | null
  /** @nullable */
  endorsementType: string | null
  /** @nullable */
  endorsementReason: string | null
  /** @nullable */
  sourcePolicySnapshot: UpdateProposalDates200DataSourcePolicySnapshot
  /** @nullable */
  insurerId: string | null
  /** @nullable */
  deletedAt: string | null
  createdAt: string
  updatedAt: string
  /** @nullable */
  coverageStartDate: string | null
  /** @nullable */
  coverageEndDate: string | null
  /** @nullable */
  sentToClientAt: string | null
  /** @nullable */
  clientResponseAt: string | null
  /** @nullable */
  quoteValidUntil: string | null
  clientName?: string
  clientDocument?: string
  clientPersonType?: string
  salespersonName?: string
  insurerName?: string
}
