/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateAssistanceStatus200Data } from './updateAssistanceStatus200Data'

export type UpdateAssistanceStatus200 = {
  success: boolean
  data: UpdateAssistanceStatus200Data
}
