/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateContact422Error } from './updateContact422Error'

export type UpdateContact422 = {
  success: boolean
  error: UpdateContact422Error
}
