/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateOrganization409Error } from './updateOrganization409Error'

export type UpdateOrganization409 = {
  success: boolean
  error: UpdateOrganization409Error
}
