/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type UpdateProposalObservations200DataBranch =
  (typeof UpdateProposalObservations200DataBranch)[keyof typeof UpdateProposalObservations200DataBranch]

export const UpdateProposalObservations200DataBranch = {
  AUTO: 'AUTO',
  RESIDENTIAL: 'RESIDENTIAL',
  CONDOMINIUM: 'CONDOMINIUM',
  BUSINESS: 'BUSINESS',
  LIFE: 'LIFE',
  OTHER: 'OTHER',
} as const
