/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type UpdateClientBodyMaritalStatus =
  (typeof UpdateClientBodyMaritalStatus)[keyof typeof UpdateClientBodyMaritalStatus]

export const UpdateClientBodyMaritalStatus = {
  SINGLE: 'SINGLE',
  MARRIED: 'MARRIED',
  DIVORCED: 'DIVORCED',
  WIDOWED: 'WIDOWED',
  OTHER: 'OTHER',
} as const
