/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateProposalObservations404Error } from './updateProposalObservations404Error'

export type UpdateProposalObservations404 = {
  success: boolean
  error: UpdateProposalObservations404Error
}
