/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateProposalDetails200DataBoardType } from './updateProposalDetails200DataBoardType'
import type { UpdateProposalDetails200DataBranch } from './updateProposalDetails200DataBranch'
import type { UpdateProposalDetails200DataDetails } from './updateProposalDetails200DataDetails'
import type { UpdateProposalDetails200DataStage } from './updateProposalDetails200DataStage'

export type UpdateProposalDetails200Data = {
  id: string
  organizationId: string
  clientId: string
  salespersonId: string
  stage: UpdateProposalDetails200DataStage
  boardType: UpdateProposalDetails200DataBoardType
  branch: UpdateProposalDetails200DataBranch
  premiumValueInCents: number
  commissionPercentageInCents: number
  details: UpdateProposalDetails200DataDetails
  /** @nullable */
  lostReason: string | null
  /** @nullable */
  renewalPolicyId: string | null
  /** @nullable */
  insurerId: string | null
  /** @nullable */
  deletedAt: string | null
  createdAt: string
  updatedAt: string
  clientName?: string
  clientDocument?: string
  salespersonName?: string
  insurerName?: string
}
