/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateClientBodyAddress } from './updateClientBodyAddress'
import type { UpdateClientBodyMaritalStatus } from './updateClientBodyMaritalStatus'
import type { UpdateClientBodyType } from './updateClientBodyType'

export type UpdateClientBody = {
  /** @minLength 2 */
  name?: string
  type?: UpdateClientBodyType
  email?: '' | string
  phone?: '' | string
  birthDate?: '' | string
  profession?: '' | string
  maritalStatus?: UpdateClientBodyMaritalStatus
  address?: UpdateClientBodyAddress
  tags?: string[]
  consentLgpd?: boolean
}
