/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type UpdateMemberRoleBodyRole =
  (typeof UpdateMemberRoleBodyRole)[keyof typeof UpdateMemberRoleBodyRole]

export const UpdateMemberRoleBodyRole = {
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  COMMERCIAL: 'COMMERCIAL',
  VIEWER: 'VIEWER',
} as const
