/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateProposalDetails400Error } from './updateProposalDetails400Error'

export type UpdateProposalDetails400 = {
  success: boolean
  error: UpdateProposalDetails400Error
}
