/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateProposalDetails404Error } from './updateProposalDetails404Error'

export type UpdateProposalDetails404 = {
  success: boolean
  error: UpdateProposalDetails404Error
}
