/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateProposalDates404Error } from './updateProposalDates404Error'

export type UpdateProposalDates404 = {
  success: boolean
  error: UpdateProposalDates404Error
}
