/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateInternalProposalDetailsBodyDetails } from './updateInternalProposalDetailsBodyDetails'

export type UpdateInternalProposalDetailsBody = {
  details: UpdateInternalProposalDetailsBodyDetails
  /** @minimum 0 */
  premiumValueInCents?: number
  /** @minimum 0 */
  commissionBasisPoints?: number
}
