/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateProposalDates400Error } from './updateProposalDates400Error'

export type UpdateProposalDates400 = {
  success: boolean
  error: UpdateProposalDates400Error
}
