/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateClient200DataAddress } from './updateClient200DataAddress'
import type { UpdateClient200DataMaritalStatus } from './updateClient200DataMaritalStatus'
import type { UpdateClient200DataType } from './updateClient200DataType'
import type { ClientSocialMedia } from './clientSocialMedia'

export type UpdateClient200Data = {
  id: string
  name: string
  type: UpdateClient200DataType
  tags: string[]
  document: string
  /** @nullable */
  email?: string | null
  /** @nullable */
  phone?: string | null
  createdAt: string
  consentLgpd: boolean
  updatedAt: string
  /** @nullable */
  birthDate?: string | null
  /** @nullable */
  profession?: string | null
  /** @nullable */
  maritalStatus?: UpdateClient200DataMaritalStatus
  /** @nullable */
  address?: UpdateClient200DataAddress
  /** @nullable */
  socialMedia?: ClientSocialMedia | null
}
