/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type UpdateClient200DataType =
  (typeof UpdateClient200DataType)[keyof typeof UpdateClient200DataType]

export const UpdateClient200DataType = {
  LEAD: 'LEAD',
  CLIENT: 'CLIENT',
  FORMER_CLIENT: 'FORMER_CLIENT',
} as const
