/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateClient200Data } from './updateClient200Data'

export type UpdateClient200 = {
  success: boolean
  data: UpdateClient200Data
}
