/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateClientBodyAddress } from './updateClientBodyAddress'
import type { UpdateClientBodyMaritalStatus } from './updateClientBodyMaritalStatus'
import type { UpdateClientBodyPersonType } from './updateClientBodyPersonType'

export type UpdateClientBody = {
  /** @minLength 1 */
  legalName?: string
  personType?: UpdateClientBodyPersonType
  /** @nullable */
  profession?: string | null
  /** @nullable */
  maritalStatus?: UpdateClientBodyMaritalStatus
  /** @nullable */
  address?: UpdateClientBodyAddress
  /** @nullable */
  fiscalBirthDate?: string | null
}
