/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type UpdateClient200DataPersonType =
  (typeof UpdateClient200DataPersonType)[keyof typeof UpdateClient200DataPersonType]

export const UpdateClient200DataPersonType = {
  INDIVIDUAL: 'INDIVIDUAL',
  COMPANY: 'COMPANY',
} as const
