/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateInsurer200Data } from './updateInsurer200Data'

export type UpdateInsurer200 = {
  success: boolean
  data: UpdateInsurer200Data
}
