/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateContact404Error } from './updateContact404Error'

export type UpdateContact404 = {
  success: boolean
  error: UpdateContact404Error
}
