/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateAssistanceStatus200DataStatus } from './updateAssistanceStatus200DataStatus'

export type UpdateAssistanceStatus200Data = {
  id: string
  organizationId: string
  policyId: string
  clientId: string
  /** @nullable */
  claimId: string | null
  type: string
  status: UpdateAssistanceStatus200DataStatus
  /** @nullable */
  description: string | null
  /** @nullable */
  address: string | null
  /** @nullable */
  latitude: number | null
  /** @nullable */
  longitude: number | null
  /** @nullable */
  providerName: string | null
  /** @nullable */
  providerPhone: string | null
  requestedAt: string
  /** @nullable */
  scheduledAt: string | null
  /** @nullable */
  completedAt: string | null
  createdAt: string
  updatedAt: string
  policyNumber?: string
  clientName?: string
}
