/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type UpdateClient200DataMaritalStatus =
  | (typeof UpdateClient200DataMaritalStatus)[keyof typeof UpdateClient200DataMaritalStatus]
  | null

export const UpdateClient200DataMaritalStatus = {
  SINGLE: 'SINGLE',
  MARRIED: 'MARRIED',
  DIVORCED: 'DIVORCED',
  WIDOWED: 'WIDOWED',
  OTHER: 'OTHER',
} as const
