/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateProposalDetails200Data } from './updateProposalDetails200Data'

export type UpdateProposalDetails200 = {
  success: boolean
  data: UpdateProposalDetails200Data
}
