/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateOrganization200Data } from './updateOrganization200Data'

export type UpdateOrganization200 = {
  success: boolean
  data: UpdateOrganization200Data
}
