/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { UploadDocument201Data } from './uploadDocument201Data'

export type UploadDocument201 = {
  success: boolean
  data: UploadDocument201Data
}
