/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { UploadDocument400Error } from './uploadDocument400Error'

export type UploadDocument400 = {
  success: boolean
  error: UploadDocument400Error
}
