/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type UploadDocumentEntityType =
  (typeof UploadDocumentEntityType)[keyof typeof UploadDocumentEntityType]

export const UploadDocumentEntityType = {
  CLIENT: 'CLIENT',
  PROPOSAL: 'PROPOSAL',
  POLICY: 'POLICY',
  CLAIM: 'CLAIM',
  ASSISTANCE: 'ASSISTANCE',
} as const
