/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type UploadDocument201DataEntityType =
  (typeof UploadDocument201DataEntityType)[keyof typeof UploadDocument201DataEntityType]

export const UploadDocument201DataEntityType = {
  CLIENT: 'CLIENT',
  PROPOSAL: 'PROPOSAL',
  POLICY: 'POLICY',
  CLAIM: 'CLAIM',
  ASSISTANCE: 'ASSISTANCE',
} as const
