/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { UploadDocument201DataEntityType } from './uploadDocument201DataEntityType'
import type { UploadDocument201DataType } from './uploadDocument201DataType'

export type UploadDocument201Data = {
  id: string
  organizationId: string
  entityType: UploadDocument201DataEntityType
  entityId: string
  /** @nullable */
  clientId: string | null
  type: UploadDocument201DataType
  fileName: string
  mimeType: string
  sizeBytes: number
  storageKey: string
  /** @nullable */
  url: string | null
  /** @nullable */
  createdBy: string | null
  createdAt: string
}
