/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { UploadOrganizationLogo200Data } from './uploadOrganizationLogo200Data'

export type UploadOrganizationLogo200 = {
  success: boolean
  data: UploadOrganizationLogo200Data
}
