/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { UploadOrganizationLogo400Error } from './uploadOrganizationLogo400Error'

export type UploadOrganizationLogo400 = {
  success: boolean
  error: UploadOrganizationLogo400Error
}
