/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type UpsertGoalsByYearBodyEntriesItemBoardType =
  (typeof UpsertGoalsByYearBodyEntriesItemBoardType)[keyof typeof UpsertGoalsByYearBodyEntriesItemBoardType]

export const UpsertGoalsByYearBodyEntriesItemBoardType = {
  NEW_INSURANCE: 'NEW_INSURANCE',
  RENEWAL: 'RENEWAL',
} as const
