/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { UpsertGoalsByYear200Data } from './upsertGoalsByYear200Data'

export type UpsertGoalsByYear200 = {
  success: boolean
  data: UpsertGoalsByYear200Data
}
