/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod'

/**
 * @summary List tenants for authenticated user
 */
export const ListTenantsResponse = zod.object({
  success: zod.literal(true),
  data: zod.array(
    zod.object({
      id: zod.string(),
      name: zod.string(),
      slug: zod.string(),
      logo: zod.string().nullable(),
      role: zod.string(),
    })
  ),
})
