/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type {
  CancelPolicy200,
  CancelPolicyBody,
  ExportPoliciesParams,
  GeneratePolicyPdf200,
  GeneratePolicyPdf404,
  GeneratePolicyPdfParams,
  GetPolicy200,
  ImportConfirmPolicies200,
  ImportConfirmPolicies404,
  ImportStatusPolicies200,
  ImportStatusPolicies404,
  ImportUploadPolicies200,
  ImportUploadPolicies400,
  ImportUploadPolicies413,
  ImportUploadPolicies422,
  IssuePolicy201,
  IssuePolicyBody,
  ListPolicies200,
  ListPoliciesParams,
} from '../../model'

import { customFetch } from '../../../lib/api-mutator'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Export policies as CSV
 */
export type exportPoliciesResponse200 = {
  data: void
  status: 200
}

export type exportPoliciesResponseSuccess = exportPoliciesResponse200 & {
  headers: Headers
}
export type exportPoliciesResponse = exportPoliciesResponseSuccess

export const getExportPoliciesUrl = (params?: ExportPoliciesParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/v1/policies/export?${stringifiedParams}`
    : `/api/v1/policies/export`
}

export const exportPolicies = async (
  params?: ExportPoliciesParams,
  options?: RequestInit
): Promise<exportPoliciesResponse> => {
  return customFetch<exportPoliciesResponse>(getExportPoliciesUrl(params), {
    ...options,
    method: 'GET',
  })
}

export const getExportPoliciesQueryKey = (params?: ExportPoliciesParams) => {
  return [`/api/v1/policies/export`, ...(params ? [params] : [])] as const
}

export const getExportPoliciesQueryOptions = <
  TData = Awaited<ReturnType<typeof exportPolicies>>,
  TError = unknown,
>(
  params?: ExportPoliciesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof exportPolicies>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getExportPoliciesQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof exportPolicies>>> = ({
    signal,
  }) => exportPolicies(params, { signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    staleTime: 60000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof exportPolicies>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ExportPoliciesQueryResult = NonNullable<
  Awaited<ReturnType<typeof exportPolicies>>
>
export type ExportPoliciesQueryError = unknown

export function useExportPolicies<
  TData = Awaited<ReturnType<typeof exportPolicies>>,
  TError = unknown,
>(
  params: undefined | ExportPoliciesParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof exportPolicies>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof exportPolicies>>,
          TError,
          Awaited<ReturnType<typeof exportPolicies>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useExportPolicies<
  TData = Awaited<ReturnType<typeof exportPolicies>>,
  TError = unknown,
>(
  params?: ExportPoliciesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof exportPolicies>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof exportPolicies>>,
          TError,
          Awaited<ReturnType<typeof exportPolicies>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useExportPolicies<
  TData = Awaited<ReturnType<typeof exportPolicies>>,
  TError = unknown,
>(
  params?: ExportPoliciesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof exportPolicies>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Export policies as CSV
 */

export function useExportPolicies<
  TData = Awaited<ReturnType<typeof exportPolicies>>,
  TError = unknown,
>(
  params?: ExportPoliciesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof exportPolicies>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getExportPoliciesQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * @summary Export policies as CSV
 */
export const prefetchExportPoliciesQuery = async <
  TData = Awaited<ReturnType<typeof exportPolicies>>,
  TError = unknown,
>(
  queryClient: QueryClient,
  params?: ExportPoliciesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof exportPolicies>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  }
): Promise<QueryClient> => {
  const queryOptions = getExportPoliciesQueryOptions(params, options)

  await queryClient.prefetchQuery(queryOptions)

  return queryClient
}

/**
 * @summary Download CSV import template for policies
 */
export type importTemplatePoliciesResponse200 = {
  data: void
  status: 200
}

export type importTemplatePoliciesResponseSuccess =
  importTemplatePoliciesResponse200 & {
    headers: Headers
  }
export type importTemplatePoliciesResponse =
  importTemplatePoliciesResponseSuccess

export const getImportTemplatePoliciesUrl = () => {
  return `/api/v1/policies/import/template`
}

export const importTemplatePolicies = async (
  options?: RequestInit
): Promise<importTemplatePoliciesResponse> => {
  return customFetch<importTemplatePoliciesResponse>(
    getImportTemplatePoliciesUrl(),
    {
      ...options,
      method: 'GET',
    }
  )
}

export const getImportTemplatePoliciesQueryKey = () => {
  return [`/api/v1/policies/import/template`] as const
}

export const getImportTemplatePoliciesQueryOptions = <
  TData = Awaited<ReturnType<typeof importTemplatePolicies>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof importTemplatePolicies>>,
      TError,
      TData
    >
  >
  request?: SecondParameter<typeof customFetch>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getImportTemplatePoliciesQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof importTemplatePolicies>>
  > = ({ signal }) => importTemplatePolicies({ signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    staleTime: 60000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof importTemplatePolicies>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ImportTemplatePoliciesQueryResult = NonNullable<
  Awaited<ReturnType<typeof importTemplatePolicies>>
>
export type ImportTemplatePoliciesQueryError = unknown

export function useImportTemplatePolicies<
  TData = Awaited<ReturnType<typeof importTemplatePolicies>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof importTemplatePolicies>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof importTemplatePolicies>>,
          TError,
          Awaited<ReturnType<typeof importTemplatePolicies>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useImportTemplatePolicies<
  TData = Awaited<ReturnType<typeof importTemplatePolicies>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof importTemplatePolicies>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof importTemplatePolicies>>,
          TError,
          Awaited<ReturnType<typeof importTemplatePolicies>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useImportTemplatePolicies<
  TData = Awaited<ReturnType<typeof importTemplatePolicies>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof importTemplatePolicies>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Download CSV import template for policies
 */

export function useImportTemplatePolicies<
  TData = Awaited<ReturnType<typeof importTemplatePolicies>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof importTemplatePolicies>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getImportTemplatePoliciesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * @summary Download CSV import template for policies
 */
export const prefetchImportTemplatePoliciesQuery = async <
  TData = Awaited<ReturnType<typeof importTemplatePolicies>>,
  TError = unknown,
>(
  queryClient: QueryClient,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof importTemplatePolicies>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customFetch>
  }
): Promise<QueryClient> => {
  const queryOptions = getImportTemplatePoliciesQueryOptions(options)

  await queryClient.prefetchQuery(queryOptions)

  return queryClient
}

/**
 * @summary Upload and parse a policy CSV for import preview
 */
export type importUploadPoliciesResponse200 = {
  data: ImportUploadPolicies200
  status: 200
}

export type importUploadPoliciesResponse400 = {
  data: ImportUploadPolicies400
  status: 400
}

export type importUploadPoliciesResponse413 = {
  data: ImportUploadPolicies413
  status: 413
}

export type importUploadPoliciesResponse422 = {
  data: ImportUploadPolicies422
  status: 422
}

export type importUploadPoliciesResponseSuccess =
  importUploadPoliciesResponse200 & {
    headers: Headers
  }
export type importUploadPoliciesResponseError = (
  | importUploadPoliciesResponse400
  | importUploadPoliciesResponse413
  | importUploadPoliciesResponse422
) & {
  headers: Headers
}

export type importUploadPoliciesResponse =
  | importUploadPoliciesResponseSuccess
  | importUploadPoliciesResponseError

export const getImportUploadPoliciesUrl = () => {
  return `/api/v1/policies/import`
}

export const importUploadPolicies = async (
  options?: RequestInit
): Promise<importUploadPoliciesResponse> => {
  return customFetch<importUploadPoliciesResponse>(
    getImportUploadPoliciesUrl(),
    {
      ...options,
      method: 'POST',
    }
  )
}

export const getImportUploadPoliciesMutationOptions = <
  TError =
    | ImportUploadPolicies400
    | ImportUploadPolicies413
    | ImportUploadPolicies422,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof importUploadPolicies>>,
    TError,
    void,
    TContext
  >
  request?: SecondParameter<typeof customFetch>
}): UseMutationOptions<
  Awaited<ReturnType<typeof importUploadPolicies>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['importUploadPolicies']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof importUploadPolicies>>,
    void
  > = () => {
    return importUploadPolicies(requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ImportUploadPoliciesMutationResult = NonNullable<
  Awaited<ReturnType<typeof importUploadPolicies>>
>

export type ImportUploadPoliciesMutationError =
  | ImportUploadPolicies400
  | ImportUploadPolicies413
  | ImportUploadPolicies422

/**
 * @summary Upload and parse a policy CSV for import preview
 */
export const useImportUploadPolicies = <
  TError =
    | ImportUploadPolicies400
    | ImportUploadPolicies413
    | ImportUploadPolicies422,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof importUploadPolicies>>,
      TError,
      void,
      TContext
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof importUploadPolicies>>,
  TError,
  void,
  TContext
> => {
  return useMutation(
    getImportUploadPoliciesMutationOptions(options),
    queryClient
  )
}
/**
 * @summary Confirm and enqueue a staged policy import job
 */
export type importConfirmPoliciesResponse200 = {
  data: ImportConfirmPolicies200
  status: 200
}

export type importConfirmPoliciesResponse404 = {
  data: ImportConfirmPolicies404
  status: 404
}

export type importConfirmPoliciesResponseSuccess =
  importConfirmPoliciesResponse200 & {
    headers: Headers
  }
export type importConfirmPoliciesResponseError =
  importConfirmPoliciesResponse404 & {
    headers: Headers
  }

export type importConfirmPoliciesResponse =
  | importConfirmPoliciesResponseSuccess
  | importConfirmPoliciesResponseError

export const getImportConfirmPoliciesUrl = (jobId: string) => {
  return `/api/v1/policies/import/${jobId}/confirm`
}

export const importConfirmPolicies = async (
  jobId: string,
  options?: RequestInit
): Promise<importConfirmPoliciesResponse> => {
  return customFetch<importConfirmPoliciesResponse>(
    getImportConfirmPoliciesUrl(jobId),
    {
      ...options,
      method: 'POST',
    }
  )
}

export const getImportConfirmPoliciesMutationOptions = <
  TError = ImportConfirmPolicies404,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof importConfirmPolicies>>,
    TError,
    { jobId: string },
    TContext
  >
  request?: SecondParameter<typeof customFetch>
}): UseMutationOptions<
  Awaited<ReturnType<typeof importConfirmPolicies>>,
  TError,
  { jobId: string },
  TContext
> => {
  const mutationKey = ['importConfirmPolicies']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof importConfirmPolicies>>,
    { jobId: string }
  > = (props) => {
    const { jobId } = props ?? {}

    return importConfirmPolicies(jobId, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ImportConfirmPoliciesMutationResult = NonNullable<
  Awaited<ReturnType<typeof importConfirmPolicies>>
>

export type ImportConfirmPoliciesMutationError = ImportConfirmPolicies404

/**
 * @summary Confirm and enqueue a staged policy import job
 */
export const useImportConfirmPolicies = <
  TError = ImportConfirmPolicies404,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof importConfirmPolicies>>,
      TError,
      { jobId: string },
      TContext
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof importConfirmPolicies>>,
  TError,
  { jobId: string },
  TContext
> => {
  return useMutation(
    getImportConfirmPoliciesMutationOptions(options),
    queryClient
  )
}
/**
 * @summary Check the status of a policy import job
 */
export type importStatusPoliciesResponse200 = {
  data: ImportStatusPolicies200
  status: 200
}

export type importStatusPoliciesResponse404 = {
  data: ImportStatusPolicies404
  status: 404
}

export type importStatusPoliciesResponseSuccess =
  importStatusPoliciesResponse200 & {
    headers: Headers
  }
export type importStatusPoliciesResponseError =
  importStatusPoliciesResponse404 & {
    headers: Headers
  }

export type importStatusPoliciesResponse =
  | importStatusPoliciesResponseSuccess
  | importStatusPoliciesResponseError

export const getImportStatusPoliciesUrl = (jobId: string) => {
  return `/api/v1/policies/import/${jobId}/status`
}

export const importStatusPolicies = async (
  jobId: string,
  options?: RequestInit
): Promise<importStatusPoliciesResponse> => {
  return customFetch<importStatusPoliciesResponse>(
    getImportStatusPoliciesUrl(jobId),
    {
      ...options,
      method: 'GET',
    }
  )
}

export const getImportStatusPoliciesQueryKey = (jobId: string) => {
  return [`/api/v1/policies/import/${jobId}/status`] as const
}

export const getImportStatusPoliciesQueryOptions = <
  TData = Awaited<ReturnType<typeof importStatusPolicies>>,
  TError = ImportStatusPolicies404,
>(
  jobId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof importStatusPolicies>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customFetch>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getImportStatusPoliciesQueryKey(jobId)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof importStatusPolicies>>
  > = ({ signal }) => importStatusPolicies(jobId, { signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    enabled: !!jobId,
    staleTime: 60000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof importStatusPolicies>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ImportStatusPoliciesQueryResult = NonNullable<
  Awaited<ReturnType<typeof importStatusPolicies>>
>
export type ImportStatusPoliciesQueryError = ImportStatusPolicies404

export function useImportStatusPolicies<
  TData = Awaited<ReturnType<typeof importStatusPolicies>>,
  TError = ImportStatusPolicies404,
>(
  jobId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof importStatusPolicies>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof importStatusPolicies>>,
          TError,
          Awaited<ReturnType<typeof importStatusPolicies>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useImportStatusPolicies<
  TData = Awaited<ReturnType<typeof importStatusPolicies>>,
  TError = ImportStatusPolicies404,
>(
  jobId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof importStatusPolicies>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof importStatusPolicies>>,
          TError,
          Awaited<ReturnType<typeof importStatusPolicies>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useImportStatusPolicies<
  TData = Awaited<ReturnType<typeof importStatusPolicies>>,
  TError = ImportStatusPolicies404,
>(
  jobId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof importStatusPolicies>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Check the status of a policy import job
 */

export function useImportStatusPolicies<
  TData = Awaited<ReturnType<typeof importStatusPolicies>>,
  TError = ImportStatusPolicies404,
>(
  jobId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof importStatusPolicies>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getImportStatusPoliciesQueryOptions(jobId, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * @summary Check the status of a policy import job
 */
export const prefetchImportStatusPoliciesQuery = async <
  TData = Awaited<ReturnType<typeof importStatusPolicies>>,
  TError = ImportStatusPolicies404,
>(
  queryClient: QueryClient,
  jobId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof importStatusPolicies>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customFetch>
  }
): Promise<QueryClient> => {
  const queryOptions = getImportStatusPoliciesQueryOptions(jobId, options)

  await queryClient.prefetchQuery(queryOptions)

  return queryClient
}

/**
 * @summary Generate or retrieve a cached policy PDF
 */
export type generatePolicyPdfResponse200 = {
  data: GeneratePolicyPdf200
  status: 200
}

export type generatePolicyPdfResponse404 = {
  data: GeneratePolicyPdf404
  status: 404
}

export type generatePolicyPdfResponseSuccess = generatePolicyPdfResponse200 & {
  headers: Headers
}
export type generatePolicyPdfResponseError = generatePolicyPdfResponse404 & {
  headers: Headers
}

export type generatePolicyPdfResponse =
  | generatePolicyPdfResponseSuccess
  | generatePolicyPdfResponseError

export const getGeneratePolicyPdfUrl = (
  id: string,
  params?: GeneratePolicyPdfParams
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/v1/policies/${id}/pdf?${stringifiedParams}`
    : `/api/v1/policies/${id}/pdf`
}

export const generatePolicyPdf = async (
  id: string,
  params?: GeneratePolicyPdfParams,
  options?: RequestInit
): Promise<generatePolicyPdfResponse> => {
  return customFetch<generatePolicyPdfResponse>(
    getGeneratePolicyPdfUrl(id, params),
    {
      ...options,
      method: 'POST',
    }
  )
}

export const getGeneratePolicyPdfMutationOptions = <
  TError = GeneratePolicyPdf404,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof generatePolicyPdf>>,
    TError,
    { id: string; params?: GeneratePolicyPdfParams },
    TContext
  >
  request?: SecondParameter<typeof customFetch>
}): UseMutationOptions<
  Awaited<ReturnType<typeof generatePolicyPdf>>,
  TError,
  { id: string; params?: GeneratePolicyPdfParams },
  TContext
> => {
  const mutationKey = ['generatePolicyPdf']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof generatePolicyPdf>>,
    { id: string; params?: GeneratePolicyPdfParams }
  > = (props) => {
    const { id, params } = props ?? {}

    return generatePolicyPdf(id, params, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type GeneratePolicyPdfMutationResult = NonNullable<
  Awaited<ReturnType<typeof generatePolicyPdf>>
>

export type GeneratePolicyPdfMutationError = GeneratePolicyPdf404

/**
 * @summary Generate or retrieve a cached policy PDF
 */
export const useGeneratePolicyPdf = <
  TError = GeneratePolicyPdf404,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof generatePolicyPdf>>,
      TError,
      { id: string; params?: GeneratePolicyPdfParams },
      TContext
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof generatePolicyPdf>>,
  TError,
  { id: string; params?: GeneratePolicyPdfParams },
  TContext
> => {
  return useMutation(getGeneratePolicyPdfMutationOptions(options), queryClient)
}
/**
 * @summary Cancel an active policy
 */
export type cancelPolicyResponse200 = {
  data: CancelPolicy200
  status: 200
}

export type cancelPolicyResponseSuccess = cancelPolicyResponse200 & {
  headers: Headers
}
export type cancelPolicyResponse = cancelPolicyResponseSuccess

export const getCancelPolicyUrl = (id: string) => {
  return `/api/v1/policies/${id}/cancel`
}

export const cancelPolicy = async (
  id: string,
  cancelPolicyBody: CancelPolicyBody,
  options?: RequestInit
): Promise<cancelPolicyResponse> => {
  return customFetch<cancelPolicyResponse>(getCancelPolicyUrl(id), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(cancelPolicyBody),
  })
}

export const getCancelPolicyMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof cancelPolicy>>,
    TError,
    { id: string; data: CancelPolicyBody },
    TContext
  >
  request?: SecondParameter<typeof customFetch>
}): UseMutationOptions<
  Awaited<ReturnType<typeof cancelPolicy>>,
  TError,
  { id: string; data: CancelPolicyBody },
  TContext
> => {
  const mutationKey = ['cancelPolicy']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof cancelPolicy>>,
    { id: string; data: CancelPolicyBody }
  > = (props) => {
    const { id, data } = props ?? {}

    return cancelPolicy(id, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type CancelPolicyMutationResult = NonNullable<
  Awaited<ReturnType<typeof cancelPolicy>>
>
export type CancelPolicyMutationBody = CancelPolicyBody
export type CancelPolicyMutationError = unknown

/**
 * @summary Cancel an active policy
 */
export const useCancelPolicy = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof cancelPolicy>>,
      TError,
      { id: string; data: CancelPolicyBody },
      TContext
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof cancelPolicy>>,
  TError,
  { id: string; data: CancelPolicyBody },
  TContext
> => {
  return useMutation(getCancelPolicyMutationOptions(options), queryClient)
}
/**
 * @summary Issue a new policy from a proposal
 */
export type issuePolicyResponse201 = {
  data: IssuePolicy201
  status: 201
}

export type issuePolicyResponseSuccess = issuePolicyResponse201 & {
  headers: Headers
}
export type issuePolicyResponse = issuePolicyResponseSuccess

export const getIssuePolicyUrl = () => {
  return `/api/v1/policies`
}

export const issuePolicy = async (
  issuePolicyBody: IssuePolicyBody,
  options?: RequestInit
): Promise<issuePolicyResponse> => {
  return customFetch<issuePolicyResponse>(getIssuePolicyUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(issuePolicyBody),
  })
}

export const getIssuePolicyMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof issuePolicy>>,
    TError,
    { data: IssuePolicyBody },
    TContext
  >
  request?: SecondParameter<typeof customFetch>
}): UseMutationOptions<
  Awaited<ReturnType<typeof issuePolicy>>,
  TError,
  { data: IssuePolicyBody },
  TContext
> => {
  const mutationKey = ['issuePolicy']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof issuePolicy>>,
    { data: IssuePolicyBody }
  > = (props) => {
    const { data } = props ?? {}

    return issuePolicy(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type IssuePolicyMutationResult = NonNullable<
  Awaited<ReturnType<typeof issuePolicy>>
>
export type IssuePolicyMutationBody = IssuePolicyBody
export type IssuePolicyMutationError = unknown

/**
 * @summary Issue a new policy from a proposal
 */
export const useIssuePolicy = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof issuePolicy>>,
      TError,
      { data: IssuePolicyBody },
      TContext
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof issuePolicy>>,
  TError,
  { data: IssuePolicyBody },
  TContext
> => {
  return useMutation(getIssuePolicyMutationOptions(options), queryClient)
}
/**
 * @summary List policies with cursor pagination
 */
export type listPoliciesResponse200 = {
  data: ListPolicies200
  status: 200
}

export type listPoliciesResponseSuccess = listPoliciesResponse200 & {
  headers: Headers
}
export type listPoliciesResponse = listPoliciesResponseSuccess

export const getListPoliciesUrl = (params?: ListPoliciesParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/v1/policies?${stringifiedParams}`
    : `/api/v1/policies`
}

export const listPolicies = async (
  params?: ListPoliciesParams,
  options?: RequestInit
): Promise<listPoliciesResponse> => {
  return customFetch<listPoliciesResponse>(getListPoliciesUrl(params), {
    ...options,
    method: 'GET',
  })
}

export const getListPoliciesQueryKey = (params?: ListPoliciesParams) => {
  return [`/api/v1/policies`, ...(params ? [params] : [])] as const
}

export const getListPoliciesQueryOptions = <
  TData = Awaited<ReturnType<typeof listPolicies>>,
  TError = unknown,
>(
  params?: ListPoliciesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listPolicies>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getListPoliciesQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listPolicies>>> = ({
    signal,
  }) => listPolicies(params, { signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    staleTime: 60000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof listPolicies>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListPoliciesQueryResult = NonNullable<
  Awaited<ReturnType<typeof listPolicies>>
>
export type ListPoliciesQueryError = unknown

export function useListPolicies<
  TData = Awaited<ReturnType<typeof listPolicies>>,
  TError = unknown,
>(
  params: undefined | ListPoliciesParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listPolicies>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPolicies>>,
          TError,
          Awaited<ReturnType<typeof listPolicies>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useListPolicies<
  TData = Awaited<ReturnType<typeof listPolicies>>,
  TError = unknown,
>(
  params?: ListPoliciesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listPolicies>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPolicies>>,
          TError,
          Awaited<ReturnType<typeof listPolicies>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useListPolicies<
  TData = Awaited<ReturnType<typeof listPolicies>>,
  TError = unknown,
>(
  params?: ListPoliciesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listPolicies>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary List policies with cursor pagination
 */

export function useListPolicies<
  TData = Awaited<ReturnType<typeof listPolicies>>,
  TError = unknown,
>(
  params?: ListPoliciesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listPolicies>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getListPoliciesQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * @summary List policies with cursor pagination
 */
export const prefetchListPoliciesQuery = async <
  TData = Awaited<ReturnType<typeof listPolicies>>,
  TError = unknown,
>(
  queryClient: QueryClient,
  params?: ListPoliciesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listPolicies>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  }
): Promise<QueryClient> => {
  const queryOptions = getListPoliciesQueryOptions(params, options)

  await queryClient.prefetchQuery(queryOptions)

  return queryClient
}

/**
 * @summary Get a single policy by ID
 */
export type getPolicyResponse200 = {
  data: GetPolicy200
  status: 200
}

export type getPolicyResponseSuccess = getPolicyResponse200 & {
  headers: Headers
}
export type getPolicyResponse = getPolicyResponseSuccess

export const getGetPolicyUrl = (id: string) => {
  return `/api/v1/policies/${id}`
}

export const getPolicy = async (
  id: string,
  options?: RequestInit
): Promise<getPolicyResponse> => {
  return customFetch<getPolicyResponse>(getGetPolicyUrl(id), {
    ...options,
    method: 'GET',
  })
}

export const getGetPolicyQueryKey = (id: string) => {
  return [`/api/v1/policies/${id}`] as const
}

export const getGetPolicyQueryOptions = <
  TData = Awaited<ReturnType<typeof getPolicy>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPolicy>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetPolicyQueryKey(id)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPolicy>>> = ({
    signal,
  }) => getPolicy(id, { signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    staleTime: 60000,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getPolicy>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }
}

export type GetPolicyQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPolicy>>
>
export type GetPolicyQueryError = unknown

export function useGetPolicy<
  TData = Awaited<ReturnType<typeof getPolicy>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPolicy>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPolicy>>,
          TError,
          Awaited<ReturnType<typeof getPolicy>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetPolicy<
  TData = Awaited<ReturnType<typeof getPolicy>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPolicy>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPolicy>>,
          TError,
          Awaited<ReturnType<typeof getPolicy>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetPolicy<
  TData = Awaited<ReturnType<typeof getPolicy>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPolicy>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get a single policy by ID
 */

export function useGetPolicy<
  TData = Awaited<ReturnType<typeof getPolicy>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPolicy>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetPolicyQueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * @summary Get a single policy by ID
 */
export const prefetchGetPolicyQuery = async <
  TData = Awaited<ReturnType<typeof getPolicy>>,
  TError = unknown,
>(
  queryClient: QueryClient,
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPolicy>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  }
): Promise<QueryClient> => {
  const queryOptions = getGetPolicyQueryOptions(id, options)

  await queryClient.prefetchQuery(queryOptions)

  return queryClient
}
