/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod'

/**
 * @summary Export policies as CSV
 */
export const exportPoliciesQueryLimitDefault = 20
export const exportPoliciesQueryLimitMax = 100

export const ExportPoliciesQueryParams = zod.object({
  cursor: zod.string().optional(),
  limit: zod
    .number()
    .min(1)
    .max(exportPoliciesQueryLimitMax)
    .default(exportPoliciesQueryLimitDefault),
  status: zod.enum(['ACTIVE', 'CANCELLED', 'EXPIRED']).optional(),
  clientId: zod.string().optional(),
  proposalId: zod.string().optional(),
  branch: zod
    .enum(['AUTO', 'RESIDENTIAL', 'CONDOMINIUM', 'BUSINESS', 'LIFE', 'OTHER'])
    .optional(),
  search: zod.string().optional(),
})

/**
 * @summary Confirm and enqueue a staged policy import job
 */
export const ImportConfirmPoliciesParams = zod.object({
  jobId: zod.string().uuid(),
})

/**
 * @summary Check the status of a policy import job
 */
export const ImportStatusPoliciesParams = zod.object({
  jobId: zod.string().uuid(),
})

/**
 * @summary Generate or retrieve a cached policy PDF
 */

export const GeneratePolicyPdfParams = zod.object({
  id: zod.string().min(1),
})

export const GeneratePolicyPdfQueryParams = zod.object({
  force: zod.string().optional(),
})

/**
 * @summary Cancel an active policy
 */

export const CancelPolicyParams = zod.object({
  id: zod.string().min(1),
})

export const CancelPolicyBody = zod.object({
  reason: zod.string().min(1),
})

/**
 * @summary Issue a new policy from a proposal
 */

export const IssuePolicyBody = zod.object({
  proposalId: zod.string().min(1),
  policyNumber: zod.string().min(1),
  startDate: zod.string().datetime({}),
  endDate: zod.string().datetime({}),
  coverageDetails: zod.record(zod.string(), zod.unknown()).optional(),
})

/**
 * @summary List policies with cursor pagination
 */
export const listPoliciesQueryLimitDefault = 20
export const listPoliciesQueryLimitMax = 100

export const ListPoliciesQueryParams = zod.object({
  cursor: zod.string().optional(),
  limit: zod
    .number()
    .min(1)
    .max(listPoliciesQueryLimitMax)
    .default(listPoliciesQueryLimitDefault),
  status: zod.enum(['ACTIVE', 'CANCELLED', 'EXPIRED']).optional(),
  clientId: zod.string().optional(),
  proposalId: zod.string().optional(),
  branch: zod
    .enum(['AUTO', 'RESIDENTIAL', 'CONDOMINIUM', 'BUSINESS', 'LIFE', 'OTHER'])
    .optional(),
  search: zod.string().optional(),
})

/**
 * @summary Get a single policy by ID
 */

export const GetPolicyParams = zod.object({
  id: zod.string().min(1),
})
