/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type {
  CreateInsurer201,
  CreateInsurerBody,
  ListInsurers200,
  ListInsurersParams,
  UpdateInsurer200,
  UpdateInsurerBody,
} from '../../model'

import { customFetch } from '../../../lib/api-mutator'

type AwaitedInput<T> = PromiseLike<T> | T

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Create a new insurer
 */
export type createInsurerResponse201 = {
  data: CreateInsurer201
  status: 201
}

export type createInsurerResponseSuccess = createInsurerResponse201 & {
  headers: Headers
}
export type createInsurerResponse = createInsurerResponseSuccess

export const getCreateInsurerUrl = () => {
  return `/api/v1/insurers`
}

export const createInsurer = async (
  createInsurerBody: CreateInsurerBody,
  options?: RequestInit
): Promise<createInsurerResponse> => {
  return customFetch<createInsurerResponse>(getCreateInsurerUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createInsurerBody),
  })
}

export const getCreateInsurerMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createInsurer>>,
    TError,
    { data: CreateInsurerBody },
    TContext
  >
  request?: SecondParameter<typeof customFetch>
}): UseMutationOptions<
  Awaited<ReturnType<typeof createInsurer>>,
  TError,
  { data: CreateInsurerBody },
  TContext
> => {
  const mutationKey = ['createInsurer']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createInsurer>>,
    { data: CreateInsurerBody }
  > = (props) => {
    const { data } = props ?? {}

    return createInsurer(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type CreateInsurerMutationResult = NonNullable<
  Awaited<ReturnType<typeof createInsurer>>
>
export type CreateInsurerMutationBody = CreateInsurerBody
export type CreateInsurerMutationError = unknown

/**
 * @summary Create a new insurer
 */
export const useCreateInsurer = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createInsurer>>,
    TError,
    { data: CreateInsurerBody },
    TContext
  >
  request?: SecondParameter<typeof customFetch>
}): UseMutationResult<
  Awaited<ReturnType<typeof createInsurer>>,
  TError,
  { data: CreateInsurerBody },
  TContext
> => {
  return useMutation(getCreateInsurerMutationOptions(options))
}
/**
 * @summary List insurers with cursor pagination and caching
 */
export type listInsurersResponse200 = {
  data: ListInsurers200
  status: 200
}

export type listInsurersResponseSuccess = listInsurersResponse200 & {
  headers: Headers
}
export type listInsurersResponse = listInsurersResponseSuccess

export const getListInsurersUrl = (params?: ListInsurersParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/v1/insurers?${stringifiedParams}`
    : `/api/v1/insurers`
}

export const listInsurers = async (
  params?: ListInsurersParams,
  options?: RequestInit
): Promise<listInsurersResponse> => {
  return customFetch<listInsurersResponse>(getListInsurersUrl(params), {
    ...options,
    method: 'GET',
  })
}

export const getListInsurersQueryKey = (params?: ListInsurersParams) => {
  return [`/api/v1/insurers`, ...(params ? [params] : [])] as const
}

export const getListInsurersQueryOptions = <
  TData = Awaited<ReturnType<typeof listInsurers>>,
  TError = unknown,
>(
  params?: ListInsurersParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listInsurers>>,
      TError,
      TData
    >
    request?: SecondParameter<typeof customFetch>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getListInsurersQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listInsurers>>> = ({
    signal,
  }) => listInsurers(params, { signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    staleTime: 60000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof listInsurers>>,
    TError,
    TData
  > & { queryKey: QueryKey }
}

export type ListInsurersQueryResult = NonNullable<
  Awaited<ReturnType<typeof listInsurers>>
>
export type ListInsurersQueryError = unknown

/**
 * @summary List insurers with cursor pagination and caching
 */

export function useListInsurers<
  TData = Awaited<ReturnType<typeof listInsurers>>,
  TError = unknown,
>(
  params?: ListInsurersParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listInsurers>>,
      TError,
      TData
    >
    request?: SecondParameter<typeof customFetch>
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListInsurersQueryOptions(params, options)

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * @summary List insurers with cursor pagination and caching
 */
export const prefetchListInsurersQuery = async <
  TData = Awaited<ReturnType<typeof listInsurers>>,
  TError = unknown,
>(
  queryClient: QueryClient,
  params?: ListInsurersParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listInsurers>>,
      TError,
      TData
    >
    request?: SecondParameter<typeof customFetch>
  }
): Promise<QueryClient> => {
  const queryOptions = getListInsurersQueryOptions(params, options)

  await queryClient.prefetchQuery(queryOptions)

  return queryClient
}

/**
 * @summary Update an insurer
 */
export type updateInsurerResponse200 = {
  data: UpdateInsurer200
  status: 200
}

export type updateInsurerResponseSuccess = updateInsurerResponse200 & {
  headers: Headers
}
export type updateInsurerResponse = updateInsurerResponseSuccess

export const getUpdateInsurerUrl = (id: string) => {
  return `/api/v1/insurers/${id}`
}

export const updateInsurer = async (
  id: string,
  updateInsurerBody: UpdateInsurerBody,
  options?: RequestInit
): Promise<updateInsurerResponse> => {
  return customFetch<updateInsurerResponse>(getUpdateInsurerUrl(id), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateInsurerBody),
  })
}

export const getUpdateInsurerMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateInsurer>>,
    TError,
    { id: string; data: UpdateInsurerBody },
    TContext
  >
  request?: SecondParameter<typeof customFetch>
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateInsurer>>,
  TError,
  { id: string; data: UpdateInsurerBody },
  TContext
> => {
  const mutationKey = ['updateInsurer']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateInsurer>>,
    { id: string; data: UpdateInsurerBody }
  > = (props) => {
    const { id, data } = props ?? {}

    return updateInsurer(id, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UpdateInsurerMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateInsurer>>
>
export type UpdateInsurerMutationBody = UpdateInsurerBody
export type UpdateInsurerMutationError = unknown

/**
 * @summary Update an insurer
 */
export const useUpdateInsurer = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateInsurer>>,
    TError,
    { id: string; data: UpdateInsurerBody },
    TContext
  >
  request?: SecondParameter<typeof customFetch>
}): UseMutationResult<
  Awaited<ReturnType<typeof updateInsurer>>,
  TError,
  { id: string; data: UpdateInsurerBody },
  TContext
> => {
  return useMutation(getUpdateInsurerMutationOptions(options))
}
