/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod'

/**
 * @summary Create a new insurer
 */

export const CreateInsurerBody = zod.object({
  name: zod.string().min(1),
  code: zod.union([zod.enum(['']), zod.string()]).optional(),
})

/**
 * @summary List insurers with cursor pagination and caching
 */
export const listInsurersQueryLimitDefault = 20
export const listInsurersQueryLimitMax = 100

export const listInsurersQuerySortByDefault = `name`
export const listInsurersQuerySortOrderDefault = `asc`

export const ListInsurersQueryParams = zod.object({
  active: zod.union([zod.enum(['true']), zod.enum(['false'])]).optional(),
  search: zod.string().optional(),
  cursor: zod.string().optional(),
  limit: zod
    .number()
    .min(1)
    .max(listInsurersQueryLimitMax)
    .default(listInsurersQueryLimitDefault),
  sortBy: zod
    .enum(['name', 'code', 'active', 'updatedAt'])
    .default(listInsurersQuerySortByDefault),
  sortOrder: zod
    .enum(['asc', 'desc'])
    .default(listInsurersQuerySortOrderDefault),
})

export const ListInsurersResponse = zod.object({
  success: zod.literal(true),
  data: zod.array(
    zod.object({
      id: zod.string(),
      organizationId: zod.string(),
      name: zod.string(),
      code: zod.string().nullable(),
      active: zod.boolean(),
      createdAt: zod.string().datetime({}),
      updatedAt: zod.string().datetime({}),
    })
  ),
  meta: zod.object({
    nextCursor: zod.string().nullish(),
  }),
})

/**
 * @summary Get an insurer by id
 */

export const GetInsurerParams = zod.object({
  id: zod.string().min(1),
})

export const GetInsurerResponse = zod.object({
  success: zod.literal(true),
  data: zod.object({
    id: zod.string(),
    organizationId: zod.string(),
    name: zod.string(),
    code: zod.string().nullable(),
    active: zod.boolean(),
    createdAt: zod.string().datetime({}),
    updatedAt: zod.string().datetime({}),
  }),
})

/**
 * @summary Update an insurer
 */

export const UpdateInsurerParams = zod.object({
  id: zod.string().min(1),
})

export const UpdateInsurerBody = zod.object({
  name: zod.string().min(1),
  code: zod.union([zod.enum(['']), zod.string()]).optional(),
  active: zod.boolean(),
})

export const UpdateInsurerResponse = zod.object({
  success: zod.literal(true),
  data: zod.object({
    id: zod.string(),
    organizationId: zod.string(),
    name: zod.string(),
    code: zod.string().nullable(),
    active: zod.boolean(),
    createdAt: zod.string().datetime({}),
    updatedAt: zod.string().datetime({}),
  }),
})
