-- AlterEnum
ALTER TYPE "DocumentType" ADD VALUE 'HEALTH_DECLARATION';
ALTER TYPE "DocumentType" ADD VALUE 'PROOF_OF_ADDRESS';
ALTER TYPE "DocumentType" ADD VALUE 'SOCIAL_CONTRACT';
ALTER TYPE "DocumentType" ADD VALUE 'CNPJ_CARD';
