/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query'
import { useMutation } from '@tanstack/react-query'

import type {
  CompleteOnboarding200,
  CompleteOnboarding400,
  CompleteOnboarding401,
  CompleteOnboarding404,
  CompleteOnboardingBody,
} from '../../model'

import { customFetch } from '../../../lib/api-mutator'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Cria organização + subscription TRIALING 14d após signup (Fase 7A)
 */
export type completeOnboardingResponse200 = {
  data: CompleteOnboarding200
  status: 200
}

export type completeOnboardingResponse400 = {
  data: CompleteOnboarding400
  status: 400
}

export type completeOnboardingResponse401 = {
  data: CompleteOnboarding401
  status: 401
}

export type completeOnboardingResponse404 = {
  data: CompleteOnboarding404
  status: 404
}

export type completeOnboardingResponseSuccess =
  completeOnboardingResponse200 & {
    headers: Headers
  }
export type completeOnboardingResponseError = (
  | completeOnboardingResponse400
  | completeOnboardingResponse401
  | completeOnboardingResponse404
) & {
  headers: Headers
}

export type completeOnboardingResponse =
  | completeOnboardingResponseSuccess
  | completeOnboardingResponseError

export const getCompleteOnboardingUrl = () => {
  return `/api/v1/onboarding/complete`
}

export const completeOnboarding = async (
  completeOnboardingBody: CompleteOnboardingBody,
  options?: RequestInit
): Promise<completeOnboardingResponse> => {
  return customFetch<completeOnboardingResponse>(getCompleteOnboardingUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(completeOnboardingBody),
  })
}

export const getCompleteOnboardingMutationOptions = <
  TError =
    | CompleteOnboarding400
    | CompleteOnboarding401
    | CompleteOnboarding404,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof completeOnboarding>>,
    TError,
    { data: CompleteOnboardingBody },
    TContext
  >
  request?: SecondParameter<typeof customFetch>
}): UseMutationOptions<
  Awaited<ReturnType<typeof completeOnboarding>>,
  TError,
  { data: CompleteOnboardingBody },
  TContext
> => {
  const mutationKey = ['completeOnboarding']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof completeOnboarding>>,
    { data: CompleteOnboardingBody }
  > = (props) => {
    const { data } = props ?? {}

    return completeOnboarding(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type CompleteOnboardingMutationResult = NonNullable<
  Awaited<ReturnType<typeof completeOnboarding>>
>
export type CompleteOnboardingMutationBody = CompleteOnboardingBody
export type CompleteOnboardingMutationError =
  | CompleteOnboarding400
  | CompleteOnboarding401
  | CompleteOnboarding404

/**
 * @summary Cria organização + subscription TRIALING 14d após signup (Fase 7A)
 */
export const useCompleteOnboarding = <
  TError =
    | CompleteOnboarding400
    | CompleteOnboarding401
    | CompleteOnboarding404,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof completeOnboarding>>,
      TError,
      { data: CompleteOnboardingBody },
      TContext
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof completeOnboarding>>,
  TError,
  { data: CompleteOnboardingBody },
  TContext
> => {
  return useMutation(getCompleteOnboardingMutationOptions(options), queryClient)
}
