import { defineConfig } from 'tsup'

export default defineConfig({
  entry: {
    server: 'src/server.ts',
  },
  format: ['esm'],
  target: 'node22',
  outDir: 'dist',
  clean: true,
  splitting: false,
  sourcemap: true,
  noExternal: [
    '@repo/asaas-adapter',
    '@repo/auth',
    '@repo/billing-port',
    '@repo/core',
    '@repo/db',
    '@repo/env',
    '@repo/shared',
  ],
  external: [
    'fastify',
    '@fastify/*',
    '@prisma/client',
    '@prisma/adapter-pg',
    'pg',
    'prisma',
    'bullmq',
    'ioredis',
    'socket.io',
    'pino',
    'better-auth',
    '@casl/*',
    'tsyringe',
    'reflect-metadata',
    'zod',
    '@t3-oss/env-core',
    'resend',
    '@aws-sdk/*',
    'file-type',
  ],
})
