/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod'

/**
 * @summary Export clients as CSV
 */
export const exportClientsQueryLimitDefault = 20
export const exportClientsQueryLimitMax = 100

export const exportClientsQuerySortByDefault = `createdAt`
export const exportClientsQuerySortOrderDefault = `desc`

export const ExportClientsQueryParams = zod.object({
  hasActivePolicy: zod
    .union([zod.enum(['true']), zod.enum(['false'])])
    .optional(),
  personTypeIn: zod.string().optional(),
  search: zod.string().optional(),
  cursor: zod.string().optional(),
  limit: zod
    .number()
    .min(1)
    .max(exportClientsQueryLimitMax)
    .default(exportClientsQueryLimitDefault),
  sortBy: zod
    .enum(['createdAt', 'legalName'])
    .default(exportClientsQuerySortByDefault),
  sortOrder: zod
    .enum(['asc', 'desc'])
    .default(exportClientsQuerySortOrderDefault),
})

/**
 * @summary Upload CSV file for client import (preview + validation)
 */
export const ImportUploadClientsResponse = zod.object({
  success: zod.literal(true),
  data: zod.object({
    jobId: zod.string().uuid(),
    preview: zod.array(zod.record(zod.string(), zod.string())),
    validationSummary: zod.object({
      total: zod.number(),
      valid: zod.number(),
      invalid: zod.number(),
      errors: zod.array(
        zod.object({
          row: zod.number(),
          field: zod.string(),
          message: zod.string(),
          value: zod.string().optional(),
        })
      ),
    }),
  }),
})

/**
 * @summary Confirm and enqueue a staged client import job
 */
export const ImportConfirmClientsParams = zod.object({
  jobId: zod.string().uuid(),
})

export const ImportConfirmClientsResponse = zod.object({
  success: zod.literal(true),
  data: zod.object({
    jobId: zod.string().uuid(),
  }),
})

/**
 * @summary Get the status of a client import job
 */
export const ImportStatusClientsParams = zod.object({
  jobId: zod.string().uuid(),
})

export const ImportStatusClientsResponse = zod.object({
  success: zod.literal(true),
  data: zod.object({
    status: zod.enum(['active', 'completed', 'failed', 'waiting', 'not_found']),
    progress: zod.record(zod.string(), zod.unknown()).nullable(),
  }),
})

/**
 * @summary Create a client (fiscal data)
 */
export const createClientBodyLegalNameMax = 200

export const createClientBodyDocumentMin = 11
export const createClientBodyDocumentMax = 14

export const createClientBodyPersonTypeDefault = `INDIVIDUAL`
export const createClientBodyProfessionMax = 100

export const createClientBodyAddressCepRegExp = new RegExp('^\\d{5}-?\\d{3}$')
export const createClientBodyAddressStreetMax = 200

export const createClientBodyAddressNumberMax = 20

export const createClientBodyAddressComplementMax = 200

export const createClientBodyAddressNeighborhoodMax = 100

export const createClientBodyAddressCityMax = 100

export const createClientBodyAddressStateMin = 2
export const createClientBodyAddressStateMax = 2

export const CreateClientBody = zod.object({
  legalName: zod.string().min(1).max(createClientBodyLegalNameMax),
  document: zod
    .string()
    .min(createClientBodyDocumentMin)
    .max(createClientBodyDocumentMax),
  personType: zod
    .enum(['INDIVIDUAL', 'COMPANY'])
    .default(createClientBodyPersonTypeDefault),
  profession: zod.string().max(createClientBodyProfessionMax).nullish(),
  maritalStatus: zod
    .enum(['SINGLE', 'MARRIED', 'DIVORCED', 'WIDOWED', 'OTHER'])
    .nullish(),
  address: zod
    .object({
      cep: zod.string().regex(createClientBodyAddressCepRegExp),
      street: zod.string().min(1).max(createClientBodyAddressStreetMax),
      number: zod.string().max(createClientBodyAddressNumberMax).nullish(),
      complement: zod
        .string()
        .max(createClientBodyAddressComplementMax)
        .nullish(),
      neighborhood: zod
        .string()
        .min(1)
        .max(createClientBodyAddressNeighborhoodMax),
      city: zod.string().min(1).max(createClientBodyAddressCityMax),
      state: zod
        .string()
        .min(createClientBodyAddressStateMin)
        .max(createClientBodyAddressStateMax),
    })
    .nullish(),
  fiscalBirthDate: zod.string().datetime({}).nullish(),
})

/**
 * @summary List clients with cursor pagination
 */
export const listClientsQueryLimitDefault = 20
export const listClientsQueryLimitMax = 100

export const listClientsQuerySortByDefault = `createdAt`
export const listClientsQuerySortOrderDefault = `desc`

export const ListClientsQueryParams = zod.object({
  hasActivePolicy: zod
    .union([zod.enum(['true']), zod.enum(['false'])])
    .optional(),
  personTypeIn: zod.string().optional(),
  search: zod.string().optional(),
  cursor: zod.string().optional(),
  limit: zod
    .number()
    .min(1)
    .max(listClientsQueryLimitMax)
    .default(listClientsQueryLimitDefault),
  sortBy: zod
    .enum(['createdAt', 'legalName'])
    .default(listClientsQuerySortByDefault),
  sortOrder: zod
    .enum(['asc', 'desc'])
    .default(listClientsQuerySortOrderDefault),
})

export const listClientsResponseDataItemAddressCepRegExp = new RegExp(
  '^\\d{8}$'
)
export const listClientsResponseDataItemAddressStreetMax = 200

export const listClientsResponseDataItemAddressNumberMax = 20

export const listClientsResponseDataItemAddressComplementMax = 200

export const listClientsResponseDataItemAddressNeighborhoodMax = 100

export const listClientsResponseDataItemAddressCityMax = 100

export const listClientsResponseDataItemAddressStateMin = 2
export const listClientsResponseDataItemAddressStateMax = 2

export const ListClientsResponse = zod.object({
  success: zod.literal(true),
  data: zod.array(
    zod.object({
      id: zod.string(),
      organizationId: zod.string(),
      legalName: zod.string(),
      document: zod.string(),
      personType: zod.enum(['INDIVIDUAL', 'COMPANY']),
      profession: zod.string().nullable(),
      maritalStatus: zod
        .enum(['SINGLE', 'MARRIED', 'DIVORCED', 'WIDOWED', 'OTHER'])
        .nullable(),
      address: zod
        .object({
          cep: zod.string().regex(listClientsResponseDataItemAddressCepRegExp),
          street: zod
            .string()
            .min(1)
            .max(listClientsResponseDataItemAddressStreetMax),
          number: zod
            .string()
            .max(listClientsResponseDataItemAddressNumberMax)
            .nullable(),
          complement: zod
            .string()
            .max(listClientsResponseDataItemAddressComplementMax)
            .nullable(),
          neighborhood: zod
            .string()
            .min(1)
            .max(listClientsResponseDataItemAddressNeighborhoodMax),
          city: zod
            .string()
            .min(1)
            .max(listClientsResponseDataItemAddressCityMax),
          state: zod
            .string()
            .min(listClientsResponseDataItemAddressStateMin)
            .max(listClientsResponseDataItemAddressStateMax),
        })
        .nullable(),
      fiscalBirthDate: zod.string().datetime({}).nullable(),
      createdAt: zod.string().datetime({}),
      updatedAt: zod.string().datetime({}),
      deletedAt: zod.string().datetime({}).nullable(),
      activePolicyCount: zod.number(),
      totalPolicyCount: zod.number(),
      contactCount: zod.number(),
    })
  ),
  meta: zod.object({
    total: zod.number().optional(),
    nextCursor: zod.string().nullish(),
  }),
})

/**
 * @summary LGPD data anonymization — irreversible
 */

export const LgpdDeleteClientParams = zod.object({
  id: zod.string().min(1),
})

/**
 * @summary Get a client by ID with metrics
 */

export const GetClientParams = zod.object({
  id: zod.string().min(1),
})

export const getClientResponseDataAddressCepRegExp = new RegExp('^\\d{8}$')
export const getClientResponseDataAddressStreetMax = 200

export const getClientResponseDataAddressNumberMax = 20

export const getClientResponseDataAddressComplementMax = 200

export const getClientResponseDataAddressNeighborhoodMax = 100

export const getClientResponseDataAddressCityMax = 100

export const getClientResponseDataAddressStateMin = 2
export const getClientResponseDataAddressStateMax = 2

export const GetClientResponse = zod.object({
  success: zod.literal(true),
  data: zod.object({
    id: zod.string(),
    organizationId: zod.string(),
    legalName: zod.string(),
    document: zod.string(),
    personType: zod.enum(['INDIVIDUAL', 'COMPANY']),
    profession: zod.string().nullable(),
    maritalStatus: zod
      .enum(['SINGLE', 'MARRIED', 'DIVORCED', 'WIDOWED', 'OTHER'])
      .nullable(),
    address: zod
      .object({
        cep: zod.string().regex(getClientResponseDataAddressCepRegExp),
        street: zod.string().min(1).max(getClientResponseDataAddressStreetMax),
        number: zod
          .string()
          .max(getClientResponseDataAddressNumberMax)
          .nullable(),
        complement: zod
          .string()
          .max(getClientResponseDataAddressComplementMax)
          .nullable(),
        neighborhood: zod
          .string()
          .min(1)
          .max(getClientResponseDataAddressNeighborhoodMax),
        city: zod.string().min(1).max(getClientResponseDataAddressCityMax),
        state: zod
          .string()
          .min(getClientResponseDataAddressStateMin)
          .max(getClientResponseDataAddressStateMax),
      })
      .nullable(),
    fiscalBirthDate: zod.string().datetime({}).nullable(),
    createdAt: zod.string().datetime({}),
    updatedAt: zod.string().datetime({}),
    deletedAt: zod.string().datetime({}).nullable(),
    activePolicyCount: zod.number(),
    totalPolicyCount: zod.number(),
    contactCount: zod.number(),
  }),
})

/**
 * @summary Update a client (fiscal data only)
 */

export const UpdateClientParams = zod.object({
  id: zod.string().min(1),
})

export const updateClientBodyAddressCepRegExp = new RegExp('^\\d{5}-?\\d{3}$')
export const updateClientBodyAddressStreetMax = 200

export const updateClientBodyAddressNumberMax = 20

export const updateClientBodyAddressComplementMax = 200

export const updateClientBodyAddressNeighborhoodMax = 100

export const updateClientBodyAddressCityMax = 100

export const updateClientBodyAddressStateMin = 2
export const updateClientBodyAddressStateMax = 2

export const UpdateClientBody = zod.object({
  legalName: zod.string().min(1).optional(),
  personType: zod.enum(['INDIVIDUAL', 'COMPANY']).optional(),
  profession: zod.string().nullish(),
  maritalStatus: zod
    .enum(['SINGLE', 'MARRIED', 'DIVORCED', 'WIDOWED', 'OTHER'])
    .nullish(),
  address: zod
    .object({
      cep: zod.string().regex(updateClientBodyAddressCepRegExp),
      street: zod.string().min(1).max(updateClientBodyAddressStreetMax),
      number: zod.string().max(updateClientBodyAddressNumberMax).nullish(),
      complement: zod
        .string()
        .max(updateClientBodyAddressComplementMax)
        .nullish(),
      neighborhood: zod
        .string()
        .min(1)
        .max(updateClientBodyAddressNeighborhoodMax),
      city: zod.string().min(1).max(updateClientBodyAddressCityMax),
      state: zod
        .string()
        .min(updateClientBodyAddressStateMin)
        .max(updateClientBodyAddressStateMax),
    })
    .nullish(),
  fiscalBirthDate: zod.string().datetime({}).nullish(),
})

export const updateClientResponseDataAddressCepRegExp = new RegExp('^\\d{8}$')
export const updateClientResponseDataAddressStreetMax = 200

export const updateClientResponseDataAddressNumberMax = 20

export const updateClientResponseDataAddressComplementMax = 200

export const updateClientResponseDataAddressNeighborhoodMax = 100

export const updateClientResponseDataAddressCityMax = 100

export const updateClientResponseDataAddressStateMin = 2
export const updateClientResponseDataAddressStateMax = 2

export const UpdateClientResponse = zod.object({
  success: zod.literal(true),
  data: zod.object({
    id: zod.string(),
    organizationId: zod.string(),
    legalName: zod.string(),
    document: zod.string(),
    personType: zod.enum(['INDIVIDUAL', 'COMPANY']),
    profession: zod.string().nullable(),
    maritalStatus: zod
      .enum(['SINGLE', 'MARRIED', 'DIVORCED', 'WIDOWED', 'OTHER'])
      .nullable(),
    address: zod
      .object({
        cep: zod.string().regex(updateClientResponseDataAddressCepRegExp),
        street: zod
          .string()
          .min(1)
          .max(updateClientResponseDataAddressStreetMax),
        number: zod
          .string()
          .max(updateClientResponseDataAddressNumberMax)
          .nullable(),
        complement: zod
          .string()
          .max(updateClientResponseDataAddressComplementMax)
          .nullable(),
        neighborhood: zod
          .string()
          .min(1)
          .max(updateClientResponseDataAddressNeighborhoodMax),
        city: zod.string().min(1).max(updateClientResponseDataAddressCityMax),
        state: zod
          .string()
          .min(updateClientResponseDataAddressStateMin)
          .max(updateClientResponseDataAddressStateMax),
      })
      .nullable(),
    fiscalBirthDate: zod.string().datetime({}).nullable(),
    createdAt: zod.string().datetime({}),
    updatedAt: zod.string().datetime({}),
    deletedAt: zod.string().datetime({}).nullable(),
  }),
})

/**
 * @summary Soft-delete a client
 */

export const DeleteClientParams = zod.object({
  id: zod.string().min(1),
})
