/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod'

/**
 * @summary Get current organization details
 */
export const GetOrganizationResponse = zod.object({
  success: zod.literal(true),
  data: zod.object({
    id: zod.string(),
    name: zod.string(),
    slug: zod.string(),
    logo: zod.string().nullable(),
    createdAt: zod.string(),
  }),
})

/**
 * @summary Update organization name and slug
 */
export const updateOrganizationBodyNameMin = 2
export const updateOrganizationBodyNameMax = 100

export const updateOrganizationBodySlugMin = 2
export const updateOrganizationBodySlugMax = 50

export const updateOrganizationBodySlugRegExp = new RegExp('^[a-z0-9-]+$')

export const UpdateOrganizationBody = zod.object({
  name: zod
    .string()
    .min(updateOrganizationBodyNameMin)
    .max(updateOrganizationBodyNameMax),
  slug: zod
    .string()
    .min(updateOrganizationBodySlugMin)
    .max(updateOrganizationBodySlugMax)
    .regex(updateOrganizationBodySlugRegExp),
})

export const UpdateOrganizationResponse = zod.object({
  success: zod.literal(true),
  data: zod.object({
    id: zod.string(),
    name: zod.string(),
    slug: zod.string(),
    logo: zod.string().nullable(),
    createdAt: zod.string(),
  }),
})

/**
 * @summary Upload organization logo
 */
export const UploadOrganizationLogoResponse = zod.object({
  success: zod.literal(true),
  data: zod.object({
    id: zod.string(),
    name: zod.string(),
    slug: zod.string(),
    logo: zod.string().nullable(),
    createdAt: zod.string(),
  }),
})
