/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod'

export const exportCommissionsQueryLimitDefault = 20
export const exportCommissionsQueryLimitMax = 100

export const ExportCommissionsQueryParams = zod.object({
  cursor: zod.string().optional(),
  limit: zod
    .number()
    .min(1)
    .max(exportCommissionsQueryLimitMax)
    .default(exportCommissionsQueryLimitDefault),
  dateFrom: zod.string().datetime({}).optional(),
  dateTo: zod.string().datetime({}).optional(),
  status: zod
    .enum([
      'PENDING_COMMERCIAL',
      'PENDING_ADMIN',
      'APPROVED',
      'PAID',
      'REJECTED',
      'REVERSED',
    ])
    .optional(),
  salespersonId: zod.string().optional(),
  policyId: zod.string().optional(),
  search: zod.string().optional(),
})

export const listCommissionsQueryLimitDefault = 20
export const listCommissionsQueryLimitMax = 100

export const ListCommissionsQueryParams = zod.object({
  cursor: zod.string().optional(),
  limit: zod
    .number()
    .min(1)
    .max(listCommissionsQueryLimitMax)
    .default(listCommissionsQueryLimitDefault),
  dateFrom: zod.string().datetime({}).optional(),
  dateTo: zod.string().datetime({}).optional(),
  status: zod
    .enum([
      'PENDING_COMMERCIAL',
      'PENDING_ADMIN',
      'APPROVED',
      'PAID',
      'REJECTED',
      'REVERSED',
    ])
    .optional(),
  salespersonId: zod.string().optional(),
  policyId: zod.string().optional(),
  search: zod.string().optional(),
})

export const GetCommissionParams = zod.object({
  id: zod.string().min(1),
})

export const ApproveCommissionCommercialParams = zod.object({
  id: zod.string().min(1),
})

export const ApproveCommissionAdminParams = zod.object({
  id: zod.string().min(1),
})

export const RejectCommissionParams = zod.object({
  id: zod.string().min(1),
})

export const RejectCommissionBody = zod.object({
  reason: zod.string().min(1),
})

export const PayCommissionParams = zod.object({
  id: zod.string().min(1),
})

export const ReverseCommissionParams = zod.object({
  id: zod.string().min(1),
})
