/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod'

/**
 * @summary Export proposals as CSV
 */
export const exportProposalsQueryLimitDefault = 20
export const exportProposalsQueryLimitMax = 100

export const exportProposalsQuerySortByDefault = `createdAt`
export const exportProposalsQuerySortOrderDefault = `desc`

export const ExportProposalsQueryParams = zod.object({
  cursor: zod.string().optional(),
  limit: zod
    .number()
    .min(1)
    .max(exportProposalsQueryLimitMax)
    .default(exportProposalsQueryLimitDefault),
  stage: zod
    .enum([
      'CAPTURE',
      'QUOTE',
      'PROTOCOL',
      'INSPECTION',
      'PAYMENT',
      'POLICY_ISSUED',
      'LOST',
    ])
    .optional(),
  contactId: zod.string().optional(),
  clientId: zod.string().optional(),
  salespersonId: zod.string().optional(),
  insurerId: zod.string().optional(),
  sourcePolicyId: zod.string().optional(),
  boardType: zod.enum(['NEW_INSURANCE', 'RENEWAL', 'ENDORSEMENT']).optional(),
  stageIn: zod.string().optional(),
  branchIn: zod.string().optional(),
  salespersonIdIn: zod.string().optional(),
  createdFrom: zod.string().datetime({}).optional(),
  createdTo: zod.string().datetime({}).optional(),
  updatedAtFrom: zod.string().datetime({}).optional(),
  updatedAtTo: zod.string().datetime({}).optional(),
  search: zod.string().optional(),
  sortBy: zod
    .enum([
      'clientName',
      'branch',
      'stage',
      'boardType',
      'premiumValueInCents',
      'createdAt',
    ])
    .default(exportProposalsQuerySortByDefault),
  sortOrder: zod
    .enum(['asc', 'desc'])
    .default(exportProposalsQuerySortOrderDefault),
})

/**
 * @summary Generate or retrieve proposal PDF
 */

export const GenerateProposalPdfParams = zod.object({
  id: zod.string().min(1),
})

export const GenerateProposalPdfResponse = zod.object({
  success: zod.literal(true),
  data: zod.object({
    url: zod.string(),
    cached: zod.boolean(),
  }),
})

/**
 * @summary Generate PDF and send quote to client via email
 */

export const SendQuoteParams = zod.object({
  id: zod.string().min(1),
})

/**
 * @summary Update proposal date fields
 */

export const UpdateProposalDatesParams = zod.object({
  id: zod.string().min(1),
})

export const UpdateProposalDatesBody = zod.object({
  coverageStartDate: zod.string().datetime({}).optional(),
  coverageEndDate: zod.string().datetime({}).optional(),
  clientResponseAt: zod.string().datetime({}).optional(),
  quoteValidUntil: zod.string().datetime({}).optional(),
})

export const updateProposalDatesResponseDataDetailsOneManufacturingYearMin = 1900
export const updateProposalDatesResponseDataDetailsOneManufacturingYearMax = 2100

export const updateProposalDatesResponseDataDetailsOneModelYearMin = 1900
export const updateProposalDatesResponseDataDetailsOneModelYearMax = 2100

export const updateProposalDatesResponseDataDetailsTwoStateMin = 2
export const updateProposalDatesResponseDataDetailsTwoStateMax = 2

export const updateProposalDatesResponseDataDetailsThreeStateMin = 2
export const updateProposalDatesResponseDataDetailsThreeStateMax = 2

export const updateProposalDatesResponseDataDetailsFourStateMin = 2
export const updateProposalDatesResponseDataDetailsFourStateMax = 2

export const updateProposalDatesResponseDataDetailsFiveMonthlyIncomeCentsMin = 0

export const updateProposalDatesResponseDataDetailsFiveHeightInCentimetersMin = 100
export const updateProposalDatesResponseDataDetailsFiveHeightInCentimetersMax = 250

export const updateProposalDatesResponseDataDetailsFiveWeightInGramsMin = 20000
export const updateProposalDatesResponseDataDetailsFiveWeightInGramsMax = 300000

export const UpdateProposalDatesResponse = zod.object({
  success: zod.literal(true),
  data: zod.object({
    id: zod.string(),
    organizationId: zod.string(),
    contactId: zod.string(),
    salespersonId: zod.string(),
    stage: zod.enum([
      'CAPTURE',
      'QUOTE',
      'PROTOCOL',
      'INSPECTION',
      'PAYMENT',
      'POLICY_ISSUED',
      'LOST',
    ]),
    boardType: zod.enum(['NEW_INSURANCE', 'RENEWAL', 'ENDORSEMENT']),
    branch: zod.enum([
      'AUTO',
      'RESIDENTIAL',
      'CONDOMINIUM',
      'BUSINESS',
      'LIFE',
      'OTHER',
    ]),
    premiumValueInCents: zod.number(),
    commissionPercentageInCents: zod.number(),
    details: zod
      .union([
        zod.object({
          branch: zod.enum(['AUTO']),
          brand: zod.string().min(1),
          model: zod.string().min(1),
          manufacturingYear: zod
            .number()
            .min(updateProposalDatesResponseDataDetailsOneManufacturingYearMin)
            .max(updateProposalDatesResponseDataDetailsOneManufacturingYearMax),
          modelYear: zod
            .number()
            .min(updateProposalDatesResponseDataDetailsOneModelYearMin)
            .max(updateProposalDatesResponseDataDetailsOneModelYearMax),
          licensePlate: zod.string().optional(),
          vin: zod.string().optional(),
          color: zod.string().optional(),
          fuelType: zod.string().optional(),
          vehicleUsage: zod.string().optional(),
        }),
        zod.object({
          branch: zod.enum(['RESIDENTIAL']),
          propertyType: zod.string().min(1),
          propertyUsage: zod.string().min(1),
          cep: zod.string().min(1),
          street: zod.string().optional(),
          number: zod.string().optional(),
          complement: zod.string().optional(),
          neighborhood: zod.string().optional(),
          city: zod.string().optional(),
          state: zod
            .string()
            .min(updateProposalDatesResponseDataDetailsTwoStateMin)
            .max(updateProposalDatesResponseDataDetailsTwoStateMax)
            .optional(),
          construction: zod.string().optional(),
          areaM2: zod.number().optional(),
        }),
        zod.object({
          branch: zod.enum(['CONDOMINIUM']),
          condominiumName: zod.string().min(1),
          unitCount: zod.number().min(1),
          cep: zod.string().min(1),
          street: zod.string().optional(),
          number: zod.string().optional(),
          complement: zod.string().optional(),
          neighborhood: zod.string().optional(),
          city: zod.string().optional(),
          state: zod
            .string()
            .min(updateProposalDatesResponseDataDetailsThreeStateMin)
            .max(updateProposalDatesResponseDataDetailsThreeStateMax)
            .optional(),
          constructionYear: zod.number().optional(),
          floorCount: zod.number().optional(),
          blockCount: zod.number().optional(),
          elevatorCount: zod.number().optional(),
          employeeCount: zod.number().optional(),
          hasSecurityEquipment: zod.boolean().optional(),
          securityEquipmentDetails: zod.string().optional(),
          hasFireEquipment: zod.boolean().optional(),
          fireEquipmentDetails: zod.string().optional(),
        }),
        zod.object({
          branch: zod.enum(['BUSINESS']),
          legalName: zod.string().min(1),
          cnpj: zod.string().min(1),
          businessActivity: zod.string().min(1),
          cep: zod.string().optional(),
          street: zod.string().optional(),
          number: zod.string().optional(),
          complement: zod.string().optional(),
          neighborhood: zod.string().optional(),
          city: zod.string().optional(),
          state: zod
            .string()
            .min(updateProposalDatesResponseDataDetailsFourStateMin)
            .max(updateProposalDatesResponseDataDetailsFourStateMax)
            .optional(),
          areaM2: zod.number().optional(),
        }),
        zod.object({
          branch: zod.enum(['LIFE']),
          occupation: zod.string().min(1),
          monthlyIncomeCents: zod
            .number()
            .min(
              updateProposalDatesResponseDataDetailsFiveMonthlyIncomeCentsMin
            )
            .optional(),
          isSmoker: zod.boolean().optional(),
          extremeSports: zod.boolean().optional(),
          heightInCentimeters: zod
            .number()
            .min(
              updateProposalDatesResponseDataDetailsFiveHeightInCentimetersMin
            )
            .max(
              updateProposalDatesResponseDataDetailsFiveHeightInCentimetersMax
            )
            .optional(),
          weightInGrams: zod
            .number()
            .min(updateProposalDatesResponseDataDetailsFiveWeightInGramsMin)
            .max(updateProposalDatesResponseDataDetailsFiveWeightInGramsMax)
            .optional(),
          beneficiaries: zod.string().optional(),
        }),
        zod.object({
          branch: zod.enum(['OTHER']),
          description: zod.string().min(1),
        }),
      ])
      .nullable(),
    lostReason: zod.string().nullable(),
    observations: zod.string().nullable(),
    renewalPolicyId: zod.string().nullable(),
    renewalPolicyNumber: zod.string().nullable(),
    sourcePolicyId: zod.string().nullable(),
    endorsementType: zod.string().nullable(),
    endorsementReason: zod.string().nullable(),
    sourcePolicySnapshot: zod
      .object({
        policyNumber: zod.string(),
        clientName: zod.string(),
        startDate: zod.string().datetime({}),
        endDate: zod.string().datetime({}),
        status: zod.enum(['ACTIVE', 'CANCELLED', 'EXPIRED']),
        insurerId: zod.string().nullable(),
        insurerName: zod.string().nullable(),
      })
      .nullable(),
    insurerId: zod.string().nullable(),
    deletedAt: zod.string().datetime({}).nullable(),
    createdAt: zod.string().datetime({}),
    updatedAt: zod.string().datetime({}),
    coverageStartDate: zod.string().datetime({}).nullable(),
    coverageEndDate: zod.string().datetime({}).nullable(),
    sentToClientAt: zod.string().datetime({}).nullable(),
    clientResponseAt: zod.string().datetime({}).nullable(),
    quoteValidUntil: zod.string().datetime({}).nullable(),
    clientName: zod.string().optional(),
    clientDocument: zod.string().optional(),
    clientPersonType: zod.string().optional(),
    salespersonName: zod.string().optional(),
    insurerName: zod.string().optional(),
  }),
})

/**
 * @summary Create a new proposal
 */

export const CreateProposalBody = zod.union([
  zod.object({
    contactId: zod.string().min(1),
    branch: zod.enum([
      'AUTO',
      'RESIDENTIAL',
      'CONDOMINIUM',
      'BUSINESS',
      'LIFE',
      'OTHER',
    ]),
    boardType: zod.enum(['NEW_INSURANCE', 'RENEWAL']),
    renewalPolicyId: zod.string().optional(),
    renewalPolicyNumber: zod.string().optional(),
    insurerId: zod.string().optional(),
  }),
  zod.object({
    boardType: zod.enum(['ENDORSEMENT']),
    sourcePolicyId: zod.string().min(1),
    endorsementType: zod.string().min(1),
    endorsementReason: zod.string().min(1),
  }),
])

/**
 * @summary List proposals with cursor pagination
 */
export const listProposalsQueryLimitDefault = 20
export const listProposalsQueryLimitMax = 100

export const listProposalsQuerySortByDefault = `createdAt`
export const listProposalsQuerySortOrderDefault = `desc`

export const ListProposalsQueryParams = zod.object({
  cursor: zod.string().optional(),
  limit: zod
    .number()
    .min(1)
    .max(listProposalsQueryLimitMax)
    .default(listProposalsQueryLimitDefault),
  stage: zod
    .enum([
      'CAPTURE',
      'QUOTE',
      'PROTOCOL',
      'INSPECTION',
      'PAYMENT',
      'POLICY_ISSUED',
      'LOST',
    ])
    .optional(),
  contactId: zod.string().optional(),
  clientId: zod.string().optional(),
  salespersonId: zod.string().optional(),
  insurerId: zod.string().optional(),
  sourcePolicyId: zod.string().optional(),
  boardType: zod.enum(['NEW_INSURANCE', 'RENEWAL', 'ENDORSEMENT']).optional(),
  stageIn: zod.string().optional(),
  branchIn: zod.string().optional(),
  salespersonIdIn: zod.string().optional(),
  createdFrom: zod.string().datetime({}).optional(),
  createdTo: zod.string().datetime({}).optional(),
  updatedAtFrom: zod.string().datetime({}).optional(),
  updatedAtTo: zod.string().datetime({}).optional(),
  search: zod.string().optional(),
  sortBy: zod
    .enum([
      'clientName',
      'branch',
      'stage',
      'boardType',
      'premiumValueInCents',
      'createdAt',
    ])
    .default(listProposalsQuerySortByDefault),
  sortOrder: zod
    .enum(['asc', 'desc'])
    .default(listProposalsQuerySortOrderDefault),
})

export const listProposalsResponseDataItemDetailsOneManufacturingYearMin = 1900
export const listProposalsResponseDataItemDetailsOneManufacturingYearMax = 2100

export const listProposalsResponseDataItemDetailsOneModelYearMin = 1900
export const listProposalsResponseDataItemDetailsOneModelYearMax = 2100

export const listProposalsResponseDataItemDetailsTwoStateMin = 2
export const listProposalsResponseDataItemDetailsTwoStateMax = 2

export const listProposalsResponseDataItemDetailsThreeStateMin = 2
export const listProposalsResponseDataItemDetailsThreeStateMax = 2

export const listProposalsResponseDataItemDetailsFourStateMin = 2
export const listProposalsResponseDataItemDetailsFourStateMax = 2

export const listProposalsResponseDataItemDetailsFiveMonthlyIncomeCentsMin = 0

export const listProposalsResponseDataItemDetailsFiveHeightInCentimetersMin = 100
export const listProposalsResponseDataItemDetailsFiveHeightInCentimetersMax = 250

export const listProposalsResponseDataItemDetailsFiveWeightInGramsMin = 20000
export const listProposalsResponseDataItemDetailsFiveWeightInGramsMax = 300000

export const ListProposalsResponse = zod.object({
  success: zod.literal(true),
  data: zod.array(
    zod.object({
      id: zod.string(),
      organizationId: zod.string(),
      contactId: zod.string(),
      salespersonId: zod.string(),
      stage: zod.enum([
        'CAPTURE',
        'QUOTE',
        'PROTOCOL',
        'INSPECTION',
        'PAYMENT',
        'POLICY_ISSUED',
        'LOST',
      ]),
      boardType: zod.enum(['NEW_INSURANCE', 'RENEWAL', 'ENDORSEMENT']),
      branch: zod.enum([
        'AUTO',
        'RESIDENTIAL',
        'CONDOMINIUM',
        'BUSINESS',
        'LIFE',
        'OTHER',
      ]),
      premiumValueInCents: zod.number(),
      commissionPercentageInCents: zod.number(),
      details: zod
        .union([
          zod.object({
            branch: zod.enum(['AUTO']),
            brand: zod.string().min(1),
            model: zod.string().min(1),
            manufacturingYear: zod
              .number()
              .min(listProposalsResponseDataItemDetailsOneManufacturingYearMin)
              .max(listProposalsResponseDataItemDetailsOneManufacturingYearMax),
            modelYear: zod
              .number()
              .min(listProposalsResponseDataItemDetailsOneModelYearMin)
              .max(listProposalsResponseDataItemDetailsOneModelYearMax),
            licensePlate: zod.string().optional(),
            vin: zod.string().optional(),
            color: zod.string().optional(),
            fuelType: zod.string().optional(),
            vehicleUsage: zod.string().optional(),
          }),
          zod.object({
            branch: zod.enum(['RESIDENTIAL']),
            propertyType: zod.string().min(1),
            propertyUsage: zod.string().min(1),
            cep: zod.string().min(1),
            street: zod.string().optional(),
            number: zod.string().optional(),
            complement: zod.string().optional(),
            neighborhood: zod.string().optional(),
            city: zod.string().optional(),
            state: zod
              .string()
              .min(listProposalsResponseDataItemDetailsTwoStateMin)
              .max(listProposalsResponseDataItemDetailsTwoStateMax)
              .optional(),
            construction: zod.string().optional(),
            areaM2: zod.number().optional(),
          }),
          zod.object({
            branch: zod.enum(['CONDOMINIUM']),
            condominiumName: zod.string().min(1),
            unitCount: zod.number().min(1),
            cep: zod.string().min(1),
            street: zod.string().optional(),
            number: zod.string().optional(),
            complement: zod.string().optional(),
            neighborhood: zod.string().optional(),
            city: zod.string().optional(),
            state: zod
              .string()
              .min(listProposalsResponseDataItemDetailsThreeStateMin)
              .max(listProposalsResponseDataItemDetailsThreeStateMax)
              .optional(),
            constructionYear: zod.number().optional(),
            floorCount: zod.number().optional(),
            blockCount: zod.number().optional(),
            elevatorCount: zod.number().optional(),
            employeeCount: zod.number().optional(),
            hasSecurityEquipment: zod.boolean().optional(),
            securityEquipmentDetails: zod.string().optional(),
            hasFireEquipment: zod.boolean().optional(),
            fireEquipmentDetails: zod.string().optional(),
          }),
          zod.object({
            branch: zod.enum(['BUSINESS']),
            legalName: zod.string().min(1),
            cnpj: zod.string().min(1),
            businessActivity: zod.string().min(1),
            cep: zod.string().optional(),
            street: zod.string().optional(),
            number: zod.string().optional(),
            complement: zod.string().optional(),
            neighborhood: zod.string().optional(),
            city: zod.string().optional(),
            state: zod
              .string()
              .min(listProposalsResponseDataItemDetailsFourStateMin)
              .max(listProposalsResponseDataItemDetailsFourStateMax)
              .optional(),
            areaM2: zod.number().optional(),
          }),
          zod.object({
            branch: zod.enum(['LIFE']),
            occupation: zod.string().min(1),
            monthlyIncomeCents: zod
              .number()
              .min(
                listProposalsResponseDataItemDetailsFiveMonthlyIncomeCentsMin
              )
              .optional(),
            isSmoker: zod.boolean().optional(),
            extremeSports: zod.boolean().optional(),
            heightInCentimeters: zod
              .number()
              .min(
                listProposalsResponseDataItemDetailsFiveHeightInCentimetersMin
              )
              .max(
                listProposalsResponseDataItemDetailsFiveHeightInCentimetersMax
              )
              .optional(),
            weightInGrams: zod
              .number()
              .min(listProposalsResponseDataItemDetailsFiveWeightInGramsMin)
              .max(listProposalsResponseDataItemDetailsFiveWeightInGramsMax)
              .optional(),
            beneficiaries: zod.string().optional(),
          }),
          zod.object({
            branch: zod.enum(['OTHER']),
            description: zod.string().min(1),
          }),
        ])
        .nullable(),
      lostReason: zod.string().nullable(),
      observations: zod.string().nullable(),
      renewalPolicyId: zod.string().nullable(),
      renewalPolicyNumber: zod.string().nullable(),
      sourcePolicyId: zod.string().nullable(),
      endorsementType: zod.string().nullable(),
      endorsementReason: zod.string().nullable(),
      sourcePolicySnapshot: zod
        .object({
          policyNumber: zod.string(),
          clientName: zod.string(),
          startDate: zod.string().datetime({}),
          endDate: zod.string().datetime({}),
          status: zod.enum(['ACTIVE', 'CANCELLED', 'EXPIRED']),
          insurerId: zod.string().nullable(),
          insurerName: zod.string().nullable(),
        })
        .nullable(),
      insurerId: zod.string().nullable(),
      deletedAt: zod.string().datetime({}).nullable(),
      createdAt: zod.string().datetime({}),
      updatedAt: zod.string().datetime({}),
      coverageStartDate: zod.string().datetime({}).nullable(),
      coverageEndDate: zod.string().datetime({}).nullable(),
      sentToClientAt: zod.string().datetime({}).nullable(),
      clientResponseAt: zod.string().datetime({}).nullable(),
      quoteValidUntil: zod.string().datetime({}).nullable(),
      clientName: zod.string().optional(),
      clientDocument: zod.string().optional(),
      clientPersonType: zod.string().optional(),
      salespersonName: zod.string().optional(),
      insurerName: zod.string().optional(),
    })
  ),
  meta: zod.object({
    nextCursor: zod.string().nullable(),
  }),
})

/**
 * @summary Get a proposal by ID
 */

export const GetProposalParams = zod.object({
  id: zod.string().min(1),
})

export const getProposalResponseDataDetailsOneManufacturingYearMin = 1900
export const getProposalResponseDataDetailsOneManufacturingYearMax = 2100

export const getProposalResponseDataDetailsOneModelYearMin = 1900
export const getProposalResponseDataDetailsOneModelYearMax = 2100

export const getProposalResponseDataDetailsTwoStateMin = 2
export const getProposalResponseDataDetailsTwoStateMax = 2

export const getProposalResponseDataDetailsThreeStateMin = 2
export const getProposalResponseDataDetailsThreeStateMax = 2

export const getProposalResponseDataDetailsFourStateMin = 2
export const getProposalResponseDataDetailsFourStateMax = 2

export const getProposalResponseDataDetailsFiveMonthlyIncomeCentsMin = 0

export const getProposalResponseDataDetailsFiveHeightInCentimetersMin = 100
export const getProposalResponseDataDetailsFiveHeightInCentimetersMax = 250

export const getProposalResponseDataDetailsFiveWeightInGramsMin = 20000
export const getProposalResponseDataDetailsFiveWeightInGramsMax = 300000

export const GetProposalResponse = zod.object({
  success: zod.literal(true),
  data: zod.object({
    id: zod.string(),
    organizationId: zod.string(),
    contactId: zod.string(),
    salespersonId: zod.string(),
    stage: zod.enum([
      'CAPTURE',
      'QUOTE',
      'PROTOCOL',
      'INSPECTION',
      'PAYMENT',
      'POLICY_ISSUED',
      'LOST',
    ]),
    boardType: zod.enum(['NEW_INSURANCE', 'RENEWAL', 'ENDORSEMENT']),
    branch: zod.enum([
      'AUTO',
      'RESIDENTIAL',
      'CONDOMINIUM',
      'BUSINESS',
      'LIFE',
      'OTHER',
    ]),
    premiumValueInCents: zod.number(),
    commissionPercentageInCents: zod.number(),
    details: zod
      .union([
        zod.object({
          branch: zod.enum(['AUTO']),
          brand: zod.string().min(1),
          model: zod.string().min(1),
          manufacturingYear: zod
            .number()
            .min(getProposalResponseDataDetailsOneManufacturingYearMin)
            .max(getProposalResponseDataDetailsOneManufacturingYearMax),
          modelYear: zod
            .number()
            .min(getProposalResponseDataDetailsOneModelYearMin)
            .max(getProposalResponseDataDetailsOneModelYearMax),
          licensePlate: zod.string().optional(),
          vin: zod.string().optional(),
          color: zod.string().optional(),
          fuelType: zod.string().optional(),
          vehicleUsage: zod.string().optional(),
        }),
        zod.object({
          branch: zod.enum(['RESIDENTIAL']),
          propertyType: zod.string().min(1),
          propertyUsage: zod.string().min(1),
          cep: zod.string().min(1),
          street: zod.string().optional(),
          number: zod.string().optional(),
          complement: zod.string().optional(),
          neighborhood: zod.string().optional(),
          city: zod.string().optional(),
          state: zod
            .string()
            .min(getProposalResponseDataDetailsTwoStateMin)
            .max(getProposalResponseDataDetailsTwoStateMax)
            .optional(),
          construction: zod.string().optional(),
          areaM2: zod.number().optional(),
        }),
        zod.object({
          branch: zod.enum(['CONDOMINIUM']),
          condominiumName: zod.string().min(1),
          unitCount: zod.number().min(1),
          cep: zod.string().min(1),
          street: zod.string().optional(),
          number: zod.string().optional(),
          complement: zod.string().optional(),
          neighborhood: zod.string().optional(),
          city: zod.string().optional(),
          state: zod
            .string()
            .min(getProposalResponseDataDetailsThreeStateMin)
            .max(getProposalResponseDataDetailsThreeStateMax)
            .optional(),
          constructionYear: zod.number().optional(),
          floorCount: zod.number().optional(),
          blockCount: zod.number().optional(),
          elevatorCount: zod.number().optional(),
          employeeCount: zod.number().optional(),
          hasSecurityEquipment: zod.boolean().optional(),
          securityEquipmentDetails: zod.string().optional(),
          hasFireEquipment: zod.boolean().optional(),
          fireEquipmentDetails: zod.string().optional(),
        }),
        zod.object({
          branch: zod.enum(['BUSINESS']),
          legalName: zod.string().min(1),
          cnpj: zod.string().min(1),
          businessActivity: zod.string().min(1),
          cep: zod.string().optional(),
          street: zod.string().optional(),
          number: zod.string().optional(),
          complement: zod.string().optional(),
          neighborhood: zod.string().optional(),
          city: zod.string().optional(),
          state: zod
            .string()
            .min(getProposalResponseDataDetailsFourStateMin)
            .max(getProposalResponseDataDetailsFourStateMax)
            .optional(),
          areaM2: zod.number().optional(),
        }),
        zod.object({
          branch: zod.enum(['LIFE']),
          occupation: zod.string().min(1),
          monthlyIncomeCents: zod
            .number()
            .min(getProposalResponseDataDetailsFiveMonthlyIncomeCentsMin)
            .optional(),
          isSmoker: zod.boolean().optional(),
          extremeSports: zod.boolean().optional(),
          heightInCentimeters: zod
            .number()
            .min(getProposalResponseDataDetailsFiveHeightInCentimetersMin)
            .max(getProposalResponseDataDetailsFiveHeightInCentimetersMax)
            .optional(),
          weightInGrams: zod
            .number()
            .min(getProposalResponseDataDetailsFiveWeightInGramsMin)
            .max(getProposalResponseDataDetailsFiveWeightInGramsMax)
            .optional(),
          beneficiaries: zod.string().optional(),
        }),
        zod.object({
          branch: zod.enum(['OTHER']),
          description: zod.string().min(1),
        }),
      ])
      .nullable(),
    lostReason: zod.string().nullable(),
    observations: zod.string().nullable(),
    renewalPolicyId: zod.string().nullable(),
    renewalPolicyNumber: zod.string().nullable(),
    sourcePolicyId: zod.string().nullable(),
    endorsementType: zod.string().nullable(),
    endorsementReason: zod.string().nullable(),
    sourcePolicySnapshot: zod
      .object({
        policyNumber: zod.string(),
        clientName: zod.string(),
        startDate: zod.string().datetime({}),
        endDate: zod.string().datetime({}),
        status: zod.enum(['ACTIVE', 'CANCELLED', 'EXPIRED']),
        insurerId: zod.string().nullable(),
        insurerName: zod.string().nullable(),
      })
      .nullable(),
    insurerId: zod.string().nullable(),
    deletedAt: zod.string().datetime({}).nullable(),
    createdAt: zod.string().datetime({}),
    updatedAt: zod.string().datetime({}),
    coverageStartDate: zod.string().datetime({}).nullable(),
    coverageEndDate: zod.string().datetime({}).nullable(),
    sentToClientAt: zod.string().datetime({}).nullable(),
    clientResponseAt: zod.string().datetime({}).nullable(),
    quoteValidUntil: zod.string().datetime({}).nullable(),
    clientName: zod.string().optional(),
    clientDocument: zod.string().optional(),
    clientPersonType: zod.string().optional(),
    salespersonName: zod.string().optional(),
    insurerName: zod.string().optional(),
  }),
})

/**
 * @summary Advance proposal to next stage
 */

export const AdvanceProposalParams = zod.object({
  id: zod.string().min(1),
})

export const advanceProposalResponseDataDetailsOneManufacturingYearMin = 1900
export const advanceProposalResponseDataDetailsOneManufacturingYearMax = 2100

export const advanceProposalResponseDataDetailsOneModelYearMin = 1900
export const advanceProposalResponseDataDetailsOneModelYearMax = 2100

export const advanceProposalResponseDataDetailsTwoStateMin = 2
export const advanceProposalResponseDataDetailsTwoStateMax = 2

export const advanceProposalResponseDataDetailsThreeStateMin = 2
export const advanceProposalResponseDataDetailsThreeStateMax = 2

export const advanceProposalResponseDataDetailsFourStateMin = 2
export const advanceProposalResponseDataDetailsFourStateMax = 2

export const advanceProposalResponseDataDetailsFiveMonthlyIncomeCentsMin = 0

export const advanceProposalResponseDataDetailsFiveHeightInCentimetersMin = 100
export const advanceProposalResponseDataDetailsFiveHeightInCentimetersMax = 250

export const advanceProposalResponseDataDetailsFiveWeightInGramsMin = 20000
export const advanceProposalResponseDataDetailsFiveWeightInGramsMax = 300000

export const AdvanceProposalResponse = zod.object({
  success: zod.literal(true),
  data: zod.object({
    id: zod.string(),
    organizationId: zod.string(),
    contactId: zod.string(),
    salespersonId: zod.string(),
    stage: zod.enum([
      'CAPTURE',
      'QUOTE',
      'PROTOCOL',
      'INSPECTION',
      'PAYMENT',
      'POLICY_ISSUED',
      'LOST',
    ]),
    boardType: zod.enum(['NEW_INSURANCE', 'RENEWAL', 'ENDORSEMENT']),
    branch: zod.enum([
      'AUTO',
      'RESIDENTIAL',
      'CONDOMINIUM',
      'BUSINESS',
      'LIFE',
      'OTHER',
    ]),
    premiumValueInCents: zod.number(),
    commissionPercentageInCents: zod.number(),
    details: zod
      .union([
        zod.object({
          branch: zod.enum(['AUTO']),
          brand: zod.string().min(1),
          model: zod.string().min(1),
          manufacturingYear: zod
            .number()
            .min(advanceProposalResponseDataDetailsOneManufacturingYearMin)
            .max(advanceProposalResponseDataDetailsOneManufacturingYearMax),
          modelYear: zod
            .number()
            .min(advanceProposalResponseDataDetailsOneModelYearMin)
            .max(advanceProposalResponseDataDetailsOneModelYearMax),
          licensePlate: zod.string().optional(),
          vin: zod.string().optional(),
          color: zod.string().optional(),
          fuelType: zod.string().optional(),
          vehicleUsage: zod.string().optional(),
        }),
        zod.object({
          branch: zod.enum(['RESIDENTIAL']),
          propertyType: zod.string().min(1),
          propertyUsage: zod.string().min(1),
          cep: zod.string().min(1),
          street: zod.string().optional(),
          number: zod.string().optional(),
          complement: zod.string().optional(),
          neighborhood: zod.string().optional(),
          city: zod.string().optional(),
          state: zod
            .string()
            .min(advanceProposalResponseDataDetailsTwoStateMin)
            .max(advanceProposalResponseDataDetailsTwoStateMax)
            .optional(),
          construction: zod.string().optional(),
          areaM2: zod.number().optional(),
        }),
        zod.object({
          branch: zod.enum(['CONDOMINIUM']),
          condominiumName: zod.string().min(1),
          unitCount: zod.number().min(1),
          cep: zod.string().min(1),
          street: zod.string().optional(),
          number: zod.string().optional(),
          complement: zod.string().optional(),
          neighborhood: zod.string().optional(),
          city: zod.string().optional(),
          state: zod
            .string()
            .min(advanceProposalResponseDataDetailsThreeStateMin)
            .max(advanceProposalResponseDataDetailsThreeStateMax)
            .optional(),
          constructionYear: zod.number().optional(),
          floorCount: zod.number().optional(),
          blockCount: zod.number().optional(),
          elevatorCount: zod.number().optional(),
          employeeCount: zod.number().optional(),
          hasSecurityEquipment: zod.boolean().optional(),
          securityEquipmentDetails: zod.string().optional(),
          hasFireEquipment: zod.boolean().optional(),
          fireEquipmentDetails: zod.string().optional(),
        }),
        zod.object({
          branch: zod.enum(['BUSINESS']),
          legalName: zod.string().min(1),
          cnpj: zod.string().min(1),
          businessActivity: zod.string().min(1),
          cep: zod.string().optional(),
          street: zod.string().optional(),
          number: zod.string().optional(),
          complement: zod.string().optional(),
          neighborhood: zod.string().optional(),
          city: zod.string().optional(),
          state: zod
            .string()
            .min(advanceProposalResponseDataDetailsFourStateMin)
            .max(advanceProposalResponseDataDetailsFourStateMax)
            .optional(),
          areaM2: zod.number().optional(),
        }),
        zod.object({
          branch: zod.enum(['LIFE']),
          occupation: zod.string().min(1),
          monthlyIncomeCents: zod
            .number()
            .min(advanceProposalResponseDataDetailsFiveMonthlyIncomeCentsMin)
            .optional(),
          isSmoker: zod.boolean().optional(),
          extremeSports: zod.boolean().optional(),
          heightInCentimeters: zod
            .number()
            .min(advanceProposalResponseDataDetailsFiveHeightInCentimetersMin)
            .max(advanceProposalResponseDataDetailsFiveHeightInCentimetersMax)
            .optional(),
          weightInGrams: zod
            .number()
            .min(advanceProposalResponseDataDetailsFiveWeightInGramsMin)
            .max(advanceProposalResponseDataDetailsFiveWeightInGramsMax)
            .optional(),
          beneficiaries: zod.string().optional(),
        }),
        zod.object({
          branch: zod.enum(['OTHER']),
          description: zod.string().min(1),
        }),
      ])
      .nullable(),
    lostReason: zod.string().nullable(),
    observations: zod.string().nullable(),
    renewalPolicyId: zod.string().nullable(),
    renewalPolicyNumber: zod.string().nullable(),
    sourcePolicyId: zod.string().nullable(),
    endorsementType: zod.string().nullable(),
    endorsementReason: zod.string().nullable(),
    sourcePolicySnapshot: zod
      .object({
        policyNumber: zod.string(),
        clientName: zod.string(),
        startDate: zod.string().datetime({}),
        endDate: zod.string().datetime({}),
        status: zod.enum(['ACTIVE', 'CANCELLED', 'EXPIRED']),
        insurerId: zod.string().nullable(),
        insurerName: zod.string().nullable(),
      })
      .nullable(),
    insurerId: zod.string().nullable(),
    deletedAt: zod.string().datetime({}).nullable(),
    createdAt: zod.string().datetime({}),
    updatedAt: zod.string().datetime({}),
    coverageStartDate: zod.string().datetime({}).nullable(),
    coverageEndDate: zod.string().datetime({}).nullable(),
    sentToClientAt: zod.string().datetime({}).nullable(),
    clientResponseAt: zod.string().datetime({}).nullable(),
    quoteValidUntil: zod.string().datetime({}).nullable(),
    clientName: zod.string().optional(),
    clientDocument: zod.string().optional(),
    clientPersonType: zod.string().optional(),
    salespersonName: zod.string().optional(),
    insurerName: zod.string().optional(),
  }),
})

/**
 * @summary Mark proposal as lost
 */

export const MarkProposalLostParams = zod.object({
  id: zod.string().min(1),
})

export const MarkProposalLostBody = zod.object({
  reason: zod.string().min(1),
})

export const markProposalLostResponseDataDetailsOneManufacturingYearMin = 1900
export const markProposalLostResponseDataDetailsOneManufacturingYearMax = 2100

export const markProposalLostResponseDataDetailsOneModelYearMin = 1900
export const markProposalLostResponseDataDetailsOneModelYearMax = 2100

export const markProposalLostResponseDataDetailsTwoStateMin = 2
export const markProposalLostResponseDataDetailsTwoStateMax = 2

export const markProposalLostResponseDataDetailsThreeStateMin = 2
export const markProposalLostResponseDataDetailsThreeStateMax = 2

export const markProposalLostResponseDataDetailsFourStateMin = 2
export const markProposalLostResponseDataDetailsFourStateMax = 2

export const markProposalLostResponseDataDetailsFiveMonthlyIncomeCentsMin = 0

export const markProposalLostResponseDataDetailsFiveHeightInCentimetersMin = 100
export const markProposalLostResponseDataDetailsFiveHeightInCentimetersMax = 250

export const markProposalLostResponseDataDetailsFiveWeightInGramsMin = 20000
export const markProposalLostResponseDataDetailsFiveWeightInGramsMax = 300000

export const MarkProposalLostResponse = zod.object({
  success: zod.literal(true),
  data: zod.object({
    id: zod.string(),
    organizationId: zod.string(),
    contactId: zod.string(),
    salespersonId: zod.string(),
    stage: zod.enum([
      'CAPTURE',
      'QUOTE',
      'PROTOCOL',
      'INSPECTION',
      'PAYMENT',
      'POLICY_ISSUED',
      'LOST',
    ]),
    boardType: zod.enum(['NEW_INSURANCE', 'RENEWAL', 'ENDORSEMENT']),
    branch: zod.enum([
      'AUTO',
      'RESIDENTIAL',
      'CONDOMINIUM',
      'BUSINESS',
      'LIFE',
      'OTHER',
    ]),
    premiumValueInCents: zod.number(),
    commissionPercentageInCents: zod.number(),
    details: zod
      .union([
        zod.object({
          branch: zod.enum(['AUTO']),
          brand: zod.string().min(1),
          model: zod.string().min(1),
          manufacturingYear: zod
            .number()
            .min(markProposalLostResponseDataDetailsOneManufacturingYearMin)
            .max(markProposalLostResponseDataDetailsOneManufacturingYearMax),
          modelYear: zod
            .number()
            .min(markProposalLostResponseDataDetailsOneModelYearMin)
            .max(markProposalLostResponseDataDetailsOneModelYearMax),
          licensePlate: zod.string().optional(),
          vin: zod.string().optional(),
          color: zod.string().optional(),
          fuelType: zod.string().optional(),
          vehicleUsage: zod.string().optional(),
        }),
        zod.object({
          branch: zod.enum(['RESIDENTIAL']),
          propertyType: zod.string().min(1),
          propertyUsage: zod.string().min(1),
          cep: zod.string().min(1),
          street: zod.string().optional(),
          number: zod.string().optional(),
          complement: zod.string().optional(),
          neighborhood: zod.string().optional(),
          city: zod.string().optional(),
          state: zod
            .string()
            .min(markProposalLostResponseDataDetailsTwoStateMin)
            .max(markProposalLostResponseDataDetailsTwoStateMax)
            .optional(),
          construction: zod.string().optional(),
          areaM2: zod.number().optional(),
        }),
        zod.object({
          branch: zod.enum(['CONDOMINIUM']),
          condominiumName: zod.string().min(1),
          unitCount: zod.number().min(1),
          cep: zod.string().min(1),
          street: zod.string().optional(),
          number: zod.string().optional(),
          complement: zod.string().optional(),
          neighborhood: zod.string().optional(),
          city: zod.string().optional(),
          state: zod
            .string()
            .min(markProposalLostResponseDataDetailsThreeStateMin)
            .max(markProposalLostResponseDataDetailsThreeStateMax)
            .optional(),
          constructionYear: zod.number().optional(),
          floorCount: zod.number().optional(),
          blockCount: zod.number().optional(),
          elevatorCount: zod.number().optional(),
          employeeCount: zod.number().optional(),
          hasSecurityEquipment: zod.boolean().optional(),
          securityEquipmentDetails: zod.string().optional(),
          hasFireEquipment: zod.boolean().optional(),
          fireEquipmentDetails: zod.string().optional(),
        }),
        zod.object({
          branch: zod.enum(['BUSINESS']),
          legalName: zod.string().min(1),
          cnpj: zod.string().min(1),
          businessActivity: zod.string().min(1),
          cep: zod.string().optional(),
          street: zod.string().optional(),
          number: zod.string().optional(),
          complement: zod.string().optional(),
          neighborhood: zod.string().optional(),
          city: zod.string().optional(),
          state: zod
            .string()
            .min(markProposalLostResponseDataDetailsFourStateMin)
            .max(markProposalLostResponseDataDetailsFourStateMax)
            .optional(),
          areaM2: zod.number().optional(),
        }),
        zod.object({
          branch: zod.enum(['LIFE']),
          occupation: zod.string().min(1),
          monthlyIncomeCents: zod
            .number()
            .min(markProposalLostResponseDataDetailsFiveMonthlyIncomeCentsMin)
            .optional(),
          isSmoker: zod.boolean().optional(),
          extremeSports: zod.boolean().optional(),
          heightInCentimeters: zod
            .number()
            .min(markProposalLostResponseDataDetailsFiveHeightInCentimetersMin)
            .max(markProposalLostResponseDataDetailsFiveHeightInCentimetersMax)
            .optional(),
          weightInGrams: zod
            .number()
            .min(markProposalLostResponseDataDetailsFiveWeightInGramsMin)
            .max(markProposalLostResponseDataDetailsFiveWeightInGramsMax)
            .optional(),
          beneficiaries: zod.string().optional(),
        }),
        zod.object({
          branch: zod.enum(['OTHER']),
          description: zod.string().min(1),
        }),
      ])
      .nullable(),
    lostReason: zod.string().nullable(),
    observations: zod.string().nullable(),
    renewalPolicyId: zod.string().nullable(),
    renewalPolicyNumber: zod.string().nullable(),
    sourcePolicyId: zod.string().nullable(),
    endorsementType: zod.string().nullable(),
    endorsementReason: zod.string().nullable(),
    sourcePolicySnapshot: zod
      .object({
        policyNumber: zod.string(),
        clientName: zod.string(),
        startDate: zod.string().datetime({}),
        endDate: zod.string().datetime({}),
        status: zod.enum(['ACTIVE', 'CANCELLED', 'EXPIRED']),
        insurerId: zod.string().nullable(),
        insurerName: zod.string().nullable(),
      })
      .nullable(),
    insurerId: zod.string().nullable(),
    deletedAt: zod.string().datetime({}).nullable(),
    createdAt: zod.string().datetime({}),
    updatedAt: zod.string().datetime({}),
    coverageStartDate: zod.string().datetime({}).nullable(),
    coverageEndDate: zod.string().datetime({}).nullable(),
    sentToClientAt: zod.string().datetime({}).nullable(),
    clientResponseAt: zod.string().datetime({}).nullable(),
    quoteValidUntil: zod.string().datetime({}).nullable(),
    clientName: zod.string().optional(),
    clientDocument: zod.string().optional(),
    clientPersonType: zod.string().optional(),
    salespersonName: zod.string().optional(),
    insurerName: zod.string().optional(),
  }),
})

/**
 * @summary Reopen a lost proposal
 */

export const ReopenProposalParams = zod.object({
  id: zod.string().min(1),
})

export const ReopenProposalResponse = zod.object({
  success: zod.literal(true),
  data: zod.enum(['null']).nullable(),
})

/**
 * @summary Update proposal insured object details
 */

export const UpdateProposalDetailsParams = zod.object({
  id: zod.string().min(1),
})

export const updateProposalDetailsBodyDetailsOneManufacturingYearMin = 1900
export const updateProposalDetailsBodyDetailsOneManufacturingYearMax = 2100

export const updateProposalDetailsBodyDetailsOneModelYearMin = 1900
export const updateProposalDetailsBodyDetailsOneModelYearMax = 2100

export const updateProposalDetailsBodyDetailsTwoStateMin = 2
export const updateProposalDetailsBodyDetailsTwoStateMax = 2

export const updateProposalDetailsBodyDetailsThreeStateMin = 2
export const updateProposalDetailsBodyDetailsThreeStateMax = 2

export const updateProposalDetailsBodyDetailsFourStateMin = 2
export const updateProposalDetailsBodyDetailsFourStateMax = 2

export const updateProposalDetailsBodyDetailsFiveMonthlyIncomeCentsMin = 0

export const updateProposalDetailsBodyDetailsFiveHeightInCentimetersMin = 100
export const updateProposalDetailsBodyDetailsFiveHeightInCentimetersMax = 250

export const updateProposalDetailsBodyDetailsFiveWeightInGramsMin = 20000
export const updateProposalDetailsBodyDetailsFiveWeightInGramsMax = 300000

export const updateProposalDetailsBodyPremiumValueInCentsMin = 0

export const updateProposalDetailsBodyCommissionBasisPointsMin = 0
export const updateProposalDetailsBodyCommissionBasisPointsMax = 10000

export const UpdateProposalDetailsBody = zod.object({
  details: zod.union([
    zod.object({
      branch: zod.enum(['AUTO']),
      brand: zod.string().min(1),
      model: zod.string().min(1),
      manufacturingYear: zod
        .number()
        .min(updateProposalDetailsBodyDetailsOneManufacturingYearMin)
        .max(updateProposalDetailsBodyDetailsOneManufacturingYearMax),
      modelYear: zod
        .number()
        .min(updateProposalDetailsBodyDetailsOneModelYearMin)
        .max(updateProposalDetailsBodyDetailsOneModelYearMax),
      licensePlate: zod.string().optional(),
      vin: zod.string().optional(),
      color: zod.string().optional(),
      fuelType: zod.string().optional(),
      vehicleUsage: zod.string().optional(),
    }),
    zod.object({
      branch: zod.enum(['RESIDENTIAL']),
      propertyType: zod.string().min(1),
      propertyUsage: zod.string().min(1),
      cep: zod.string().min(1),
      street: zod.string().optional(),
      number: zod.string().optional(),
      complement: zod.string().optional(),
      neighborhood: zod.string().optional(),
      city: zod.string().optional(),
      state: zod
        .string()
        .min(updateProposalDetailsBodyDetailsTwoStateMin)
        .max(updateProposalDetailsBodyDetailsTwoStateMax)
        .optional(),
      construction: zod.string().optional(),
      areaM2: zod.number().optional(),
    }),
    zod.object({
      branch: zod.enum(['CONDOMINIUM']),
      condominiumName: zod.string().min(1),
      unitCount: zod.number().min(1),
      cep: zod.string().min(1),
      street: zod.string().optional(),
      number: zod.string().optional(),
      complement: zod.string().optional(),
      neighborhood: zod.string().optional(),
      city: zod.string().optional(),
      state: zod
        .string()
        .min(updateProposalDetailsBodyDetailsThreeStateMin)
        .max(updateProposalDetailsBodyDetailsThreeStateMax)
        .optional(),
      constructionYear: zod.number().optional(),
      floorCount: zod.number().optional(),
      blockCount: zod.number().optional(),
      elevatorCount: zod.number().optional(),
      employeeCount: zod.number().optional(),
      hasSecurityEquipment: zod.boolean().optional(),
      securityEquipmentDetails: zod.string().optional(),
      hasFireEquipment: zod.boolean().optional(),
      fireEquipmentDetails: zod.string().optional(),
    }),
    zod.object({
      branch: zod.enum(['BUSINESS']),
      legalName: zod.string().min(1),
      cnpj: zod.string().min(1),
      businessActivity: zod.string().min(1),
      cep: zod.string().optional(),
      street: zod.string().optional(),
      number: zod.string().optional(),
      complement: zod.string().optional(),
      neighborhood: zod.string().optional(),
      city: zod.string().optional(),
      state: zod
        .string()
        .min(updateProposalDetailsBodyDetailsFourStateMin)
        .max(updateProposalDetailsBodyDetailsFourStateMax)
        .optional(),
      areaM2: zod.number().optional(),
    }),
    zod.object({
      branch: zod.enum(['LIFE']),
      occupation: zod.string().min(1),
      monthlyIncomeCents: zod
        .number()
        .min(updateProposalDetailsBodyDetailsFiveMonthlyIncomeCentsMin)
        .optional(),
      isSmoker: zod.boolean().optional(),
      extremeSports: zod.boolean().optional(),
      heightInCentimeters: zod
        .number()
        .min(updateProposalDetailsBodyDetailsFiveHeightInCentimetersMin)
        .max(updateProposalDetailsBodyDetailsFiveHeightInCentimetersMax)
        .optional(),
      weightInGrams: zod
        .number()
        .min(updateProposalDetailsBodyDetailsFiveWeightInGramsMin)
        .max(updateProposalDetailsBodyDetailsFiveWeightInGramsMax)
        .optional(),
      beneficiaries: zod.string().optional(),
    }),
    zod.object({
      branch: zod.enum(['OTHER']),
      description: zod.string().min(1),
    }),
  ]),
  premiumValueInCents: zod
    .number()
    .min(updateProposalDetailsBodyPremiumValueInCentsMin),
  commissionBasisPoints: zod
    .number()
    .min(updateProposalDetailsBodyCommissionBasisPointsMin)
    .max(updateProposalDetailsBodyCommissionBasisPointsMax),
  insurerId: zod.string().nullish(),
})

export const updateProposalDetailsResponseDataDetailsOneManufacturingYearMin = 1900
export const updateProposalDetailsResponseDataDetailsOneManufacturingYearMax = 2100

export const updateProposalDetailsResponseDataDetailsOneModelYearMin = 1900
export const updateProposalDetailsResponseDataDetailsOneModelYearMax = 2100

export const updateProposalDetailsResponseDataDetailsTwoStateMin = 2
export const updateProposalDetailsResponseDataDetailsTwoStateMax = 2

export const updateProposalDetailsResponseDataDetailsThreeStateMin = 2
export const updateProposalDetailsResponseDataDetailsThreeStateMax = 2

export const updateProposalDetailsResponseDataDetailsFourStateMin = 2
export const updateProposalDetailsResponseDataDetailsFourStateMax = 2

export const updateProposalDetailsResponseDataDetailsFiveMonthlyIncomeCentsMin = 0

export const updateProposalDetailsResponseDataDetailsFiveHeightInCentimetersMin = 100
export const updateProposalDetailsResponseDataDetailsFiveHeightInCentimetersMax = 250

export const updateProposalDetailsResponseDataDetailsFiveWeightInGramsMin = 20000
export const updateProposalDetailsResponseDataDetailsFiveWeightInGramsMax = 300000

export const UpdateProposalDetailsResponse = zod.object({
  success: zod.literal(true),
  data: zod.object({
    id: zod.string(),
    organizationId: zod.string(),
    contactId: zod.string(),
    salespersonId: zod.string(),
    stage: zod.enum([
      'CAPTURE',
      'QUOTE',
      'PROTOCOL',
      'INSPECTION',
      'PAYMENT',
      'POLICY_ISSUED',
      'LOST',
    ]),
    boardType: zod.enum(['NEW_INSURANCE', 'RENEWAL', 'ENDORSEMENT']),
    branch: zod.enum([
      'AUTO',
      'RESIDENTIAL',
      'CONDOMINIUM',
      'BUSINESS',
      'LIFE',
      'OTHER',
    ]),
    premiumValueInCents: zod.number(),
    commissionPercentageInCents: zod.number(),
    details: zod
      .union([
        zod.object({
          branch: zod.enum(['AUTO']),
          brand: zod.string().min(1),
          model: zod.string().min(1),
          manufacturingYear: zod
            .number()
            .min(
              updateProposalDetailsResponseDataDetailsOneManufacturingYearMin
            )
            .max(
              updateProposalDetailsResponseDataDetailsOneManufacturingYearMax
            ),
          modelYear: zod
            .number()
            .min(updateProposalDetailsResponseDataDetailsOneModelYearMin)
            .max(updateProposalDetailsResponseDataDetailsOneModelYearMax),
          licensePlate: zod.string().optional(),
          vin: zod.string().optional(),
          color: zod.string().optional(),
          fuelType: zod.string().optional(),
          vehicleUsage: zod.string().optional(),
        }),
        zod.object({
          branch: zod.enum(['RESIDENTIAL']),
          propertyType: zod.string().min(1),
          propertyUsage: zod.string().min(1),
          cep: zod.string().min(1),
          street: zod.string().optional(),
          number: zod.string().optional(),
          complement: zod.string().optional(),
          neighborhood: zod.string().optional(),
          city: zod.string().optional(),
          state: zod
            .string()
            .min(updateProposalDetailsResponseDataDetailsTwoStateMin)
            .max(updateProposalDetailsResponseDataDetailsTwoStateMax)
            .optional(),
          construction: zod.string().optional(),
          areaM2: zod.number().optional(),
        }),
        zod.object({
          branch: zod.enum(['CONDOMINIUM']),
          condominiumName: zod.string().min(1),
          unitCount: zod.number().min(1),
          cep: zod.string().min(1),
          street: zod.string().optional(),
          number: zod.string().optional(),
          complement: zod.string().optional(),
          neighborhood: zod.string().optional(),
          city: zod.string().optional(),
          state: zod
            .string()
            .min(updateProposalDetailsResponseDataDetailsThreeStateMin)
            .max(updateProposalDetailsResponseDataDetailsThreeStateMax)
            .optional(),
          constructionYear: zod.number().optional(),
          floorCount: zod.number().optional(),
          blockCount: zod.number().optional(),
          elevatorCount: zod.number().optional(),
          employeeCount: zod.number().optional(),
          hasSecurityEquipment: zod.boolean().optional(),
          securityEquipmentDetails: zod.string().optional(),
          hasFireEquipment: zod.boolean().optional(),
          fireEquipmentDetails: zod.string().optional(),
        }),
        zod.object({
          branch: zod.enum(['BUSINESS']),
          legalName: zod.string().min(1),
          cnpj: zod.string().min(1),
          businessActivity: zod.string().min(1),
          cep: zod.string().optional(),
          street: zod.string().optional(),
          number: zod.string().optional(),
          complement: zod.string().optional(),
          neighborhood: zod.string().optional(),
          city: zod.string().optional(),
          state: zod
            .string()
            .min(updateProposalDetailsResponseDataDetailsFourStateMin)
            .max(updateProposalDetailsResponseDataDetailsFourStateMax)
            .optional(),
          areaM2: zod.number().optional(),
        }),
        zod.object({
          branch: zod.enum(['LIFE']),
          occupation: zod.string().min(1),
          monthlyIncomeCents: zod
            .number()
            .min(
              updateProposalDetailsResponseDataDetailsFiveMonthlyIncomeCentsMin
            )
            .optional(),
          isSmoker: zod.boolean().optional(),
          extremeSports: zod.boolean().optional(),
          heightInCentimeters: zod
            .number()
            .min(
              updateProposalDetailsResponseDataDetailsFiveHeightInCentimetersMin
            )
            .max(
              updateProposalDetailsResponseDataDetailsFiveHeightInCentimetersMax
            )
            .optional(),
          weightInGrams: zod
            .number()
            .min(updateProposalDetailsResponseDataDetailsFiveWeightInGramsMin)
            .max(updateProposalDetailsResponseDataDetailsFiveWeightInGramsMax)
            .optional(),
          beneficiaries: zod.string().optional(),
        }),
        zod.object({
          branch: zod.enum(['OTHER']),
          description: zod.string().min(1),
        }),
      ])
      .nullable(),
    lostReason: zod.string().nullable(),
    observations: zod.string().nullable(),
    renewalPolicyId: zod.string().nullable(),
    renewalPolicyNumber: zod.string().nullable(),
    sourcePolicyId: zod.string().nullable(),
    endorsementType: zod.string().nullable(),
    endorsementReason: zod.string().nullable(),
    sourcePolicySnapshot: zod
      .object({
        policyNumber: zod.string(),
        clientName: zod.string(),
        startDate: zod.string().datetime({}),
        endDate: zod.string().datetime({}),
        status: zod.enum(['ACTIVE', 'CANCELLED', 'EXPIRED']),
        insurerId: zod.string().nullable(),
        insurerName: zod.string().nullable(),
      })
      .nullable(),
    insurerId: zod.string().nullable(),
    deletedAt: zod.string().datetime({}).nullable(),
    createdAt: zod.string().datetime({}),
    updatedAt: zod.string().datetime({}),
    coverageStartDate: zod.string().datetime({}).nullable(),
    coverageEndDate: zod.string().datetime({}).nullable(),
    sentToClientAt: zod.string().datetime({}).nullable(),
    clientResponseAt: zod.string().datetime({}).nullable(),
    quoteValidUntil: zod.string().datetime({}).nullable(),
    clientName: zod.string().optional(),
    clientDocument: zod.string().optional(),
    clientPersonType: zod.string().optional(),
    salespersonName: zod.string().optional(),
    insurerName: zod.string().optional(),
  }),
})

/**
 * @summary Update proposal observations
 */

export const UpdateProposalObservationsParams = zod.object({
  id: zod.string().min(1),
})

export const updateProposalObservationsBodyObservationsMax = 2000

export const UpdateProposalObservationsBody = zod.object({
  observations: zod
    .string()
    .max(updateProposalObservationsBodyObservationsMax)
    .nullable(),
})

export const updateProposalObservationsResponseDataDetailsOneManufacturingYearMin = 1900
export const updateProposalObservationsResponseDataDetailsOneManufacturingYearMax = 2100

export const updateProposalObservationsResponseDataDetailsOneModelYearMin = 1900
export const updateProposalObservationsResponseDataDetailsOneModelYearMax = 2100

export const updateProposalObservationsResponseDataDetailsTwoStateMin = 2
export const updateProposalObservationsResponseDataDetailsTwoStateMax = 2

export const updateProposalObservationsResponseDataDetailsThreeStateMin = 2
export const updateProposalObservationsResponseDataDetailsThreeStateMax = 2

export const updateProposalObservationsResponseDataDetailsFourStateMin = 2
export const updateProposalObservationsResponseDataDetailsFourStateMax = 2

export const updateProposalObservationsResponseDataDetailsFiveMonthlyIncomeCentsMin = 0

export const updateProposalObservationsResponseDataDetailsFiveHeightInCentimetersMin = 100
export const updateProposalObservationsResponseDataDetailsFiveHeightInCentimetersMax = 250

export const updateProposalObservationsResponseDataDetailsFiveWeightInGramsMin = 20000
export const updateProposalObservationsResponseDataDetailsFiveWeightInGramsMax = 300000

export const UpdateProposalObservationsResponse = zod.object({
  success: zod.literal(true),
  data: zod.object({
    id: zod.string(),
    organizationId: zod.string(),
    contactId: zod.string(),
    salespersonId: zod.string(),
    stage: zod.enum([
      'CAPTURE',
      'QUOTE',
      'PROTOCOL',
      'INSPECTION',
      'PAYMENT',
      'POLICY_ISSUED',
      'LOST',
    ]),
    boardType: zod.enum(['NEW_INSURANCE', 'RENEWAL', 'ENDORSEMENT']),
    branch: zod.enum([
      'AUTO',
      'RESIDENTIAL',
      'CONDOMINIUM',
      'BUSINESS',
      'LIFE',
      'OTHER',
    ]),
    premiumValueInCents: zod.number(),
    commissionPercentageInCents: zod.number(),
    details: zod
      .union([
        zod.object({
          branch: zod.enum(['AUTO']),
          brand: zod.string().min(1),
          model: zod.string().min(1),
          manufacturingYear: zod
            .number()
            .min(
              updateProposalObservationsResponseDataDetailsOneManufacturingYearMin
            )
            .max(
              updateProposalObservationsResponseDataDetailsOneManufacturingYearMax
            ),
          modelYear: zod
            .number()
            .min(updateProposalObservationsResponseDataDetailsOneModelYearMin)
            .max(updateProposalObservationsResponseDataDetailsOneModelYearMax),
          licensePlate: zod.string().optional(),
          vin: zod.string().optional(),
          color: zod.string().optional(),
          fuelType: zod.string().optional(),
          vehicleUsage: zod.string().optional(),
        }),
        zod.object({
          branch: zod.enum(['RESIDENTIAL']),
          propertyType: zod.string().min(1),
          propertyUsage: zod.string().min(1),
          cep: zod.string().min(1),
          street: zod.string().optional(),
          number: zod.string().optional(),
          complement: zod.string().optional(),
          neighborhood: zod.string().optional(),
          city: zod.string().optional(),
          state: zod
            .string()
            .min(updateProposalObservationsResponseDataDetailsTwoStateMin)
            .max(updateProposalObservationsResponseDataDetailsTwoStateMax)
            .optional(),
          construction: zod.string().optional(),
          areaM2: zod.number().optional(),
        }),
        zod.object({
          branch: zod.enum(['CONDOMINIUM']),
          condominiumName: zod.string().min(1),
          unitCount: zod.number().min(1),
          cep: zod.string().min(1),
          street: zod.string().optional(),
          number: zod.string().optional(),
          complement: zod.string().optional(),
          neighborhood: zod.string().optional(),
          city: zod.string().optional(),
          state: zod
            .string()
            .min(updateProposalObservationsResponseDataDetailsThreeStateMin)
            .max(updateProposalObservationsResponseDataDetailsThreeStateMax)
            .optional(),
          constructionYear: zod.number().optional(),
          floorCount: zod.number().optional(),
          blockCount: zod.number().optional(),
          elevatorCount: zod.number().optional(),
          employeeCount: zod.number().optional(),
          hasSecurityEquipment: zod.boolean().optional(),
          securityEquipmentDetails: zod.string().optional(),
          hasFireEquipment: zod.boolean().optional(),
          fireEquipmentDetails: zod.string().optional(),
        }),
        zod.object({
          branch: zod.enum(['BUSINESS']),
          legalName: zod.string().min(1),
          cnpj: zod.string().min(1),
          businessActivity: zod.string().min(1),
          cep: zod.string().optional(),
          street: zod.string().optional(),
          number: zod.string().optional(),
          complement: zod.string().optional(),
          neighborhood: zod.string().optional(),
          city: zod.string().optional(),
          state: zod
            .string()
            .min(updateProposalObservationsResponseDataDetailsFourStateMin)
            .max(updateProposalObservationsResponseDataDetailsFourStateMax)
            .optional(),
          areaM2: zod.number().optional(),
        }),
        zod.object({
          branch: zod.enum(['LIFE']),
          occupation: zod.string().min(1),
          monthlyIncomeCents: zod
            .number()
            .min(
              updateProposalObservationsResponseDataDetailsFiveMonthlyIncomeCentsMin
            )
            .optional(),
          isSmoker: zod.boolean().optional(),
          extremeSports: zod.boolean().optional(),
          heightInCentimeters: zod
            .number()
            .min(
              updateProposalObservationsResponseDataDetailsFiveHeightInCentimetersMin
            )
            .max(
              updateProposalObservationsResponseDataDetailsFiveHeightInCentimetersMax
            )
            .optional(),
          weightInGrams: zod
            .number()
            .min(
              updateProposalObservationsResponseDataDetailsFiveWeightInGramsMin
            )
            .max(
              updateProposalObservationsResponseDataDetailsFiveWeightInGramsMax
            )
            .optional(),
          beneficiaries: zod.string().optional(),
        }),
        zod.object({
          branch: zod.enum(['OTHER']),
          description: zod.string().min(1),
        }),
      ])
      .nullable(),
    lostReason: zod.string().nullable(),
    observations: zod.string().nullable(),
    renewalPolicyId: zod.string().nullable(),
    renewalPolicyNumber: zod.string().nullable(),
    sourcePolicyId: zod.string().nullable(),
    endorsementType: zod.string().nullable(),
    endorsementReason: zod.string().nullable(),
    sourcePolicySnapshot: zod
      .object({
        policyNumber: zod.string(),
        clientName: zod.string(),
        startDate: zod.string().datetime({}),
        endDate: zod.string().datetime({}),
        status: zod.enum(['ACTIVE', 'CANCELLED', 'EXPIRED']),
        insurerId: zod.string().nullable(),
        insurerName: zod.string().nullable(),
      })
      .nullable(),
    insurerId: zod.string().nullable(),
    deletedAt: zod.string().datetime({}).nullable(),
    createdAt: zod.string().datetime({}),
    updatedAt: zod.string().datetime({}),
    coverageStartDate: zod.string().datetime({}).nullable(),
    coverageEndDate: zod.string().datetime({}).nullable(),
    sentToClientAt: zod.string().datetime({}).nullable(),
    clientResponseAt: zod.string().datetime({}).nullable(),
    quoteValidUntil: zod.string().datetime({}).nullable(),
    clientName: zod.string().optional(),
    clientDocument: zod.string().optional(),
    clientPersonType: zod.string().optional(),
    salespersonName: zod.string().optional(),
    insurerName: zod.string().optional(),
  }),
})

/**
 * @summary Get proposal checklist items
 */

export const GetProposalChecklistParams = zod.object({
  id: zod.string().min(1),
})

export const GetProposalChecklistResponse = zod.object({
  success: zod.literal(true),
  data: zod.object({
    items: zod.array(
      zod.object({
        id: zod.string(),
        proposalId: zod.string(),
        itemKey: zod.string(),
        label: zod.string(),
        isRequired: zod.boolean(),
        isCompleted: zod.boolean(),
        completedAt: zod.string().datetime({}).nullable(),
        completedBy: zod.string().nullable(),
        createdAt: zod.string().datetime({}),
      })
    ),
    summary: zod.object({
      total: zod.number(),
      completed: zod.number(),
      required: zod.number(),
      requiredCompleted: zod.number(),
      canAdvance: zod.boolean(),
    }),
  }),
})

/**
 * @summary Mark a checklist item as complete
 */

export const CompleteProposalChecklistItemParams = zod.object({
  id: zod.string().min(1),
  itemId: zod.string().min(1),
})

export const CompleteProposalChecklistItemResponse = zod.object({
  success: zod.literal(true),
  data: zod.object({
    id: zod.string(),
    proposalId: zod.string(),
    itemKey: zod.string(),
    label: zod.string(),
    isRequired: zod.boolean(),
    isCompleted: zod.boolean(),
    completedAt: zod.string().datetime({}).nullable(),
    completedBy: zod.string().nullable(),
    createdAt: zod.string().datetime({}),
  }),
})

/**
 * @summary Unmark a checklist item (revert completion)
 */

export const UncompleteProposalChecklistItemParams = zod.object({
  id: zod.string().min(1),
  itemId: zod.string().min(1),
})

export const UncompleteProposalChecklistItemResponse = zod.object({
  success: zod.literal(true),
  data: zod.object({
    id: zod.string(),
    proposalId: zod.string(),
    itemKey: zod.string(),
    label: zod.string(),
    isRequired: zod.boolean(),
    isCompleted: zod.boolean(),
    completedAt: zod.string().datetime({}).nullable(),
    completedBy: zod.string().nullable(),
    createdAt: zod.string().datetime({}),
  }),
})
