/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type {
  AdvanceProposal200,
  AdvanceProposal400,
  AdvanceProposal404,
  CompleteProposalChecklistItem200,
  CompleteProposalChecklistItem404,
  CreateProposal201,
  CreateProposal400,
  CreateProposal422,
  CreateProposalBody,
  ExportProposalsParams,
  GenerateProposalPdf200,
  GenerateProposalPdf404,
  GetProposal200,
  GetProposal404,
  GetProposalChecklist200,
  GetProposalChecklist404,
  ListProposals200,
  ListProposalsParams,
  MarkProposalLost200,
  MarkProposalLost400,
  MarkProposalLost404,
  MarkProposalLostBody,
  ReopenProposal200,
  ReopenProposal400,
  ReopenProposal404,
  UpdateProposalDetails200,
  UpdateProposalDetails400,
  UpdateProposalDetails404,
  UpdateProposalDetailsBody,
} from '../../model'

import { customFetch } from '../../../lib/api-mutator'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Export proposals as CSV
 */
export type exportProposalsResponse200 = {
  data: void
  status: 200
}

export type exportProposalsResponseSuccess = exportProposalsResponse200 & {
  headers: Headers
}
export type exportProposalsResponse = exportProposalsResponseSuccess

export const getExportProposalsUrl = (params?: ExportProposalsParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/v1/proposals/export?${stringifiedParams}`
    : `/api/v1/proposals/export`
}

export const exportProposals = async (
  params?: ExportProposalsParams,
  options?: RequestInit
): Promise<exportProposalsResponse> => {
  return customFetch<exportProposalsResponse>(getExportProposalsUrl(params), {
    ...options,
    method: 'GET',
  })
}

export const getExportProposalsQueryKey = (params?: ExportProposalsParams) => {
  return [`/api/v1/proposals/export`, ...(params ? [params] : [])] as const
}

export const getExportProposalsQueryOptions = <
  TData = Awaited<ReturnType<typeof exportProposals>>,
  TError = unknown,
>(
  params?: ExportProposalsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof exportProposals>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customFetch>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getExportProposalsQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof exportProposals>>> = ({
    signal,
  }) => exportProposals(params, { signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    staleTime: 60000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof exportProposals>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ExportProposalsQueryResult = NonNullable<
  Awaited<ReturnType<typeof exportProposals>>
>
export type ExportProposalsQueryError = unknown

export function useExportProposals<
  TData = Awaited<ReturnType<typeof exportProposals>>,
  TError = unknown,
>(
  params: undefined | ExportProposalsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof exportProposals>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof exportProposals>>,
          TError,
          Awaited<ReturnType<typeof exportProposals>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useExportProposals<
  TData = Awaited<ReturnType<typeof exportProposals>>,
  TError = unknown,
>(
  params?: ExportProposalsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof exportProposals>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof exportProposals>>,
          TError,
          Awaited<ReturnType<typeof exportProposals>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useExportProposals<
  TData = Awaited<ReturnType<typeof exportProposals>>,
  TError = unknown,
>(
  params?: ExportProposalsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof exportProposals>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Export proposals as CSV
 */

export function useExportProposals<
  TData = Awaited<ReturnType<typeof exportProposals>>,
  TError = unknown,
>(
  params?: ExportProposalsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof exportProposals>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getExportProposalsQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * @summary Export proposals as CSV
 */
export const prefetchExportProposalsQuery = async <
  TData = Awaited<ReturnType<typeof exportProposals>>,
  TError = unknown,
>(
  queryClient: QueryClient,
  params?: ExportProposalsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof exportProposals>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customFetch>
  }
): Promise<QueryClient> => {
  const queryOptions = getExportProposalsQueryOptions(params, options)

  await queryClient.prefetchQuery(queryOptions)

  return queryClient
}

/**
 * @summary Generate or retrieve proposal PDF
 */
export type generateProposalPdfResponse200 = {
  data: GenerateProposalPdf200
  status: 200
}

export type generateProposalPdfResponse404 = {
  data: GenerateProposalPdf404
  status: 404
}

export type generateProposalPdfResponseSuccess =
  generateProposalPdfResponse200 & {
    headers: Headers
  }
export type generateProposalPdfResponseError =
  generateProposalPdfResponse404 & {
    headers: Headers
  }

export type generateProposalPdfResponse =
  | generateProposalPdfResponseSuccess
  | generateProposalPdfResponseError

export const getGenerateProposalPdfUrl = (id: string) => {
  return `/api/v1/proposals/${id}/pdf`
}

export const generateProposalPdf = async (
  id: string,
  options?: RequestInit
): Promise<generateProposalPdfResponse> => {
  return customFetch<generateProposalPdfResponse>(
    getGenerateProposalPdfUrl(id),
    {
      ...options,
      method: 'POST',
    }
  )
}

export const getGenerateProposalPdfMutationOptions = <
  TError = GenerateProposalPdf404,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof generateProposalPdf>>,
    TError,
    { id: string },
    TContext
  >
  request?: SecondParameter<typeof customFetch>
}): UseMutationOptions<
  Awaited<ReturnType<typeof generateProposalPdf>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['generateProposalPdf']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof generateProposalPdf>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {}

    return generateProposalPdf(id, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type GenerateProposalPdfMutationResult = NonNullable<
  Awaited<ReturnType<typeof generateProposalPdf>>
>

export type GenerateProposalPdfMutationError = GenerateProposalPdf404

/**
 * @summary Generate or retrieve proposal PDF
 */
export const useGenerateProposalPdf = <
  TError = GenerateProposalPdf404,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof generateProposalPdf>>,
      TError,
      { id: string },
      TContext
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof generateProposalPdf>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getGenerateProposalPdfMutationOptions(options),
    queryClient
  )
}
/**
 * @summary Create a new proposal
 */
export type createProposalResponse201 = {
  data: CreateProposal201
  status: 201
}

export type createProposalResponse400 = {
  data: CreateProposal400
  status: 400
}

export type createProposalResponse422 = {
  data: CreateProposal422
  status: 422
}

export type createProposalResponseSuccess = createProposalResponse201 & {
  headers: Headers
}
export type createProposalResponseError = (
  | createProposalResponse400
  | createProposalResponse422
) & {
  headers: Headers
}

export type createProposalResponse =
  | createProposalResponseSuccess
  | createProposalResponseError

export const getCreateProposalUrl = () => {
  return `/api/v1/proposals`
}

export const createProposal = async (
  createProposalBody: CreateProposalBody,
  options?: RequestInit
): Promise<createProposalResponse> => {
  return customFetch<createProposalResponse>(getCreateProposalUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createProposalBody),
  })
}

export const getCreateProposalMutationOptions = <
  TError = CreateProposal400 | CreateProposal422,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createProposal>>,
    TError,
    { data: CreateProposalBody },
    TContext
  >
  request?: SecondParameter<typeof customFetch>
}): UseMutationOptions<
  Awaited<ReturnType<typeof createProposal>>,
  TError,
  { data: CreateProposalBody },
  TContext
> => {
  const mutationKey = ['createProposal']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createProposal>>,
    { data: CreateProposalBody }
  > = (props) => {
    const { data } = props ?? {}

    return createProposal(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type CreateProposalMutationResult = NonNullable<
  Awaited<ReturnType<typeof createProposal>>
>
export type CreateProposalMutationBody = CreateProposalBody
export type CreateProposalMutationError = CreateProposal400 | CreateProposal422

/**
 * @summary Create a new proposal
 */
export const useCreateProposal = <
  TError = CreateProposal400 | CreateProposal422,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createProposal>>,
      TError,
      { data: CreateProposalBody },
      TContext
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof createProposal>>,
  TError,
  { data: CreateProposalBody },
  TContext
> => {
  return useMutation(getCreateProposalMutationOptions(options), queryClient)
}
/**
 * @summary List proposals with cursor pagination
 */
export type listProposalsResponse200 = {
  data: ListProposals200
  status: 200
}

export type listProposalsResponseSuccess = listProposalsResponse200 & {
  headers: Headers
}
export type listProposalsResponse = listProposalsResponseSuccess

export const getListProposalsUrl = (params?: ListProposalsParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/v1/proposals?${stringifiedParams}`
    : `/api/v1/proposals`
}

export const listProposals = async (
  params?: ListProposalsParams,
  options?: RequestInit
): Promise<listProposalsResponse> => {
  return customFetch<listProposalsResponse>(getListProposalsUrl(params), {
    ...options,
    method: 'GET',
  })
}

export const getListProposalsQueryKey = (params?: ListProposalsParams) => {
  return [`/api/v1/proposals`, ...(params ? [params] : [])] as const
}

export const getListProposalsQueryOptions = <
  TData = Awaited<ReturnType<typeof listProposals>>,
  TError = unknown,
>(
  params?: ListProposalsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listProposals>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getListProposalsQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listProposals>>> = ({
    signal,
  }) => listProposals(params, { signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    staleTime: 60000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof listProposals>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListProposalsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listProposals>>
>
export type ListProposalsQueryError = unknown

export function useListProposals<
  TData = Awaited<ReturnType<typeof listProposals>>,
  TError = unknown,
>(
  params: undefined | ListProposalsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listProposals>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listProposals>>,
          TError,
          Awaited<ReturnType<typeof listProposals>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useListProposals<
  TData = Awaited<ReturnType<typeof listProposals>>,
  TError = unknown,
>(
  params?: ListProposalsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listProposals>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listProposals>>,
          TError,
          Awaited<ReturnType<typeof listProposals>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useListProposals<
  TData = Awaited<ReturnType<typeof listProposals>>,
  TError = unknown,
>(
  params?: ListProposalsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listProposals>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary List proposals with cursor pagination
 */

export function useListProposals<
  TData = Awaited<ReturnType<typeof listProposals>>,
  TError = unknown,
>(
  params?: ListProposalsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listProposals>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getListProposalsQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * @summary List proposals with cursor pagination
 */
export const prefetchListProposalsQuery = async <
  TData = Awaited<ReturnType<typeof listProposals>>,
  TError = unknown,
>(
  queryClient: QueryClient,
  params?: ListProposalsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listProposals>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  }
): Promise<QueryClient> => {
  const queryOptions = getListProposalsQueryOptions(params, options)

  await queryClient.prefetchQuery(queryOptions)

  return queryClient
}

/**
 * @summary Get a proposal by ID
 */
export type getProposalResponse200 = {
  data: GetProposal200
  status: 200
}

export type getProposalResponse404 = {
  data: GetProposal404
  status: 404
}

export type getProposalResponseSuccess = getProposalResponse200 & {
  headers: Headers
}
export type getProposalResponseError = getProposalResponse404 & {
  headers: Headers
}

export type getProposalResponse =
  | getProposalResponseSuccess
  | getProposalResponseError

export const getGetProposalUrl = (id: string) => {
  return `/api/v1/proposals/${id}`
}

export const getProposal = async (
  id: string,
  options?: RequestInit
): Promise<getProposalResponse> => {
  return customFetch<getProposalResponse>(getGetProposalUrl(id), {
    ...options,
    method: 'GET',
  })
}

export const getGetProposalQueryKey = (id: string) => {
  return [`/api/v1/proposals/${id}`] as const
}

export const getGetProposalQueryOptions = <
  TData = Awaited<ReturnType<typeof getProposal>>,
  TError = GetProposal404,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProposal>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetProposalQueryKey(id)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getProposal>>> = ({
    signal,
  }) => getProposal(id, { signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    staleTime: 60000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getProposal>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProposalQueryResult = NonNullable<
  Awaited<ReturnType<typeof getProposal>>
>
export type GetProposalQueryError = GetProposal404

export function useGetProposal<
  TData = Awaited<ReturnType<typeof getProposal>>,
  TError = GetProposal404,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProposal>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProposal>>,
          TError,
          Awaited<ReturnType<typeof getProposal>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetProposal<
  TData = Awaited<ReturnType<typeof getProposal>>,
  TError = GetProposal404,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProposal>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProposal>>,
          TError,
          Awaited<ReturnType<typeof getProposal>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetProposal<
  TData = Awaited<ReturnType<typeof getProposal>>,
  TError = GetProposal404,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProposal>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get a proposal by ID
 */

export function useGetProposal<
  TData = Awaited<ReturnType<typeof getProposal>>,
  TError = GetProposal404,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProposal>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetProposalQueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * @summary Get a proposal by ID
 */
export const prefetchGetProposalQuery = async <
  TData = Awaited<ReturnType<typeof getProposal>>,
  TError = GetProposal404,
>(
  queryClient: QueryClient,
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProposal>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  }
): Promise<QueryClient> => {
  const queryOptions = getGetProposalQueryOptions(id, options)

  await queryClient.prefetchQuery(queryOptions)

  return queryClient
}

/**
 * @summary Advance proposal to next stage
 */
export type advanceProposalResponse200 = {
  data: AdvanceProposal200
  status: 200
}

export type advanceProposalResponse400 = {
  data: AdvanceProposal400
  status: 400
}

export type advanceProposalResponse404 = {
  data: AdvanceProposal404
  status: 404
}

export type advanceProposalResponseSuccess = advanceProposalResponse200 & {
  headers: Headers
}
export type advanceProposalResponseError = (
  | advanceProposalResponse400
  | advanceProposalResponse404
) & {
  headers: Headers
}

export type advanceProposalResponse =
  | advanceProposalResponseSuccess
  | advanceProposalResponseError

export const getAdvanceProposalUrl = (id: string) => {
  return `/api/v1/proposals/${id}/advance`
}

export const advanceProposal = async (
  id: string,
  options?: RequestInit
): Promise<advanceProposalResponse> => {
  return customFetch<advanceProposalResponse>(getAdvanceProposalUrl(id), {
    ...options,
    method: 'POST',
  })
}

export const getAdvanceProposalMutationOptions = <
  TError = AdvanceProposal400 | AdvanceProposal404,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof advanceProposal>>,
    TError,
    { id: string },
    TContext
  >
  request?: SecondParameter<typeof customFetch>
}): UseMutationOptions<
  Awaited<ReturnType<typeof advanceProposal>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['advanceProposal']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof advanceProposal>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {}

    return advanceProposal(id, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AdvanceProposalMutationResult = NonNullable<
  Awaited<ReturnType<typeof advanceProposal>>
>

export type AdvanceProposalMutationError =
  | AdvanceProposal400
  | AdvanceProposal404

/**
 * @summary Advance proposal to next stage
 */
export const useAdvanceProposal = <
  TError = AdvanceProposal400 | AdvanceProposal404,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof advanceProposal>>,
      TError,
      { id: string },
      TContext
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof advanceProposal>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getAdvanceProposalMutationOptions(options), queryClient)
}
/**
 * @summary Mark proposal as lost
 */
export type markProposalLostResponse200 = {
  data: MarkProposalLost200
  status: 200
}

export type markProposalLostResponse400 = {
  data: MarkProposalLost400
  status: 400
}

export type markProposalLostResponse404 = {
  data: MarkProposalLost404
  status: 404
}

export type markProposalLostResponseSuccess = markProposalLostResponse200 & {
  headers: Headers
}
export type markProposalLostResponseError = (
  | markProposalLostResponse400
  | markProposalLostResponse404
) & {
  headers: Headers
}

export type markProposalLostResponse =
  | markProposalLostResponseSuccess
  | markProposalLostResponseError

export const getMarkProposalLostUrl = (id: string) => {
  return `/api/v1/proposals/${id}/lost`
}

export const markProposalLost = async (
  id: string,
  markProposalLostBody: MarkProposalLostBody,
  options?: RequestInit
): Promise<markProposalLostResponse> => {
  return customFetch<markProposalLostResponse>(getMarkProposalLostUrl(id), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(markProposalLostBody),
  })
}

export const getMarkProposalLostMutationOptions = <
  TError = MarkProposalLost400 | MarkProposalLost404,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof markProposalLost>>,
    TError,
    { id: string; data: MarkProposalLostBody },
    TContext
  >
  request?: SecondParameter<typeof customFetch>
}): UseMutationOptions<
  Awaited<ReturnType<typeof markProposalLost>>,
  TError,
  { id: string; data: MarkProposalLostBody },
  TContext
> => {
  const mutationKey = ['markProposalLost']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof markProposalLost>>,
    { id: string; data: MarkProposalLostBody }
  > = (props) => {
    const { id, data } = props ?? {}

    return markProposalLost(id, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type MarkProposalLostMutationResult = NonNullable<
  Awaited<ReturnType<typeof markProposalLost>>
>
export type MarkProposalLostMutationBody = MarkProposalLostBody
export type MarkProposalLostMutationError =
  | MarkProposalLost400
  | MarkProposalLost404

/**
 * @summary Mark proposal as lost
 */
export const useMarkProposalLost = <
  TError = MarkProposalLost400 | MarkProposalLost404,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof markProposalLost>>,
      TError,
      { id: string; data: MarkProposalLostBody },
      TContext
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof markProposalLost>>,
  TError,
  { id: string; data: MarkProposalLostBody },
  TContext
> => {
  return useMutation(getMarkProposalLostMutationOptions(options), queryClient)
}
/**
 * @summary Reopen a lost proposal
 */
export type reopenProposalResponse200 = {
  data: ReopenProposal200
  status: 200
}

export type reopenProposalResponse400 = {
  data: ReopenProposal400
  status: 400
}

export type reopenProposalResponse404 = {
  data: ReopenProposal404
  status: 404
}

export type reopenProposalResponseSuccess = reopenProposalResponse200 & {
  headers: Headers
}
export type reopenProposalResponseError = (
  | reopenProposalResponse400
  | reopenProposalResponse404
) & {
  headers: Headers
}

export type reopenProposalResponse =
  | reopenProposalResponseSuccess
  | reopenProposalResponseError

export const getReopenProposalUrl = (id: string) => {
  return `/api/v1/proposals/${id}/reopen`
}

export const reopenProposal = async (
  id: string,
  options?: RequestInit
): Promise<reopenProposalResponse> => {
  return customFetch<reopenProposalResponse>(getReopenProposalUrl(id), {
    ...options,
    method: 'POST',
  })
}

export const getReopenProposalMutationOptions = <
  TError = ReopenProposal400 | ReopenProposal404,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof reopenProposal>>,
    TError,
    { id: string },
    TContext
  >
  request?: SecondParameter<typeof customFetch>
}): UseMutationOptions<
  Awaited<ReturnType<typeof reopenProposal>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['reopenProposal']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof reopenProposal>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {}

    return reopenProposal(id, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ReopenProposalMutationResult = NonNullable<
  Awaited<ReturnType<typeof reopenProposal>>
>

export type ReopenProposalMutationError = ReopenProposal400 | ReopenProposal404

/**
 * @summary Reopen a lost proposal
 */
export const useReopenProposal = <
  TError = ReopenProposal400 | ReopenProposal404,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof reopenProposal>>,
      TError,
      { id: string },
      TContext
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof reopenProposal>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getReopenProposalMutationOptions(options), queryClient)
}
/**
 * @summary Update proposal insured object details
 */
export type updateProposalDetailsResponse200 = {
  data: UpdateProposalDetails200
  status: 200
}

export type updateProposalDetailsResponse400 = {
  data: UpdateProposalDetails400
  status: 400
}

export type updateProposalDetailsResponse404 = {
  data: UpdateProposalDetails404
  status: 404
}

export type updateProposalDetailsResponseSuccess =
  updateProposalDetailsResponse200 & {
    headers: Headers
  }
export type updateProposalDetailsResponseError = (
  | updateProposalDetailsResponse400
  | updateProposalDetailsResponse404
) & {
  headers: Headers
}

export type updateProposalDetailsResponse =
  | updateProposalDetailsResponseSuccess
  | updateProposalDetailsResponseError

export const getUpdateProposalDetailsUrl = (id: string) => {
  return `/api/v1/proposals/${id}/details`
}

export const updateProposalDetails = async (
  id: string,
  updateProposalDetailsBody: UpdateProposalDetailsBody,
  options?: RequestInit
): Promise<updateProposalDetailsResponse> => {
  return customFetch<updateProposalDetailsResponse>(
    getUpdateProposalDetailsUrl(id),
    {
      ...options,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(updateProposalDetailsBody),
    }
  )
}

export const getUpdateProposalDetailsMutationOptions = <
  TError = UpdateProposalDetails400 | UpdateProposalDetails404,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateProposalDetails>>,
    TError,
    { id: string; data: UpdateProposalDetailsBody },
    TContext
  >
  request?: SecondParameter<typeof customFetch>
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateProposalDetails>>,
  TError,
  { id: string; data: UpdateProposalDetailsBody },
  TContext
> => {
  const mutationKey = ['updateProposalDetails']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateProposalDetails>>,
    { id: string; data: UpdateProposalDetailsBody }
  > = (props) => {
    const { id, data } = props ?? {}

    return updateProposalDetails(id, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UpdateProposalDetailsMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateProposalDetails>>
>
export type UpdateProposalDetailsMutationBody = UpdateProposalDetailsBody
export type UpdateProposalDetailsMutationError =
  | UpdateProposalDetails400
  | UpdateProposalDetails404

/**
 * @summary Update proposal insured object details
 */
export const useUpdateProposalDetails = <
  TError = UpdateProposalDetails400 | UpdateProposalDetails404,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateProposalDetails>>,
      TError,
      { id: string; data: UpdateProposalDetailsBody },
      TContext
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof updateProposalDetails>>,
  TError,
  { id: string; data: UpdateProposalDetailsBody },
  TContext
> => {
  return useMutation(
    getUpdateProposalDetailsMutationOptions(options),
    queryClient
  )
}
/**
 * @summary Get proposal checklist items
 */
export type getProposalChecklistResponse200 = {
  data: GetProposalChecklist200
  status: 200
}

export type getProposalChecklistResponse404 = {
  data: GetProposalChecklist404
  status: 404
}

export type getProposalChecklistResponseSuccess =
  getProposalChecklistResponse200 & {
    headers: Headers
  }
export type getProposalChecklistResponseError =
  getProposalChecklistResponse404 & {
    headers: Headers
  }

export type getProposalChecklistResponse =
  | getProposalChecklistResponseSuccess
  | getProposalChecklistResponseError

export const getGetProposalChecklistUrl = (id: string) => {
  return `/api/v1/proposals/${id}/checklist`
}

export const getProposalChecklist = async (
  id: string,
  options?: RequestInit
): Promise<getProposalChecklistResponse> => {
  return customFetch<getProposalChecklistResponse>(
    getGetProposalChecklistUrl(id),
    {
      ...options,
      method: 'GET',
    }
  )
}

export const getGetProposalChecklistQueryKey = (id: string) => {
  return [`/api/v1/proposals/${id}/checklist`] as const
}

export const getGetProposalChecklistQueryOptions = <
  TData = Awaited<ReturnType<typeof getProposalChecklist>>,
  TError = GetProposalChecklist404,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProposalChecklist>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customFetch>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetProposalChecklistQueryKey(id)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getProposalChecklist>>
  > = ({ signal }) => getProposalChecklist(id, { signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    staleTime: 60000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getProposalChecklist>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProposalChecklistQueryResult = NonNullable<
  Awaited<ReturnType<typeof getProposalChecklist>>
>
export type GetProposalChecklistQueryError = GetProposalChecklist404

export function useGetProposalChecklist<
  TData = Awaited<ReturnType<typeof getProposalChecklist>>,
  TError = GetProposalChecklist404,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProposalChecklist>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProposalChecklist>>,
          TError,
          Awaited<ReturnType<typeof getProposalChecklist>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetProposalChecklist<
  TData = Awaited<ReturnType<typeof getProposalChecklist>>,
  TError = GetProposalChecklist404,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProposalChecklist>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProposalChecklist>>,
          TError,
          Awaited<ReturnType<typeof getProposalChecklist>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetProposalChecklist<
  TData = Awaited<ReturnType<typeof getProposalChecklist>>,
  TError = GetProposalChecklist404,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProposalChecklist>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get proposal checklist items
 */

export function useGetProposalChecklist<
  TData = Awaited<ReturnType<typeof getProposalChecklist>>,
  TError = GetProposalChecklist404,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProposalChecklist>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetProposalChecklistQueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * @summary Get proposal checklist items
 */
export const prefetchGetProposalChecklistQuery = async <
  TData = Awaited<ReturnType<typeof getProposalChecklist>>,
  TError = GetProposalChecklist404,
>(
  queryClient: QueryClient,
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProposalChecklist>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customFetch>
  }
): Promise<QueryClient> => {
  const queryOptions = getGetProposalChecklistQueryOptions(id, options)

  await queryClient.prefetchQuery(queryOptions)

  return queryClient
}

/**
 * @summary Mark a checklist item as complete
 */
export type completeProposalChecklistItemResponse200 = {
  data: CompleteProposalChecklistItem200
  status: 200
}

export type completeProposalChecklistItemResponse404 = {
  data: CompleteProposalChecklistItem404
  status: 404
}

export type completeProposalChecklistItemResponseSuccess =
  completeProposalChecklistItemResponse200 & {
    headers: Headers
  }
export type completeProposalChecklistItemResponseError =
  completeProposalChecklistItemResponse404 & {
    headers: Headers
  }

export type completeProposalChecklistItemResponse =
  | completeProposalChecklistItemResponseSuccess
  | completeProposalChecklistItemResponseError

export const getCompleteProposalChecklistItemUrl = (
  id: string,
  itemId: string
) => {
  return `/api/v1/proposals/${id}/checklist/${itemId}/complete`
}

export const completeProposalChecklistItem = async (
  id: string,
  itemId: string,
  options?: RequestInit
): Promise<completeProposalChecklistItemResponse> => {
  return customFetch<completeProposalChecklistItemResponse>(
    getCompleteProposalChecklistItemUrl(id, itemId),
    {
      ...options,
      method: 'POST',
    }
  )
}

export const getCompleteProposalChecklistItemMutationOptions = <
  TError = CompleteProposalChecklistItem404,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof completeProposalChecklistItem>>,
    TError,
    { id: string; itemId: string },
    TContext
  >
  request?: SecondParameter<typeof customFetch>
}): UseMutationOptions<
  Awaited<ReturnType<typeof completeProposalChecklistItem>>,
  TError,
  { id: string; itemId: string },
  TContext
> => {
  const mutationKey = ['completeProposalChecklistItem']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof completeProposalChecklistItem>>,
    { id: string; itemId: string }
  > = (props) => {
    const { id, itemId } = props ?? {}

    return completeProposalChecklistItem(id, itemId, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type CompleteProposalChecklistItemMutationResult = NonNullable<
  Awaited<ReturnType<typeof completeProposalChecklistItem>>
>

export type CompleteProposalChecklistItemMutationError =
  CompleteProposalChecklistItem404

/**
 * @summary Mark a checklist item as complete
 */
export const useCompleteProposalChecklistItem = <
  TError = CompleteProposalChecklistItem404,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof completeProposalChecklistItem>>,
      TError,
      { id: string; itemId: string },
      TContext
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof completeProposalChecklistItem>>,
  TError,
  { id: string; itemId: string },
  TContext
> => {
  return useMutation(
    getCompleteProposalChecklistItemMutationOptions(options),
    queryClient
  )
}
