/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod'

/**
 * @summary Create a new endorsement
 */

export const CreateEndorsementBody = zod.object({
  policyId: zod.string().min(1),
  type: zod.string().min(1),
  description: zod.string().min(1),
  effectiveDate: zod.string().datetime({}),
  previousVersionSnapshot: zod.record(
    zod.string(),
    zod.union([
      zod.union([
        zod.string(),
        zod.number(),
        zod.boolean(),
        zod.enum(['null']).nullable(),
      ]),
      zod.array(zod.unknown()),
      zod.record(zod.string(), zod.unknown()),
    ])
  ),
  changes: zod.record(
    zod.string(),
    zod.union([
      zod.union([
        zod.string(),
        zod.number(),
        zod.boolean(),
        zod.enum(['null']).nullable(),
      ]),
      zod.array(zod.unknown()),
      zod.record(zod.string(), zod.unknown()),
    ])
  ),
})

/**
 * @summary List endorsements with pagination
 */
export const listEndorsementsQueryLimitDefault = 20
export const listEndorsementsQueryLimitMax = 100

export const ListEndorsementsQueryParams = zod.object({
  policyId: zod.string().optional(),
  cursor: zod.string().optional(),
  limit: zod
    .number()
    .min(1)
    .max(listEndorsementsQueryLimitMax)
    .default(listEndorsementsQueryLimitDefault),
})

export const ListEndorsementsResponse = zod.object({
  success: zod.literal(true),
  data: zod.array(
    zod.object({
      id: zod.string(),
      organizationId: zod.string(),
      policyId: zod.string(),
      type: zod.string(),
      description: zod.string(),
      effectiveDate: zod.string().datetime({}),
      previousVersionSnapshot: zod.record(zod.string(), zod.unknown()),
      changes: zod.record(zod.string(), zod.unknown()),
      createdBy: zod.string().nullable(),
      createdAt: zod.string().datetime({}),
      updatedAt: zod.string().datetime({}),
      policyNumber: zod.string().optional(),
    })
  ),
  meta: zod.object({
    nextCursor: zod.string().nullable(),
  }),
})

/**
 * @summary Get an endorsement by ID
 */

export const GetEndorsementParams = zod.object({
  id: zod.string().min(1),
})

export const GetEndorsementResponse = zod.object({
  success: zod.literal(true),
  data: zod.object({
    id: zod.string(),
    organizationId: zod.string(),
    policyId: zod.string(),
    type: zod.string(),
    description: zod.string(),
    effectiveDate: zod.string().datetime({}),
    previousVersionSnapshot: zod.record(zod.string(), zod.unknown()),
    changes: zod.record(zod.string(), zod.unknown()),
    createdBy: zod.string().nullable(),
    createdAt: zod.string().datetime({}),
    updatedAt: zod.string().datetime({}),
    policyNumber: zod.string().optional(),
  }),
})
