/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type {
  GetDocumentUrl200,
  ListDocuments200,
  ListDocumentsParams,
  UploadDocument201,
  UploadDocument400,
  UploadDocumentParams,
} from '../../model'

import { customFetch } from '../../../lib/api-mutator'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Upload a document for an entity
 */
export type uploadDocumentResponse201 = {
  data: UploadDocument201
  status: 201
}

export type uploadDocumentResponse400 = {
  data: UploadDocument400
  status: 400
}

export type uploadDocumentResponseSuccess = uploadDocumentResponse201 & {
  headers: Headers
}
export type uploadDocumentResponseError = uploadDocumentResponse400 & {
  headers: Headers
}

export type uploadDocumentResponse =
  | uploadDocumentResponseSuccess
  | uploadDocumentResponseError

export const getUploadDocumentUrl = (params: UploadDocumentParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/v1/documents/upload?${stringifiedParams}`
    : `/api/v1/documents/upload`
}

export const uploadDocument = async (
  params: UploadDocumentParams,
  options?: RequestInit
): Promise<uploadDocumentResponse> => {
  return customFetch<uploadDocumentResponse>(getUploadDocumentUrl(params), {
    ...options,
    method: 'POST',
  })
}

export const getUploadDocumentMutationOptions = <
  TError = UploadDocument400,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof uploadDocument>>,
    TError,
    { params: UploadDocumentParams },
    TContext
  >
  request?: SecondParameter<typeof customFetch>
}): UseMutationOptions<
  Awaited<ReturnType<typeof uploadDocument>>,
  TError,
  { params: UploadDocumentParams },
  TContext
> => {
  const mutationKey = ['uploadDocument']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof uploadDocument>>,
    { params: UploadDocumentParams }
  > = (props) => {
    const { params } = props ?? {}

    return uploadDocument(params, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UploadDocumentMutationResult = NonNullable<
  Awaited<ReturnType<typeof uploadDocument>>
>

export type UploadDocumentMutationError = UploadDocument400

/**
 * @summary Upload a document for an entity
 */
export const useUploadDocument = <
  TError = UploadDocument400,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof uploadDocument>>,
      TError,
      { params: UploadDocumentParams },
      TContext
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof uploadDocument>>,
  TError,
  { params: UploadDocumentParams },
  TContext
> => {
  return useMutation(getUploadDocumentMutationOptions(options), queryClient)
}
/**
 * @summary List documents for a given entity
 */
export type listDocumentsResponse200 = {
  data: ListDocuments200
  status: 200
}

export type listDocumentsResponseSuccess = listDocumentsResponse200 & {
  headers: Headers
}
export type listDocumentsResponse = listDocumentsResponseSuccess

export const getListDocumentsUrl = (params: ListDocumentsParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/v1/documents?${stringifiedParams}`
    : `/api/v1/documents`
}

export const listDocuments = async (
  params: ListDocumentsParams,
  options?: RequestInit
): Promise<listDocumentsResponse> => {
  return customFetch<listDocumentsResponse>(getListDocumentsUrl(params), {
    ...options,
    method: 'GET',
  })
}

export const getListDocumentsQueryKey = (params?: ListDocumentsParams) => {
  return [`/api/v1/documents`, ...(params ? [params] : [])] as const
}

export const getListDocumentsQueryOptions = <
  TData = Awaited<ReturnType<typeof listDocuments>>,
  TError = unknown,
>(
  params: ListDocumentsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listDocuments>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getListDocumentsQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listDocuments>>> = ({
    signal,
  }) => listDocuments(params, { signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    staleTime: 60000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof listDocuments>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListDocumentsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listDocuments>>
>
export type ListDocumentsQueryError = unknown

export function useListDocuments<
  TData = Awaited<ReturnType<typeof listDocuments>>,
  TError = unknown,
>(
  params: ListDocumentsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listDocuments>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listDocuments>>,
          TError,
          Awaited<ReturnType<typeof listDocuments>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useListDocuments<
  TData = Awaited<ReturnType<typeof listDocuments>>,
  TError = unknown,
>(
  params: ListDocumentsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listDocuments>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listDocuments>>,
          TError,
          Awaited<ReturnType<typeof listDocuments>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useListDocuments<
  TData = Awaited<ReturnType<typeof listDocuments>>,
  TError = unknown,
>(
  params: ListDocumentsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listDocuments>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary List documents for a given entity
 */

export function useListDocuments<
  TData = Awaited<ReturnType<typeof listDocuments>>,
  TError = unknown,
>(
  params: ListDocumentsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listDocuments>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getListDocumentsQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * @summary List documents for a given entity
 */
export const prefetchListDocumentsQuery = async <
  TData = Awaited<ReturnType<typeof listDocuments>>,
  TError = unknown,
>(
  queryClient: QueryClient,
  params: ListDocumentsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listDocuments>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  }
): Promise<QueryClient> => {
  const queryOptions = getListDocumentsQueryOptions(params, options)

  await queryClient.prefetchQuery(queryOptions)

  return queryClient
}

/**
 * @summary Get a signed URL for a document
 */
export type getDocumentUrlResponse200 = {
  data: GetDocumentUrl200
  status: 200
}

export type getDocumentUrlResponseSuccess = getDocumentUrlResponse200 & {
  headers: Headers
}
export type getDocumentUrlResponse = getDocumentUrlResponseSuccess

export const getGetDocumentUrlUrl = (id: string) => {
  return `/api/v1/documents/${id}/url`
}

export const getDocumentUrl = async (
  id: string,
  options?: RequestInit
): Promise<getDocumentUrlResponse> => {
  return customFetch<getDocumentUrlResponse>(getGetDocumentUrlUrl(id), {
    ...options,
    method: 'GET',
  })
}

export const getGetDocumentUrlQueryKey = (id: string) => {
  return [`/api/v1/documents/${id}/url`] as const
}

export const getGetDocumentUrlQueryOptions = <
  TData = Awaited<ReturnType<typeof getDocumentUrl>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDocumentUrl>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetDocumentUrlQueryKey(id)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getDocumentUrl>>> = ({
    signal,
  }) => getDocumentUrl(id, { signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    staleTime: 60000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getDocumentUrl>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDocumentUrlQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDocumentUrl>>
>
export type GetDocumentUrlQueryError = unknown

export function useGetDocumentUrl<
  TData = Awaited<ReturnType<typeof getDocumentUrl>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDocumentUrl>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocumentUrl>>,
          TError,
          Awaited<ReturnType<typeof getDocumentUrl>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetDocumentUrl<
  TData = Awaited<ReturnType<typeof getDocumentUrl>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDocumentUrl>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocumentUrl>>,
          TError,
          Awaited<ReturnType<typeof getDocumentUrl>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetDocumentUrl<
  TData = Awaited<ReturnType<typeof getDocumentUrl>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDocumentUrl>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get a signed URL for a document
 */

export function useGetDocumentUrl<
  TData = Awaited<ReturnType<typeof getDocumentUrl>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDocumentUrl>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetDocumentUrlQueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * @summary Get a signed URL for a document
 */
export const prefetchGetDocumentUrlQuery = async <
  TData = Awaited<ReturnType<typeof getDocumentUrl>>,
  TError = unknown,
>(
  queryClient: QueryClient,
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDocumentUrl>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  }
): Promise<QueryClient> => {
  const queryOptions = getGetDocumentUrlQueryOptions(id, options)

  await queryClient.prefetchQuery(queryOptions)

  return queryClient
}

/**
 * @summary Delete a document by ID
 */
export type deleteDocumentResponse204 = {
  data: unknown
  status: 204
}

export type deleteDocumentResponseSuccess = deleteDocumentResponse204 & {
  headers: Headers
}
export type deleteDocumentResponse = deleteDocumentResponseSuccess

export const getDeleteDocumentUrl = (id: string) => {
  return `/api/v1/documents/${id}`
}

export const deleteDocument = async (
  id: string,
  options?: RequestInit
): Promise<deleteDocumentResponse> => {
  return customFetch<deleteDocumentResponse>(getDeleteDocumentUrl(id), {
    ...options,
    method: 'DELETE',
  })
}

export const getDeleteDocumentMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteDocument>>,
    TError,
    { id: string },
    TContext
  >
  request?: SecondParameter<typeof customFetch>
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteDocument>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['deleteDocument']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteDocument>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {}

    return deleteDocument(id, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type DeleteDocumentMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteDocument>>
>

export type DeleteDocumentMutationError = unknown

/**
 * @summary Delete a document by ID
 */
export const useDeleteDocument = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteDocument>>,
      TError,
      { id: string },
      TContext
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof deleteDocument>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getDeleteDocumentMutationOptions(options), queryClient)
}
