/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod'

/**
 * @summary Upload a document for an entity
 */

export const UploadDocumentQueryParams = zod.object({
  entityType: zod.enum(['CLIENT', 'PROPOSAL', 'POLICY', 'CLAIM', 'ASSISTANCE']),
  entityId: zod.string().min(1),
  clientId: zod.string().optional(),
  type: zod
    .enum([
      'DRIVER_LICENSE',
      'VEHICLE_REGISTRATION',
      'HEALTH_DECLARATION',
      'PROOF_OF_ADDRESS',
      'SOCIAL_CONTRACT',
      'CNPJ_CARD',
      'POLICY_PDF',
      'QUOTATION_PDF',
      'CLAIM_PHOTO',
      'CLAIM_REPORT',
      'PROOF_OF_PAYMENT',
      'CONTRACT',
      'OTHER',
    ])
    .optional(),
})

/**
 * @summary List documents for a given entity
 */

export const ListDocumentsQueryParams = zod.object({
  entityType: zod.enum(['CLIENT', 'PROPOSAL', 'POLICY', 'CLAIM', 'ASSISTANCE']),
  entityId: zod.string().min(1),
})

/**
 * @summary Get a signed URL for a document
 */

export const GetDocumentUrlParams = zod.object({
  id: zod.string().min(1),
})

/**
 * @summary Delete a document by ID
 */

export const DeleteDocumentParams = zod.object({
  id: zod.string().min(1),
})
