/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod'

/**
 * @summary Create a lead from chat conversation
 */

export const CreateLeadBody = zod.object({
  clientName: zod.string().min(1),
  clientPhone: zod.string().min(1),
  insuranceType: zod.string(),
  notes: zod.string().optional(),
  source: zod.string().optional(),
})
