/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod'

/**
 * @summary Create a new assistance request
 */

export const CreateAssistanceBody = zod.object({
  policyId: zod.string().min(1),
  clientId: zod.string().min(1),
  claimId: zod.union([zod.enum(['']), zod.string()]).optional(),
  type: zod.string().min(1),
  description: zod.union([zod.enum(['']), zod.string()]).optional(),
  address: zod.union([zod.enum(['']), zod.string()]).optional(),
  latitude: zod.number().optional(),
  longitude: zod.number().optional(),
  providerName: zod.union([zod.enum(['']), zod.string()]).optional(),
  providerPhone: zod.union([zod.enum(['']), zod.string()]).optional(),
  scheduledAt: zod
    .union([zod.enum(['']), zod.string().datetime({})])
    .optional(),
})

/**
 * @summary List assistance requests with pagination and filters
 */
export const listAssistancesQueryLimitDefault = 20
export const listAssistancesQueryLimitMax = 100

export const ListAssistancesQueryParams = zod.object({
  status: zod
    .enum([
      'REQUESTED',
      'AWAITING_DOCUMENT',
      'PENDING_INSPECTION',
      'DISPATCHED',
      'IN_PROGRESS',
      'COMPLETED',
    ])
    .optional(),
  policyId: zod.string().optional(),
  clientId: zod.string().optional(),
  type: zod.string().optional(),
  cursor: zod.string().optional(),
  limit: zod
    .number()
    .min(1)
    .max(listAssistancesQueryLimitMax)
    .default(listAssistancesQueryLimitDefault),
})

/**
 * @summary Get an assistance request by ID
 */

export const GetAssistanceParams = zod.object({
  id: zod.string().min(1),
})

/**
 * @summary Update the status of an assistance request
 */

export const UpdateAssistanceStatusParams = zod.object({
  id: zod.string().min(1),
})

export const UpdateAssistanceStatusBody = zod.object({
  status: zod.enum([
    'REQUESTED',
    'AWAITING_DOCUMENT',
    'PENDING_INSPECTION',
    'DISPATCHED',
    'IN_PROGRESS',
    'COMPLETED',
  ]),
})
