/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod'

/**
 * @summary Create a new assistance request
 */

export const CreateAssistanceBody = zod.object({
  policyId: zod.string().min(1),
  clientId: zod.string().min(1),
  claimId: zod.union([zod.enum(['']), zod.string()]).optional(),
  type: zod.string().min(1),
  description: zod.union([zod.enum(['']), zod.string()]).optional(),
  address: zod.union([zod.enum(['']), zod.string()]).optional(),
  latitude: zod.number().optional(),
  longitude: zod.number().optional(),
  providerName: zod.union([zod.enum(['']), zod.string()]).optional(),
  providerPhone: zod.union([zod.enum(['']), zod.string()]).optional(),
  scheduledAt: zod
    .union([zod.enum(['']), zod.string().datetime({})])
    .optional(),
})

/**
 * @summary List assistance requests with pagination and filters
 */
export const listAssistancesQueryLimitDefault = 20
export const listAssistancesQueryLimitMax = 100

export const listAssistancesQuerySortByDefault = `createdAt`
export const listAssistancesQuerySortOrderDefault = `desc`

export const ListAssistancesQueryParams = zod.object({
  status: zod
    .enum([
      'REQUESTED',
      'AWAITING_DOCUMENT',
      'PENDING_INSPECTION',
      'DISPATCHED',
      'IN_PROGRESS',
      'COMPLETED',
    ])
    .optional(),
  policyId: zod.string().optional(),
  clientId: zod.string().optional(),
  type: zod.string().optional(),
  search: zod.string().optional(),
  cursor: zod.string().optional(),
  limit: zod
    .number()
    .min(1)
    .max(listAssistancesQueryLimitMax)
    .default(listAssistancesQueryLimitDefault),
  sortBy: zod
    .enum(['type', 'status', 'requestedAt', 'createdAt'])
    .default(listAssistancesQuerySortByDefault),
  sortOrder: zod
    .enum(['asc', 'desc'])
    .default(listAssistancesQuerySortOrderDefault),
})

export const ListAssistancesResponse = zod.object({
  success: zod.literal(true),
  data: zod.array(
    zod.object({
      id: zod.string(),
      organizationId: zod.string(),
      policyId: zod.string(),
      clientId: zod.string(),
      claimId: zod.string().nullable(),
      type: zod.string(),
      status: zod.enum([
        'REQUESTED',
        'AWAITING_DOCUMENT',
        'PENDING_INSPECTION',
        'DISPATCHED',
        'IN_PROGRESS',
        'COMPLETED',
      ]),
      description: zod.string().nullable(),
      address: zod.string().nullable(),
      latitude: zod.number().nullable(),
      longitude: zod.number().nullable(),
      providerName: zod.string().nullable(),
      providerPhone: zod.string().nullable(),
      requestedAt: zod.string().datetime({}),
      scheduledAt: zod.string().datetime({}).nullable(),
      completedAt: zod.string().datetime({}).nullable(),
      createdAt: zod.string().datetime({}),
      updatedAt: zod.string().datetime({}),
      policyNumber: zod.string().optional(),
      clientName: zod.string().optional(),
    })
  ),
  meta: zod.object({
    total: zod.number().optional(),
    nextCursor: zod.string().nullish(),
  }),
})

/**
 * @summary Get an assistance request by ID
 */

export const GetAssistanceParams = zod.object({
  id: zod.string().min(1),
})

export const GetAssistanceResponse = zod.object({
  success: zod.literal(true),
  data: zod.object({
    id: zod.string(),
    organizationId: zod.string(),
    policyId: zod.string(),
    clientId: zod.string(),
    claimId: zod.string().nullable(),
    type: zod.string(),
    status: zod.enum([
      'REQUESTED',
      'AWAITING_DOCUMENT',
      'PENDING_INSPECTION',
      'DISPATCHED',
      'IN_PROGRESS',
      'COMPLETED',
    ]),
    description: zod.string().nullable(),
    address: zod.string().nullable(),
    latitude: zod.number().nullable(),
    longitude: zod.number().nullable(),
    providerName: zod.string().nullable(),
    providerPhone: zod.string().nullable(),
    requestedAt: zod.string().datetime({}),
    scheduledAt: zod.string().datetime({}).nullable(),
    completedAt: zod.string().datetime({}).nullable(),
    createdAt: zod.string().datetime({}),
    updatedAt: zod.string().datetime({}),
    policyNumber: zod.string().optional(),
    clientName: zod.string().optional(),
  }),
})

/**
 * @summary Update the status of an assistance request
 */

export const UpdateAssistanceStatusParams = zod.object({
  id: zod.string().min(1),
})

export const UpdateAssistanceStatusBody = zod.object({
  status: zod.enum([
    'REQUESTED',
    'AWAITING_DOCUMENT',
    'PENDING_INSPECTION',
    'DISPATCHED',
    'IN_PROGRESS',
    'COMPLETED',
  ]),
})

export const UpdateAssistanceStatusResponse = zod.object({
  success: zod.literal(true),
  data: zod.object({
    id: zod.string(),
    organizationId: zod.string(),
    policyId: zod.string(),
    clientId: zod.string(),
    claimId: zod.string().nullable(),
    type: zod.string(),
    status: zod.enum([
      'REQUESTED',
      'AWAITING_DOCUMENT',
      'PENDING_INSPECTION',
      'DISPATCHED',
      'IN_PROGRESS',
      'COMPLETED',
    ]),
    description: zod.string().nullable(),
    address: zod.string().nullable(),
    latitude: zod.number().nullable(),
    longitude: zod.number().nullable(),
    providerName: zod.string().nullable(),
    providerPhone: zod.string().nullable(),
    requestedAt: zod.string().datetime({}),
    scheduledAt: zod.string().datetime({}).nullable(),
    completedAt: zod.string().datetime({}).nullable(),
    createdAt: zod.string().datetime({}),
    updatedAt: zod.string().datetime({}),
    policyNumber: zod.string().optional(),
    clientName: zod.string().optional(),
  }),
})
