/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod'

/**
 * @summary List audit logs with cursor pagination
 */
export const listAuditLogsQueryLimitDefault = 30
export const listAuditLogsQueryLimitMax = 100

export const ListAuditLogsQueryParams = zod.object({
  entityType: zod.string().optional(),
  action: zod.string().optional(),
  userId: zod.string().optional(),
  dateFrom: zod.string().optional(),
  dateTo: zod.string().optional(),
  cursor: zod.string().optional(),
  limit: zod
    .number()
    .min(1)
    .max(listAuditLogsQueryLimitMax)
    .default(listAuditLogsQueryLimitDefault),
})

export const ListAuditLogsResponse = zod.object({
  success: zod.literal(true),
  data: zod.array(
    zod.object({
      id: zod.string(),
      organizationId: zod.string(),
      userId: zod.string().nullable(),
      action: zod.string(),
      entityType: zod.string(),
      entityId: zod.string().nullable(),
      before: zod.unknown().nullish(),
      after: zod.unknown().nullish(),
      ipAddress: zod.string().nullable(),
      userAgent: zod.string().nullable(),
      createdAt: zod.string().datetime({}),
    })
  ),
  meta: zod.object({
    total: zod.number().optional(),
    nextCursor: zod.string().nullish(),
  }),
})
