/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod'

/**
 * @summary List audit logs with cursor pagination
 */
export const listAuditLogsQueryLimitDefault = 30
export const listAuditLogsQueryLimitMax = 100

export const ListAuditLogsQueryParams = zod.object({
  entityType: zod.string().optional(),
  action: zod.string().optional(),
  userId: zod.string().optional(),
  dateFrom: zod.string().optional(),
  dateTo: zod.string().optional(),
  cursor: zod.string().optional(),
  limit: zod
    .number()
    .min(1)
    .max(listAuditLogsQueryLimitMax)
    .default(listAuditLogsQueryLimitDefault),
})
