/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type { ListAuditLogs200, ListAuditLogsParams } from '../../model'

import { customFetch } from '../../../lib/api-mutator'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary List audit logs with cursor pagination
 */
export type listAuditLogsResponse200 = {
  data: ListAuditLogs200
  status: 200
}

export type listAuditLogsResponseSuccess = listAuditLogsResponse200 & {
  headers: Headers
}
export type listAuditLogsResponse = listAuditLogsResponseSuccess

export const getListAuditLogsUrl = (params?: ListAuditLogsParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/v1/audit-logs?${stringifiedParams}`
    : `/api/v1/audit-logs`
}

export const listAuditLogs = async (
  params?: ListAuditLogsParams,
  options?: RequestInit
): Promise<listAuditLogsResponse> => {
  return customFetch<listAuditLogsResponse>(getListAuditLogsUrl(params), {
    ...options,
    method: 'GET',
  })
}

export const getListAuditLogsQueryKey = (params?: ListAuditLogsParams) => {
  return [`/api/v1/audit-logs`, ...(params ? [params] : [])] as const
}

export const getListAuditLogsQueryOptions = <
  TData = Awaited<ReturnType<typeof listAuditLogs>>,
  TError = unknown,
>(
  params?: ListAuditLogsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listAuditLogs>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getListAuditLogsQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listAuditLogs>>> = ({
    signal,
  }) => listAuditLogs(params, { signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    staleTime: 60000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof listAuditLogs>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListAuditLogsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listAuditLogs>>
>
export type ListAuditLogsQueryError = unknown

export function useListAuditLogs<
  TData = Awaited<ReturnType<typeof listAuditLogs>>,
  TError = unknown,
>(
  params: undefined | ListAuditLogsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listAuditLogs>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAuditLogs>>,
          TError,
          Awaited<ReturnType<typeof listAuditLogs>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useListAuditLogs<
  TData = Awaited<ReturnType<typeof listAuditLogs>>,
  TError = unknown,
>(
  params?: ListAuditLogsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listAuditLogs>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAuditLogs>>,
          TError,
          Awaited<ReturnType<typeof listAuditLogs>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useListAuditLogs<
  TData = Awaited<ReturnType<typeof listAuditLogs>>,
  TError = unknown,
>(
  params?: ListAuditLogsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listAuditLogs>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary List audit logs with cursor pagination
 */

export function useListAuditLogs<
  TData = Awaited<ReturnType<typeof listAuditLogs>>,
  TError = unknown,
>(
  params?: ListAuditLogsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listAuditLogs>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getListAuditLogsQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * @summary List audit logs with cursor pagination
 */
export const prefetchListAuditLogsQuery = async <
  TData = Awaited<ReturnType<typeof listAuditLogs>>,
  TError = unknown,
>(
  queryClient: QueryClient,
  params?: ListAuditLogsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listAuditLogs>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  }
): Promise<QueryClient> => {
  const queryOptions = getListAuditLogsQueryOptions(params, options)

  await queryClient.prefetchQuery(queryOptions)

  return queryClient
}
