/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod'

/**
 * @summary Lookup Brazilian address by postal code (CEP)
 */
export const GetCepParams = zod.object({
  cep: zod.string(),
})

export const getCepResponseDataZipCodeMin = 8
export const getCepResponseDataZipCodeMax = 8

export const getCepResponseDataStateMin = 2
export const getCepResponseDataStateMax = 2

export const GetCepResponse = zod.object({
  success: zod.literal(true),
  data: zod.object({
    zipCode: zod
      .string()
      .min(getCepResponseDataZipCodeMin)
      .max(getCepResponseDataZipCodeMax),
    street: zod.string(),
    neighborhood: zod.string(),
    city: zod.string(),
    state: zod
      .string()
      .min(getCepResponseDataStateMin)
      .max(getCepResponseDataStateMax),
    complement: zod.string().nullable(),
  }),
})
