/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod'

/**
 * @summary Get dashboard statistics
 */
export const getDashboardStatsQueryPresetDefault = `30d`

export const GetDashboardStatsQueryParams = zod.object({
  preset: zod
    .enum(['7d', '30d', '90d', '6m'])
    .default(getDashboardStatsQueryPresetDefault),
})

/**
 * @summary Export dashboard report as PDF
 */
export const exportDashboardPdfQueryPresetDefault = `30d`

export const ExportDashboardPdfQueryParams = zod.object({
  preset: zod
    .enum(['7d', '30d', '90d', '6m'])
    .default(exportDashboardPdfQueryPresetDefault),
})
