/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod'

/**
 * @summary Get dashboard statistics
 */
export const getDashboardStatsQueryPresetDefault = `30d`

export const GetDashboardStatsQueryParams = zod.object({
  preset: zod
    .enum(['7d', '30d', '90d', '6m'])
    .default(getDashboardStatsQueryPresetDefault),
})

export const GetDashboardStatsResponse = zod.object({
  success: zod.literal(true),
  data: zod.object({
    proposalsByStage: zod.array(
      zod.object({
        stage: zod.string(),
        _count: zod.number(),
      })
    ),
    activePolicies: zod.number(),
    expiringPolicies: zod.number(),
    claimsByPriority: zod.array(
      zod.object({
        priority: zod.string(),
        _count: zod.number(),
      })
    ),
    commissionsThisMonth: zod.array(
      zod.object({
        status: zod.string(),
        _count: zod.number(),
        _sum: zod.object({
          commissionValueInCents: zod.number().nullable(),
        }),
      })
    ),
    conversionRate: zod.object({
      total: zod.number(),
      issued: zod.number(),
      rate: zod.number(),
    }),
    monthlyTrends: zod.array(
      zod.object({
        month: zod.string(),
        proposals: zod.number(),
        issued: zod.number(),
      })
    ),
    comparison: zod.object({
      proposals: zod.object({
        current: zod.number(),
        previous: zod.number(),
        changePercent: zod.number(),
      }),
      policies: zod.object({
        current: zod.number(),
        previous: zod.number(),
        changePercent: zod.number(),
      }),
      claims: zod.object({
        current: zod.number(),
        previous: zod.number(),
        changePercent: zod.number(),
      }),
      commissionsPending: zod.object({
        current: zod.number(),
        previous: zod.number(),
        changePercent: zod.number(),
      }),
    }),
    totalPremium: zod.object({
      current: zod.number(),
      previous: zod.number(),
      changePercent: zod.number(),
    }),
    averageTicket: zod.object({
      current: zod.number(),
      previous: zod.number(),
      changePercent: zod.number(),
    }),
    commissionsReceivable: zod.number(),
    ranking: zod.array(
      zod.object({
        salespersonId: zod.string(),
        salespersonName: zod.string(),
        policiesIssued: zod.number(),
        totalPremiumCents: zod.number(),
        averageTicketCents: zod.number(),
      })
    ),
  }),
})

/**
 * @summary Export dashboard report as PDF
 */
export const exportDashboardPdfQueryPresetDefault = `30d`

export const ExportDashboardPdfQueryParams = zod.object({
  preset: zod
    .enum(['7d', '30d', '90d', '6m'])
    .default(exportDashboardPdfQueryPresetDefault),
})

export const ExportDashboardPdfResponse = zod.object({
  success: zod.literal(true),
  data: zod.object({
    url: zod.string(),
  }),
})
