/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation } from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query'

import { customFetch } from '../../../lib/api-mutator'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Create a JWT token for chat authentication
 */
export type createChatTokenResponse200 = {
  data: void
  status: 200
}

export type createChatTokenResponseSuccess = createChatTokenResponse200 & {
  headers: Headers
}
export type createChatTokenResponse = createChatTokenResponseSuccess

export const getCreateChatTokenUrl = () => {
  return `/api/v1/chat/token`
}

export const createChatToken = async (
  options?: RequestInit
): Promise<createChatTokenResponse> => {
  return customFetch<createChatTokenResponse>(getCreateChatTokenUrl(), {
    ...options,
    method: 'POST',
  })
}

export const getCreateChatTokenMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createChatToken>>,
    TError,
    void,
    TContext
  >
  request?: SecondParameter<typeof customFetch>
}): UseMutationOptions<
  Awaited<ReturnType<typeof createChatToken>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['createChatToken']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createChatToken>>,
    void
  > = () => {
    return createChatToken(requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type CreateChatTokenMutationResult = NonNullable<
  Awaited<ReturnType<typeof createChatToken>>
>

export type CreateChatTokenMutationError = unknown

/**
 * @summary Create a JWT token for chat authentication
 */
export const useCreateChatToken = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createChatToken>>,
      TError,
      void,
      TContext
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof createChatToken>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getCreateChatTokenMutationOptions(options), queryClient)
}
