/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type {
  DeactivateMember200,
  ListMembers200,
  ListMembersParams,
  UpdateMemberRole200,
  UpdateMemberRoleBody,
} from '../../model'

import { customFetch } from '../../../lib/api-mutator'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary List organization members
 */
export type listMembersResponse200 = {
  data: ListMembers200
  status: 200
}

export type listMembersResponseSuccess = listMembersResponse200 & {
  headers: Headers
}
export type listMembersResponse = listMembersResponseSuccess

export const getListMembersUrl = (params?: ListMembersParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/v1/members?${stringifiedParams}`
    : `/api/v1/members`
}

export const listMembers = async (
  params?: ListMembersParams,
  options?: RequestInit
): Promise<listMembersResponse> => {
  return customFetch<listMembersResponse>(getListMembersUrl(params), {
    ...options,
    method: 'GET',
  })
}

export const getListMembersQueryKey = (params?: ListMembersParams) => {
  return [`/api/v1/members`, ...(params ? [params] : [])] as const
}

export const getListMembersQueryOptions = <
  TData = Awaited<ReturnType<typeof listMembers>>,
  TError = unknown,
>(
  params?: ListMembersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listMembers>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getListMembersQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listMembers>>> = ({
    signal,
  }) => listMembers(params, { signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    staleTime: 60000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof listMembers>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListMembersQueryResult = NonNullable<
  Awaited<ReturnType<typeof listMembers>>
>
export type ListMembersQueryError = unknown

export function useListMembers<
  TData = Awaited<ReturnType<typeof listMembers>>,
  TError = unknown,
>(
  params: undefined | ListMembersParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listMembers>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMembers>>,
          TError,
          Awaited<ReturnType<typeof listMembers>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useListMembers<
  TData = Awaited<ReturnType<typeof listMembers>>,
  TError = unknown,
>(
  params?: ListMembersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listMembers>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMembers>>,
          TError,
          Awaited<ReturnType<typeof listMembers>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useListMembers<
  TData = Awaited<ReturnType<typeof listMembers>>,
  TError = unknown,
>(
  params?: ListMembersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listMembers>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary List organization members
 */

export function useListMembers<
  TData = Awaited<ReturnType<typeof listMembers>>,
  TError = unknown,
>(
  params?: ListMembersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listMembers>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getListMembersQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * @summary List organization members
 */
export const prefetchListMembersQuery = async <
  TData = Awaited<ReturnType<typeof listMembers>>,
  TError = unknown,
>(
  queryClient: QueryClient,
  params?: ListMembersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listMembers>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  }
): Promise<QueryClient> => {
  const queryOptions = getListMembersQueryOptions(params, options)

  await queryClient.prefetchQuery(queryOptions)

  return queryClient
}

/**
 * @summary Update a member role
 */
export type updateMemberRoleResponse200 = {
  data: UpdateMemberRole200
  status: 200
}

export type updateMemberRoleResponseSuccess = updateMemberRoleResponse200 & {
  headers: Headers
}
export type updateMemberRoleResponse = updateMemberRoleResponseSuccess

export const getUpdateMemberRoleUrl = (id: string) => {
  return `/api/v1/members/${id}/role`
}

export const updateMemberRole = async (
  id: string,
  updateMemberRoleBody: UpdateMemberRoleBody,
  options?: RequestInit
): Promise<updateMemberRoleResponse> => {
  return customFetch<updateMemberRoleResponse>(getUpdateMemberRoleUrl(id), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateMemberRoleBody),
  })
}

export const getUpdateMemberRoleMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateMemberRole>>,
    TError,
    { id: string; data: UpdateMemberRoleBody },
    TContext
  >
  request?: SecondParameter<typeof customFetch>
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateMemberRole>>,
  TError,
  { id: string; data: UpdateMemberRoleBody },
  TContext
> => {
  const mutationKey = ['updateMemberRole']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateMemberRole>>,
    { id: string; data: UpdateMemberRoleBody }
  > = (props) => {
    const { id, data } = props ?? {}

    return updateMemberRole(id, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UpdateMemberRoleMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateMemberRole>>
>
export type UpdateMemberRoleMutationBody = UpdateMemberRoleBody
export type UpdateMemberRoleMutationError = unknown

/**
 * @summary Update a member role
 */
export const useUpdateMemberRole = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateMemberRole>>,
      TError,
      { id: string; data: UpdateMemberRoleBody },
      TContext
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof updateMemberRole>>,
  TError,
  { id: string; data: UpdateMemberRoleBody },
  TContext
> => {
  return useMutation(getUpdateMemberRoleMutationOptions(options), queryClient)
}
/**
 * @summary Deactivate a member
 */
export type deactivateMemberResponse200 = {
  data: DeactivateMember200
  status: 200
}

export type deactivateMemberResponseSuccess = deactivateMemberResponse200 & {
  headers: Headers
}
export type deactivateMemberResponse = deactivateMemberResponseSuccess

export const getDeactivateMemberUrl = (id: string) => {
  return `/api/v1/members/${id}`
}

export const deactivateMember = async (
  id: string,
  options?: RequestInit
): Promise<deactivateMemberResponse> => {
  return customFetch<deactivateMemberResponse>(getDeactivateMemberUrl(id), {
    ...options,
    method: 'DELETE',
  })
}

export const getDeactivateMemberMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deactivateMember>>,
    TError,
    { id: string },
    TContext
  >
  request?: SecondParameter<typeof customFetch>
}): UseMutationOptions<
  Awaited<ReturnType<typeof deactivateMember>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['deactivateMember']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deactivateMember>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {}

    return deactivateMember(id, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type DeactivateMemberMutationResult = NonNullable<
  Awaited<ReturnType<typeof deactivateMember>>
>

export type DeactivateMemberMutationError = unknown

/**
 * @summary Deactivate a member
 */
export const useDeactivateMember = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deactivateMember>>,
      TError,
      { id: string },
      TContext
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof deactivateMember>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getDeactivateMemberMutationOptions(options), queryClient)
}
