/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod'

/**
 * @summary List organization members
 */
export const listMembersQueryLimitDefault = 50
export const listMembersQueryLimitMax = 100

export const ListMembersQueryParams = zod.object({
  cursor: zod.string().optional(),
  limit: zod
    .number()
    .min(1)
    .max(listMembersQueryLimitMax)
    .default(listMembersQueryLimitDefault),
})

export const ListMembersResponse = zod.object({
  success: zod.literal(true),
  data: zod.array(
    zod.object({
      id: zod.string(),
      userId: zod.string(),
      name: zod.string().nullable(),
      email: zod.string(),
      role: zod.string(),
      active: zod.boolean(),
      createdAt: zod.string(),
    })
  ),
  meta: zod.object({
    total: zod.number().optional(),
    nextCursor: zod.string().nullish(),
  }),
})

/**
 * @summary Update a member role
 */

export const UpdateMemberRoleParams = zod.object({
  id: zod.string().min(1),
})

export const UpdateMemberRoleBody = zod.object({
  role: zod.enum(['ADMIN', 'MANAGER', 'COMMERCIAL', 'VIEWER']),
})

export const UpdateMemberRoleResponse = zod.object({
  success: zod.literal(true),
  data: zod.object({
    id: zod.string(),
    userId: zod.string(),
    organizationId: zod.string(),
    role: zod.string(),
    active: zod.boolean(),
  }),
})

/**
 * @summary Deactivate a member
 */

export const DeactivateMemberParams = zod.object({
  id: zod.string().min(1),
})

export const DeactivateMemberResponse = zod.object({
  success: zod.literal(true),
  data: zod.object({
    id: zod.string(),
  }),
})
