/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation } from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query'

import type { LookupVehicle200, LookupVehicleBody } from '../../model'

import { customFetch } from '../../../lib/api-mutator'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Lookup vehicle data by plate or chassi
 */
export type lookupVehicleResponse200 = {
  data: LookupVehicle200
  status: 200
}

export type lookupVehicleResponseSuccess = lookupVehicleResponse200 & {
  headers: Headers
}
export type lookupVehicleResponse = lookupVehicleResponseSuccess

export const getLookupVehicleUrl = () => {
  return `/api/v1/vehicles/lookup`
}

export const lookupVehicle = async (
  lookupVehicleBody: LookupVehicleBody,
  options?: RequestInit
): Promise<lookupVehicleResponse> => {
  return customFetch<lookupVehicleResponse>(getLookupVehicleUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(lookupVehicleBody),
  })
}

export const getLookupVehicleMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof lookupVehicle>>,
    TError,
    { data: LookupVehicleBody },
    TContext
  >
  request?: SecondParameter<typeof customFetch>
}): UseMutationOptions<
  Awaited<ReturnType<typeof lookupVehicle>>,
  TError,
  { data: LookupVehicleBody },
  TContext
> => {
  const mutationKey = ['lookupVehicle']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof lookupVehicle>>,
    { data: LookupVehicleBody }
  > = (props) => {
    const { data } = props ?? {}

    return lookupVehicle(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type LookupVehicleMutationResult = NonNullable<
  Awaited<ReturnType<typeof lookupVehicle>>
>
export type LookupVehicleMutationBody = LookupVehicleBody
export type LookupVehicleMutationError = unknown

/**
 * @summary Lookup vehicle data by plate or chassi
 */
export const useLookupVehicle = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof lookupVehicle>>,
      TError,
      { data: LookupVehicleBody },
      TContext
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof lookupVehicle>>,
  TError,
  { data: LookupVehicleBody },
  TContext
> => {
  return useMutation(getLookupVehicleMutationOptions(options), queryClient)
}
