export const PII_REDACT_PATHS = [
  'cpf',
  'cnpj',
  'rg',
  'email',
  'phone',
  'password',
  'token',
  'birthDate',
  'document',
  'body.cpf',
  'body.cnpj',
  'body.email',
  'body.phone',
  'body.document',
  'body.rg',
  'body.birthDate',
  'req.body.cpf',
  'req.body.cnpj',
  'req.body.email',
  'req.body.phone',
  'req.body.password',
  'req.body.document',
  'req.body.rg',
  'req.body.birthDate',
  'req.headers.authorization',
  'req.headers.cookie',
  'metaToken',
  'access_token',
  'fb_exchange_token',
  'client_secret',
  'code',
  'config.metaToken',
  '*.metaToken',
  '*.access_token',
  '*.code',
  'body.code',
  'body.access_token',
  'body.metaToken',
  'req.body.code',
  'req.body.access_token',
] as const

export const PINO_REDACT_CONFIG: { paths: string[]; censor: string } = {
  paths: [...PII_REDACT_PATHS],
  censor: '[REDACTED]',
}
