/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type {
  GetBillingCurrent200,
  ListBillingInvoices200,
  ListBillingInvoicesParams,
} from '../../model'

import { customFetch } from '../../../lib/api-mutator'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Get current subscription and entitlements for the active org
 */
export type getBillingCurrentResponse200 = {
  data: GetBillingCurrent200
  status: 200
}

export type getBillingCurrentResponseSuccess = getBillingCurrentResponse200 & {
  headers: Headers
}
export type getBillingCurrentResponse = getBillingCurrentResponseSuccess

export const getGetBillingCurrentUrl = () => {
  return `/api/v1/billing/current`
}

export const getBillingCurrent = async (
  options?: RequestInit
): Promise<getBillingCurrentResponse> => {
  return customFetch<getBillingCurrentResponse>(getGetBillingCurrentUrl(), {
    ...options,
    method: 'GET',
  })
}

export const getGetBillingCurrentQueryKey = () => {
  return [`/api/v1/billing/current`] as const
}

export const getGetBillingCurrentQueryOptions = <
  TData = Awaited<ReturnType<typeof getBillingCurrent>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getBillingCurrent>>,
      TError,
      TData
    >
  >
  request?: SecondParameter<typeof customFetch>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetBillingCurrentQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getBillingCurrent>>
  > = ({ signal }) => getBillingCurrent({ signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    staleTime: 60000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getBillingCurrent>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetBillingCurrentQueryResult = NonNullable<
  Awaited<ReturnType<typeof getBillingCurrent>>
>
export type GetBillingCurrentQueryError = unknown

export function useGetBillingCurrent<
  TData = Awaited<ReturnType<typeof getBillingCurrent>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBillingCurrent>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBillingCurrent>>,
          TError,
          Awaited<ReturnType<typeof getBillingCurrent>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetBillingCurrent<
  TData = Awaited<ReturnType<typeof getBillingCurrent>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBillingCurrent>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBillingCurrent>>,
          TError,
          Awaited<ReturnType<typeof getBillingCurrent>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetBillingCurrent<
  TData = Awaited<ReturnType<typeof getBillingCurrent>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBillingCurrent>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get current subscription and entitlements for the active org
 */

export function useGetBillingCurrent<
  TData = Awaited<ReturnType<typeof getBillingCurrent>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBillingCurrent>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetBillingCurrentQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * @summary Get current subscription and entitlements for the active org
 */
export const prefetchGetBillingCurrentQuery = async <
  TData = Awaited<ReturnType<typeof getBillingCurrent>>,
  TError = unknown,
>(
  queryClient: QueryClient,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBillingCurrent>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customFetch>
  }
): Promise<QueryClient> => {
  const queryOptions = getGetBillingCurrentQueryOptions(options)

  await queryClient.prefetchQuery(queryOptions)

  return queryClient
}

/**
 * @summary List invoices for the active org (cursor pagination)
 */
export type listBillingInvoicesResponse200 = {
  data: ListBillingInvoices200
  status: 200
}

export type listBillingInvoicesResponseSuccess =
  listBillingInvoicesResponse200 & {
    headers: Headers
  }
export type listBillingInvoicesResponse = listBillingInvoicesResponseSuccess

export const getListBillingInvoicesUrl = (
  params?: ListBillingInvoicesParams
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/api/v1/billing/invoices?${stringifiedParams}`
    : `/api/v1/billing/invoices`
}

export const listBillingInvoices = async (
  params?: ListBillingInvoicesParams,
  options?: RequestInit
): Promise<listBillingInvoicesResponse> => {
  return customFetch<listBillingInvoicesResponse>(
    getListBillingInvoicesUrl(params),
    {
      ...options,
      method: 'GET',
    }
  )
}

export const getListBillingInvoicesQueryKey = (
  params?: ListBillingInvoicesParams
) => {
  return [`/api/v1/billing/invoices`, ...(params ? [params] : [])] as const
}

export const getListBillingInvoicesQueryOptions = <
  TData = Awaited<ReturnType<typeof listBillingInvoices>>,
  TError = unknown,
>(
  params?: ListBillingInvoicesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listBillingInvoices>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customFetch>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getListBillingInvoicesQueryKey(params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listBillingInvoices>>
  > = ({ signal }) => listBillingInvoices(params, { signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    staleTime: 60000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof listBillingInvoices>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListBillingInvoicesQueryResult = NonNullable<
  Awaited<ReturnType<typeof listBillingInvoices>>
>
export type ListBillingInvoicesQueryError = unknown

export function useListBillingInvoices<
  TData = Awaited<ReturnType<typeof listBillingInvoices>>,
  TError = unknown,
>(
  params: undefined | ListBillingInvoicesParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listBillingInvoices>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listBillingInvoices>>,
          TError,
          Awaited<ReturnType<typeof listBillingInvoices>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useListBillingInvoices<
  TData = Awaited<ReturnType<typeof listBillingInvoices>>,
  TError = unknown,
>(
  params?: ListBillingInvoicesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listBillingInvoices>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listBillingInvoices>>,
          TError,
          Awaited<ReturnType<typeof listBillingInvoices>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useListBillingInvoices<
  TData = Awaited<ReturnType<typeof listBillingInvoices>>,
  TError = unknown,
>(
  params?: ListBillingInvoicesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listBillingInvoices>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary List invoices for the active org (cursor pagination)
 */

export function useListBillingInvoices<
  TData = Awaited<ReturnType<typeof listBillingInvoices>>,
  TError = unknown,
>(
  params?: ListBillingInvoicesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listBillingInvoices>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getListBillingInvoicesQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * @summary List invoices for the active org (cursor pagination)
 */
export const prefetchListBillingInvoicesQuery = async <
  TData = Awaited<ReturnType<typeof listBillingInvoices>>,
  TError = unknown,
>(
  queryClient: QueryClient,
  params?: ListBillingInvoicesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listBillingInvoices>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customFetch>
  }
): Promise<QueryClient> => {
  const queryOptions = getListBillingInvoicesQueryOptions(params, options)

  await queryClient.prefetchQuery(queryOptions)

  return queryClient
}
