/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import { customFetch } from '../../../lib/api-mutator'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export type getHealthResponse200 = {
  data: void
  status: 200
}

export type getHealthResponseSuccess = getHealthResponse200 & {
  headers: Headers
}
export type getHealthResponse = getHealthResponseSuccess

export const getGetHealthUrl = () => {
  return `/health`
}

export const getHealth = async (
  options?: RequestInit
): Promise<getHealthResponse> => {
  return customFetch<getHealthResponse>(getGetHealthUrl(), {
    ...options,
    method: 'GET',
  })
}

export const getGetHealthQueryKey = () => {
  return [`/health`] as const
}

export const getGetHealthQueryOptions = <
  TData = Awaited<ReturnType<typeof getHealth>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>
  >
  request?: SecondParameter<typeof customFetch>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetHealthQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getHealth>>> = ({
    signal,
  }) => getHealth({ signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    staleTime: 60000,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }
}

export type GetHealthQueryResult = NonNullable<
  Awaited<ReturnType<typeof getHealth>>
>
export type GetHealthQueryError = unknown

export function useGetHealth<
  TData = Awaited<ReturnType<typeof getHealth>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHealth>>,
          TError,
          Awaited<ReturnType<typeof getHealth>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetHealth<
  TData = Awaited<ReturnType<typeof getHealth>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHealth>>,
          TError,
          Awaited<ReturnType<typeof getHealth>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetHealth<
  TData = Awaited<ReturnType<typeof getHealth>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}

export function useGetHealth<
  TData = Awaited<ReturnType<typeof getHealth>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetHealthQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

export const prefetchGetHealthQuery = async <
  TData = Awaited<ReturnType<typeof getHealth>>,
  TError = unknown,
>(
  queryClient: QueryClient,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  }
): Promise<QueryClient> => {
  const queryOptions = getGetHealthQueryOptions(options)

  await queryClient.prefetchQuery(queryOptions)

  return queryClient
}

export type postApiWebhooksAsaasResponse200 = {
  data: void
  status: 200
}

export type postApiWebhooksAsaasResponseSuccess =
  postApiWebhooksAsaasResponse200 & {
    headers: Headers
  }
export type postApiWebhooksAsaasResponse = postApiWebhooksAsaasResponseSuccess

export const getPostApiWebhooksAsaasUrl = () => {
  return `/api/webhooks/asaas`
}

export const postApiWebhooksAsaas = async (
  options?: RequestInit
): Promise<postApiWebhooksAsaasResponse> => {
  return customFetch<postApiWebhooksAsaasResponse>(
    getPostApiWebhooksAsaasUrl(),
    {
      ...options,
      method: 'POST',
    }
  )
}

export const getPostApiWebhooksAsaasMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiWebhooksAsaas>>,
    TError,
    void,
    TContext
  >
  request?: SecondParameter<typeof customFetch>
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiWebhooksAsaas>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['postApiWebhooksAsaas']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiWebhooksAsaas>>,
    void
  > = () => {
    return postApiWebhooksAsaas(requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostApiWebhooksAsaasMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiWebhooksAsaas>>
>

export type PostApiWebhooksAsaasMutationError = unknown

export const usePostApiWebhooksAsaas = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiWebhooksAsaas>>,
      TError,
      void,
      TContext
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof postApiWebhooksAsaas>>,
  TError,
  void,
  TContext
> => {
  return useMutation(
    getPostApiWebhooksAsaasMutationOptions(options),
    queryClient
  )
}
