/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import { customFetch } from '../../../lib/api-mutator'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export type getHealthResponse200 = {
  data: void
  status: 200
}

export type getHealthResponseSuccess = getHealthResponse200 & {
  headers: Headers
}
export type getHealthResponse = getHealthResponseSuccess

export const getGetHealthUrl = () => {
  return `/health`
}

export const getHealth = async (
  options?: RequestInit
): Promise<getHealthResponse> => {
  return customFetch<getHealthResponse>(getGetHealthUrl(), {
    ...options,
    method: 'GET',
  })
}

export const getGetHealthQueryKey = () => {
  return [`/health`] as const
}

export const getGetHealthQueryOptions = <
  TData = Awaited<ReturnType<typeof getHealth>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>
  >
  request?: SecondParameter<typeof customFetch>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetHealthQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getHealth>>> = ({
    signal,
  }) => getHealth({ signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    staleTime: 60000,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }
}

export type GetHealthQueryResult = NonNullable<
  Awaited<ReturnType<typeof getHealth>>
>
export type GetHealthQueryError = unknown

export function useGetHealth<
  TData = Awaited<ReturnType<typeof getHealth>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHealth>>,
          TError,
          Awaited<ReturnType<typeof getHealth>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetHealth<
  TData = Awaited<ReturnType<typeof getHealth>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHealth>>,
          TError,
          Awaited<ReturnType<typeof getHealth>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetHealth<
  TData = Awaited<ReturnType<typeof getHealth>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}

export function useGetHealth<
  TData = Awaited<ReturnType<typeof getHealth>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetHealthQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

export const prefetchGetHealthQuery = async <
  TData = Awaited<ReturnType<typeof getHealth>>,
  TError = unknown,
>(
  queryClient: QueryClient,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  }
): Promise<QueryClient> => {
  const queryOptions = getGetHealthQueryOptions(options)

  await queryClient.prefetchQuery(queryOptions)

  return queryClient
}

export type getApiAuthResponse200 = {
  data: void
  status: 200
}

export type getApiAuthResponseSuccess = getApiAuthResponse200 & {
  headers: Headers
}
export type getApiAuthResponse = getApiAuthResponseSuccess

export const getGetApiAuthUrl = (wildcard: string) => {
  return `/api/auth/${wildcard}`
}

export const getApiAuth = async (
  wildcard: string,
  options?: RequestInit
): Promise<getApiAuthResponse> => {
  return customFetch<getApiAuthResponse>(getGetApiAuthUrl(wildcard), {
    ...options,
    method: 'GET',
  })
}

export const getGetApiAuthQueryKey = (wildcard: string) => {
  return [`/api/auth/${wildcard}`] as const
}

export const getGetApiAuthQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiAuth>>,
  TError = unknown,
>(
  wildcard: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiAuth>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetApiAuthQueryKey(wildcard)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAuth>>> = ({
    signal,
  }) => getApiAuth(wildcard, { signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    enabled: !!wildcard,
    staleTime: 60000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiAuth>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAuthQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiAuth>>
>
export type GetApiAuthQueryError = unknown

export function useGetApiAuth<
  TData = Awaited<ReturnType<typeof getApiAuth>>,
  TError = unknown,
>(
  wildcard: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiAuth>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAuth>>,
          TError,
          Awaited<ReturnType<typeof getApiAuth>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetApiAuth<
  TData = Awaited<ReturnType<typeof getApiAuth>>,
  TError = unknown,
>(
  wildcard: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiAuth>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAuth>>,
          TError,
          Awaited<ReturnType<typeof getApiAuth>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetApiAuth<
  TData = Awaited<ReturnType<typeof getApiAuth>>,
  TError = unknown,
>(
  wildcard: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiAuth>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}

export function useGetApiAuth<
  TData = Awaited<ReturnType<typeof getApiAuth>>,
  TError = unknown,
>(
  wildcard: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiAuth>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetApiAuthQueryOptions(wildcard, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

export const prefetchGetApiAuthQuery = async <
  TData = Awaited<ReturnType<typeof getApiAuth>>,
  TError = unknown,
>(
  queryClient: QueryClient,
  wildcard: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiAuth>>, TError, TData>
    >
    request?: SecondParameter<typeof customFetch>
  }
): Promise<QueryClient> => {
  const queryOptions = getGetApiAuthQueryOptions(wildcard, options)

  await queryClient.prefetchQuery(queryOptions)

  return queryClient
}

export type postApiAuthResponse200 = {
  data: void
  status: 200
}

export type postApiAuthResponseSuccess = postApiAuthResponse200 & {
  headers: Headers
}
export type postApiAuthResponse = postApiAuthResponseSuccess

export const getPostApiAuthUrl = (wildcard: string) => {
  return `/api/auth/${wildcard}`
}

export const postApiAuth = async (
  wildcard: string,
  options?: RequestInit
): Promise<postApiAuthResponse> => {
  return customFetch<postApiAuthResponse>(getPostApiAuthUrl(wildcard), {
    ...options,
    method: 'POST',
  })
}

export const getPostApiAuthMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiAuth>>,
    TError,
    { wildcard: string },
    TContext
  >
  request?: SecondParameter<typeof customFetch>
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiAuth>>,
  TError,
  { wildcard: string },
  TContext
> => {
  const mutationKey = ['postApiAuth']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiAuth>>,
    { wildcard: string }
  > = ({ wildcard }) => {
    return postApiAuth(wildcard, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostApiAuthMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiAuth>>
>

export type PostApiAuthMutationError = unknown

export const usePostApiAuth = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiAuth>>,
      TError,
      { wildcard: string },
      TContext
    >
    request?: SecondParameter<typeof customFetch>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof postApiAuth>>,
  TError,
  { wildcard: string },
  TContext
> => {
  return useMutation(getPostApiAuthMutationOptions(options), queryClient)
}
