/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod'

/**
 * @summary Global search across clients, proposals, policies and claims
 */
export const globalSearchQueryQMin = 2
export const globalSearchQueryQMax = 100

export const globalSearchQueryLimitDefault = 10
export const globalSearchQueryLimitMax = 20

export const GlobalSearchQueryParams = zod.object({
  q: zod.string().min(globalSearchQueryQMin).max(globalSearchQueryQMax),
  limit: zod
    .number()
    .min(1)
    .max(globalSearchQueryLimitMax)
    .default(globalSearchQueryLimitDefault),
})

export const GlobalSearchResponse = zod.object({
  success: zod.literal(true),
  data: zod.object({
    clients: zod.array(
      zod.object({
        id: zod.string(),
        name: zod.string(),
        document: zod.string(),
        type: zod.string(),
      })
    ),
    proposals: zod.array(
      zod.object({
        id: zod.string(),
        stage: zod.string(),
        branch: zod.string(),
        clientName: zod.string(),
      })
    ),
    policies: zod.array(
      zod.object({
        id: zod.string(),
        policyNumber: zod.string(),
        branch: zod.string(),
        clientName: zod.string(),
      })
    ),
    claims: zod.array(
      zod.object({
        id: zod.string(),
        claimNumber: zod.number(),
        status: zod.string(),
        clientName: zod.string(),
      })
    ),
  }),
  meta: zod.object({
    query: zod.string(),
    totalResults: zod.number(),
  }),
})
